### ISSUE TITLE
Line 1: 404:: command not found

### ISSUE THREAD

**Issue by pb1051** [complexorganizations/wireguard-manager#1]
**Describe the bug**
After installing and adding a peer, I wanted to add another peer and received the error:
`root@ubuntu-s-1vcpu-1gb-nyc1-01:/etc/wireguard# bash /etc/wireguard/wireguard-server.sh
/etc/wireguard/wireguard-server.sh: line 1: 404:: command not found`

**To Reproduce**
1. Install on Digital Ocean Droplet
2. Try to run the script again
3. Error

**Expected behavior**
I should get the options the script allows

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-96-generic x86_64)

**Additional context**
This worked until I rebooted

**Comment by pb1051** [comment]
I re-ran the curl command and then the bash script and got the configuration options again.

**Comment by Prajwal-Koirala** [comment]
can i close this issue??

**Comment by Prajwal-Koirala** [comment]
![technology (1)](https://user-images.githubusercontent.com/16564273/82120923-5ad3cb80-9757-11ea-992c-05b595a8bd39.png)
