### ISSUE TITLE
Wireguard client randomly deactivates tunnel then crashes

### ISSUE THREAD

**Issue by teammate165** [complexorganizations/wireguard-manager#103]
**Describe the bug**
A couple of clients seem to randomly disconnect after a few minutes. I'm quite sure this has nothing to do with the bash script which you've done a fine job and for that I'm grateful. I've been scratching my head for the past 2 days trying to fix this issue for my friend.

Couple of reddit/forum posts all seem to be a dead-end with 1 suggesting it had something to do with the router's firewall. Wireguard client Logs reports. So I'm making this issue to seek out help about this problem.

**To Reproduce**
1. Generate a new config
2. Send the config to client and load the config
3. Activate the config
4. Wait for roughly 3-5 minutes for the disconnect to happen. Sometimes it will stay on longer than 10 minutes before disconnecting.

**Expected behavior**
Connection should be maintained unless the user requested to deactivate

**Screenshots**

**Client:**
 - OS: Windows 10
 - Wireguard Client v0.3.7
 - Client's config:
```
# https://www.wireguard.com
[Interface]
Address = 10.8.0.8/24,fd42:42:42::8/64
DNS = 1.1.1.1,1.0.0.1,2606:4700:4700::1111,2606:4700:4700::1001
ListenPort = 56930
MTU = 1420
PrivateKey = HIDDEN
[Peer]
AllowedIPs = 0.0.0.0/5,8.0.0.0/7,11.0.0.0/8,12.0.0.0/6,16.0.0.0/4,32.0.0.0/3,64.0.0.0/2,128.0.0.0/3,160.0.0.0/5,168.0.0.0/6,172.0.0.0/12,172.32.0.0/11,172.64.0.0/10,172.128.0.0/9,173.0.0.0/8,174.0.0.0/7,176.0.0.0/4,192.0.0.0/9,192.128.0.0/11,192.160.0.0/13,192.169.0.0/16,192.170.0.0/15,192.172.0.0/14,192.176.0.0/12,192.192.0.0/10,193.0.0.0/8,194.0.0.0/7,196.0.0.0/6,200.0.0.0/5,208.0.0.0/4,::/0
Endpoint = IP:51820
PersistentKeepalive = 25
PresharedKey = HIDDEN
PublicKey = HIDDEN
```

**Server:**
 - OS: CentOS 7 
 - Kernel: 3.10.0-1160.15.2.el7.x86_64
 - Script Version: Latest Commit
 - Server's config
```
interface: wg0
  public key: HIDDEN
  private key: HIDDEN
  listening port: 51820
```

**Additional context**
I've included the Wireguard client's Log upon crash.
[wireguard-log-2021-02-28T163701.txt](https://github.com/complexorganizations/wireguard-manager/files/6056513/wireguard-log-2021-02-28T163701.txt)

**Comment by Prajwal-Koirala** [comment]
hey @teammate165 
1. Can you please post your server logs for wireguard.
2. Do u mean the server is disconnecting the clients or the clients are being disconnected?

I can easily debug this issue, if u want to get this done super fast, send me a email with your server info on `prajwalkoirala23@protonmail.com`

**Comment by teammate165** [comment]
1. How do I access the WG server logs? I've looked around and haven't found a definitive answer, syslog doesn't seem to have anything related to WG. Might be missing something here because I'm not used to using CentOS.

2. The client, only 1 client has this issue apparently. The rest seems to have no issue.

I'm pretty sure I'm running the latest version of kmod-WG from elrepo since I've only set this server up 2 days ago. Running `sudo yum update` shows all packages are up-to-date. And the client's PC is running latest version of WG on Windows is 0.3.7 from Feb 26th 2021.

On another note:
I've tried using another client that supports WG (TunSafe), it doesn't play nice with the config generated by wg-manager script however. Namely it doesn't like multiple DNSs and having 0.0.0.0/5 instead of 0.0.0.0/0 in `AllowedIPs` doesn't allow the client to connect to WG server. Having said that, if I apply those fixes then the client can successfully connect to WG server and random disconnects doesn't seem to happen anymore.

**Comment by Prajwal-Koirala** [comment]
It seems like the issue is with the wireguard peer PC and not the interface, so the best option is to completely remove wireguard from your PC and than delete all the temp files, REBOOT, after that than install wireguard again, and than use the config.

**Comment by teammate165** [comment]
Unfortunately no, my friend said he went ahead and re-installed WG client multiple times but the issue still persists. The 0.3.8 update for WG on Windows which was put out yesterday didn't have any effect as expected after looking through the commits.

Is there anyway I can reach out to the WG developers or a forum of some sort to have them look through this issue?

**Comment by teammate165** [comment]
Yea TunSafe seems to work fine. Thanks for the reponse, I'll reach out to the WG team about this issue.
