### ISSUE TITLE
Publish Docker image to Docker Hub

### ISSUE THREAD

**Issue by gaby** [complexorganizations/wireguard-manager#105]
**Is your feature request related to a problem? Please describe.**
It would be beneficial to publish the Docker image for this project on Docker Hub

**Describe the solution you'd like**
Be able to run `docker pull complexorganizations/wireguard-manager```

**Comment by Prajwal-Koirala** [comment]
Soon.

**Comment by Prajwal-Koirala** [comment]
Hey,
Docker is completed supported and all you have to do to build your own container is to follow the basic instructions.

Also one more thing, during building the container the keys are generated so they will not be published to docker hub.
