### ISSUE TITLE
Unbond does not work with device behind router

### ISSUE THREAD

**Issue by quyleanh** [complexorganizations/wireguard-manager#106]
**Describe the bug**
Unbond does not work with device behind router. So the `curl -4 -s 'https://api.ipengine.dev'` command does not work.

**Expected behavior**
The public IP should be printed out with above command.

**Comment by Prajwal-Koirala** [comment]
this is the first time i have seen something like this, IPengine was a service specifically created to fix this issue.


Can you please do `curl https://api.ipengine.dev` and post the response and than make sure `jq` is installed in the system.

**Comment by quyleanh** [comment]
I have uninstall this script and install the other one.
As I remember, the `curl -4 -s 'https://api.ipengine.dev'` command has no output. After uninstall unbound, this command does work.

**Comment by Prajwal-Koirala** [comment]
i have no idea what u have done, it might have been a problem with unbound and being unable to resolve the hostname and then ur not getting an output.

can u please post some logs.

**Comment by quyleanh** [comment]
I am so sorry. Since I uninstall it I don't have log now.
Could you tell me how to get the system log? Maybe it will be helpful.

**Comment by Prajwal-Koirala** [comment]
just spin up a new VPS or whatever and run the script and post the results.

**Comment by Prajwal-Koirala** [comment]
@quyleanh 

Any update?

I can help you set it up if u would like.

**Comment by quyleanh** [comment]
@Prajwal-Koirala I am sorry. Since I don't have any new VPS, I cannot reprocedure the bug.
In the future, if I have a chance, I will check and let you know.
Thank you for your support. I would like to close this issue.
