### ISSUE TITLE
Possibility to port forward 

### ISSUE THREAD

**Issue by brazzo97** [complexorganizations/wireguard-manager#107]
Hi I am using your script for a lot of time now , i wanted to ask if it was possible  to port forward  all the server port to the wireguard client , if yes can this be added  to the script ? Thanks

**Comment by Prajwal-Koirala** [comment]
Hello,
This isn't possible to do via my script at the current time, i know some cloud providers have a feature where you can request a port forwarding via an API so using that it could be automated, but it's a very small number of hosting providers.
- Prajwal

**Comment by jsloane** [comment]
I think an external/cloud firewall would be out of scope, but you could enable port forwarding in the wireguard server to a specific cllient with iptable rules, something like this:

```
iptables -t nat -D PREROUTING -p tcp -i $INTERNET_INF '!' --dport 22 -j DNAT --to-destination $CLIENT_IPV4
iptables -t nat -D POSTROUTING -o $INTERNET_INF -j SNAT --to-source $ext_internet_ipv4
iptables -t nat -D PREROUTING -p udp -i $INTERNET_INF '!' --dport $WG_SERVER_PORT -j DNAT --to-destination $CLIENT_IPV4
```

**Comment by Prajwal-Koirala** [comment]
Hey,
That's more or less ssh and that's should be left up to the user.

**Comment by jsloane** [comment]
The 3 rules above will forward every port except ssh and the wireguard server port, to the client specified. It could be adjusted to forward specific ports as configured by the user.
This would go in the post up/post down scripts.

**Comment by Prajwal-Koirala** [comment]
> The 3 rules above will forward every port except ssh and the wireguard server port, to the client specified. It could be adjusted to forward specific ports as configured by the user.
> This would go in the post up/post down scripts.

This is a terrible idea, lets say u have a company vpn using this script than all the users will have access to stuff they shouldn't.

**Comment by jsloane** [comment]
Yes, there would be security implications so you'd want an explicit option for this, if it were to be added to the script.

**Comment by Prajwal-Koirala** [comment]
> Yes, there would be security implications so you'd want an explicit option for this, if it were to be added to the script.

Hell NO.

**Comment by Prajwal-Koirala** [comment]
> Yes, there would be security implications so you'd want an explicit option for this, if it were to be added to the script.

HELL NO.
