### ISSUE TITLE
Issues with two subnets in config

### ISSUE THREAD

**Issue by 56kb** [complexorganizations/wireguard-manager#108]
**Describe the bug**
After running the script on ubuntu 20.04 I specified two network subnets 10.0.0.0/8, 192.165.50.0/24. The first peer config was created fine but all other peers created after are missing the 192.168.50.0/24 subnet.

the configs show "AllowedIPs = 10.0.0.0/8,"

**To Reproduce**
run the script and specify two networks and create more peers after install

**Expected behavior**
all configs should show the two subnets

**Comment by 56kb** [comment]
> I'm aware of the problem; a small portion of the script would need to be rewritten, Soon.
> 
> https://github.com/complexorganizations/wireguard-manager/blob/main/wireguard-manager.sh#L1149
> https://github.com/complexorganizations/wireguard-manager/blob/main/wireguard-manager.sh#L1161
> 
> https://github.com/complexorganizations/wireguard-manager/blob/main/wireguard-manager.sh#L328
> https://github.com/complexorganizations/wireguard-manager/blob/main/wireguard-manager.sh#L298

**Comment by Prajwal-Koirala** [comment]
Closed: Duplicate Issue.
https://github.com/complexorganizations/wireguard-manager/issues/94
