### ISSUE TITLE
 num-threads: 1?

### ISSUE THREAD

**Issue by alexlii1971** [complexorganizations/wireguard-manager#111]
Hello,

I have a question with about `num-threads: 1` in /etc/unbound/unbound.conf, but I do not know where should I submit this quesiton:                                                                                      

```

server:
    num-threads: 1
```

What does  `num-threads: 1` mean here please?

Does it mean Wireguard will only accept one peer connection?

Thanks

**Comment by Prajwal-Koirala** [comment]
No, That's the number of treads to give to unbound.

You can just ignore that, its not really that important.
