### ISSUE TITLE
Gui support

### ISSUE THREAD

**Issue by alexlii1971** [complexorganizations/wireguard-manager#113]
After test, I found this is the only one repository that support prevent DNS leak.

**Is your feature request related to a problem? Please describe.**
Yes,  if there is a GUI, it will save lots of time.

**Describe the solution you'd like**
some repositories for refereance:

https://github.com/Place1/wg-access-server
https://github.com/perara/wg-manager
https://github.com/ngoduykhanh/wireguard-ui

**Describe alternatives you've considered**

Alternatively, support these two pure wireguard gu:
https://github.com/EmbarkStudios/wg-ui
https://github.com/vx3r/wg-gen-web

Thanks

**Comment by Prajwal-Koirala** [comment]
Hello,
I like the idea but i don't like the current designs, so if we are going to support this than need to make a new design and than write a flutter app.

**Comment by alexlii1971** [comment]
Great!

Would be great if there is a "To do list" on description of this project, so that others can get involved.

**Comment by Prajwal-Koirala** [comment]
Most of the things that need to be completed are in the issues section.

**Comment by Saugjunkie** [comment]
https://github.com/donaldzou/wireguard-dashboard
