### ISSUE TITLE
Shandowdocks?

### ISSUE THREAD

**Issue by alexlii1971** [complexorganizations/wireguard-manager#116]
Hello,

I am studying the project:

In description of shadowsocks, it show:

"your best option is Shadowsocks if wireguard is blocked"

Would you please let me know what does blocked "mean" here?

What might cause it to be blocked?

Thanks

**Comment by Prajwal-Koirala** [comment]
Hello,
Lets say your in china and the CPC sees your `wg` connection and decides to block it, than use Shadowsocks, otherwise stick with wireguard.

**Comment by alexlii1971** [comment]
Thanks.
I am in China now.

And what about protect DNS leak? Is that helpful to avoid being blocked?

**Comment by Prajwal-Koirala** [comment]
> Thanks.
> I am in China now.
> 
> And what about protect DNS leak? Is that helpful to avoid being blocked?

Yes,
If your using `wireguard-manager` than stick with the default options, you will have DNSSEC and than your own personal DNS server using unbound.

90% of the time, the gov won't go after individual VPN servers and will go after known public servers.

**Comment by alexlii1971** [comment]
wireguard-manager?

I am newbie of WireGuard.

And I am confused by WireGuard and wireguard-manager.

I am just use WireGuard client on windows or Mac, is that you mean wireguard-manager?

**Comment by Prajwal-Koirala** [comment]
No.

DId you deploy your own wireguard server?

**Comment by alexlii1971** [comment]
Yes, I did

**Comment by Prajwal-Koirala** [comment]
Have u ever tried to deploy wireguard without this script?

**Comment by Prajwal-Koirala** [comment]
Just any feedback of what you think of this script is fine.
Could be good or bad, anything you feel like.

**Comment by alexlii1971** [comment]
Yes, I can deploy WireGuard by following official tutorial;

Or deploy by your repository.

**Comment by Prajwal-Koirala** [comment]
which one do you perfer?

**Comment by alexlii1971** [comment]
> Just any feedback of what you think of this script is fine.
> Could be good or bad, anything you feel like.



> which one do you prefer?

yes, I like this one, because it support to prevent DNS leak if it is helpful to avoid being blocked.

the only problem for me is that how to setup a GUI for this repository setup, and I am just trying this one https://github.com/Place1/wg-access-server

Here is what I found:
1# wg-access-server works fine if wireguard is installed by default.
2#But it does not work if I use your repository, and I just suppose it is because of custom setup process in your repository.

question please:

Is it possible to setup wireguard-manager  by matching  wg-access-server?

Thanks

**Comment by alexlii1971** [comment]
BTW,  wg-access-server is actually only a GUI, and it require wireguard to be installed bore  wg-access-server installation, and it only support if wireguard is installed by default.

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/issues/116
