### ISSUE TITLE
AllowedIPs are different

### ISSUE THREAD

**Issue by alexlii1971** [complexorganizations/wireguard-manager#117]
**Describe the bug**

In [peer] of wg0.conf at server end,  AllowedIPs = 10.8.0.3/32, please note it is 32

But new added WireGuard Peer, in [Interface] will show Address = 10.8.0.3/24, and it is 24 now.

is that right please?

Thanks

**Comment by Prajwal-Koirala** [comment]
Hello,
That's correct.
DIfferent subnet for different things.
Everything is fine as long as it's the default settings.

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/pull/118
Done.
