### ISSUE TITLE
Hetzner Support asap ;)

### ISSUE THREAD

**Issue by ardipa** [complexorganizations/wireguard-manager#12]
Hi,

With the great knowledge of you, why don't you support Hetzner Cloud?
Seems a big challenge!

**Comment by Prajwal-Koirala** [comment]
Cause the issue with Hetzner is that sometimes it works and other times it doesn't just literally depends on ur luck.

**Comment by catSIXe** [comment]
Hetzner itself is a problem...

**Comment by Prajwal-Koirala** [comment]
@ardipa 
@catSIXe 
Works now.
