### ISSUE TITLE
Optional to disable Unbound DNS server

### ISSUE THREAD

**Issue by alexlii1971** [complexorganizations/wireguard-manager#120]
In some case, Unbound DNS server will stop, 

![WechatIMG4](https://user-images.githubusercontent.com/15896194/111146886-e828bc00-85c4-11eb-8cc6-030d1c140d83.jpeg)

and it will show missing dependencies and broken packages.

![WechatIMG5](https://user-images.githubusercontent.com/15896194/111147026-0b536b80-85c5-11eb-8978-d79a4ad6712d.jpeg)

so, it would be great if there is an option to disable Unbound DNS server ?

**Comment by Prajwal-Koirala** [comment]
Hey,
When installing you can choose between pihole, unbound, custom dns servers.
- Prajwal

**Comment by alexlii1971** [comment]
> I might be able to help you

Yes, I just wanted to completely remove dockers and data, and run the following command:

```
sudo apt-get purge docker-engine
sudo apt-get autoremove --purge docker-engine
rm -rf /var/lib/docker

```


all of Package Dependency lost, I tried a lot to fix the issue, but it seems very difficult to fixed.

Any suggestion please?

**Comment by Prajwal-Koirala** [comment]
Can u please provide more details.
