### ISSUE TITLE
Option for not using IPv6

### ISSUE THREAD

**Issue by Fastidious** [complexorganizations/wireguard-manager#125]
I don’t use, nor care, about IPv6. I would say, most of us using WireGuard aren’t using IPv6. Would it be possible to have an option not to use it at all?

**Comment by Fastidious** [comment]
Regarding to this, there is something in here that isn’t right:

```
  function disable-ipvx() {
    if [ -f "${WIREGUARD_INTERFACE}" ]; then
      echo "Do you want to disable IPv4 or IPv6 on the server?"
      echo "  1) No (Recommended)"
      echo "  2) Disable IPV4"
      echo "  3) Disable IPV6"
      until [[ "${DISABLE_HOST_SETTINGS}" =~ ^[1-3]$ ]]; do
        read -rp "Disable Host Choice [1-3]: " -e -i 1 DISABLE_HOST_SETTINGS
      done
      case ${DISABLE_HOST_SETTINGS} in
      1)
        if [ -f "${WIREGUARD_IP_FORWARDING_CONFIG}" ]; then
          rm -f ${WIREGUARD_IP_FORWARDING_CONFIG}
        fi
        if [ ! -f "${WIREGUARD_IP_FORWARDING_CONFIG}" ]; then
          echo "net.ipv4.ip_forward=1" >>${WIREGUARD_IP_FORWARDING_CONFIG}
          echo "net.ipv6.conf.all.forwarding=1" >>${WIREGUARD_IP_FORWARDING_CONFIG}
          sysctl -p ${WIREGUARD_IP_FORWARDING_CONFIG}
        fi
        ;;
      2)
        if [ -f "${WIREGUARD_IP_FORWARDING_CONFIG}" ]; then
          rm -f ${WIREGUARD_IP_FORWARDING_CONFIG}
        fi
        if [ ! -f "${WIREGUARD_IP_FORWARDING_CONFIG}" ]; then
          echo "net.ipv6.conf.all.forwarding=1" >>${WIREGUARD_IP_FORWARDING_CONFIG}
          sysctl -p ${WIREGUARD_IP_FORWARDING_CONFIG}
        fi
        ;;
      3)
        if [ -f "${WIREGUARD_IP_FORWARDING_CONFIG}" ]; then
          rm -f ${WIREGUARD_IP_FORWARDING_CONFIG}
        fi
        if [ ! -f "${WIREGUARD_IP_FORWARDING_CONFIG}" ]; then
          echo "net.ipv4.ip_forward=1" >>${WIREGUARD_IP_FORWARDING_CONFIG}
          sysctl -p ${WIREGUARD_IP_FORWARDING_CONFIG}
        fi
        ;;
      esac
    fi
  }
```

I see that 2 and 3 are swapped. This still doesn’t eliminate IPv6 entries on `iptables` and configuration files created by the script.

**Comment by Prajwal-Koirala** [comment]
Hey,
Please make a PR, let's improve the script together.
Regarding the code it's designed for the future i suppose, where everyone has IPv4 / IPv6 and for most normal users they would prefer to have VPN on both IPv4 and IPv6.
If you don't want to use Ipv6 or want nothing to do with it than go with Option 3 `Disable IPV6` that way it the server will only forward ipv4 and not forward any IPv6 packets.
Regarding cleaning up `wg0`, it was designed that way so users will always have an IPv6 no matter what, and if a server doesn't have a IPv6 right now and will get it in the future that it will be automatically supported.

I kinda understand how you feel but, there is an easy fix `Option 3`, it will only forward ipv4 packets and completely disable ipv6

**Comment by Fastidious** [comment]
Your explanation makes sense. I will send in a PR to fix the little mistake. Thanks!

**Comment by Fastidious** [comment]
PR #128 on queue.

**Comment by Prajwal-Koirala** [comment]
> PR #128 on queue.

Hey,
Let me try to explain it again the options are to disable a specific protocol for example, if you only want to use IPv4 then disable IPv6, and if you only want to use IPv6 then forward IPv4, if you want to use both than forward both.

**Comment by Fastidious** [comment]
@Prajwal-Koirala oooooh! I was so confused. Now I understand. Will cancel PR, and resubmit.
