### ISSUE TITLE
Unable to browse

### ISSUE THREAD

**Issue by hdavy2002** [complexorganizations/wireguard-manager#13]
I followed simple insturctions on a brand new Ubuntu 20 LTS. Firt I choosed the option to install unbound too and second time. I choose Adguard. Both times, I was able to connect from my laptop and phone, but unable to browse. I then edited the config and added 8.8.8.8 and no luck.

**Comment by Prajwal-Koirala** [comment]
is there a firewall?
is there a outside firewall?
is there a DPI?

can u post the response to `wg` on linux
