### ISSUE TITLE
Existing ad-blocking DNS configuration

### ISSUE THREAD

**Issue by PeterRob** [complexorganizations/wireguard-manager#131]
I suggest an option to configure the user's own DNS server address, e.g. I have dnsmasq running on my router and use this for all DNS queries on my internal LAN (ip 192.168.1.1).

Thanks for the script, I found it made it very easy to configure wireguard.

**Comment by Prajwal-Koirala** [comment]
Pull??

**Comment by Prajwal-Koirala** [comment]
Hello,
Star, Sponsors, Fork, Follow is not mandatory but is much appreciated.
- Prajwal

**Comment by Prajwal-Koirala** [comment]
Hey I'll add this today.

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/commit/447810d877643edc4fe6779e43874d94ee8b9e5f
