### ISSUE TITLE
Removing and adding a peer with disrupting existing connections.

### ISSUE THREAD

**Issue by thedunston** [complexorganizations/wireguard-manager#138]
**Is your feature request related to a problem? Please describe.**

### Adding a peer

When a peer is added a service restart is not required because it disrupts every user's connection.  Once the user has been added to the wireguard configuration file: wg0.conf, the command:

<pre> wg addconf wg0 <(wg-quick strip wg0)</pre>

will reload the configuration file and the peer can connect.  I would suggest changing restarts to when a peer is added:

<pre>	wg addconf ${WIREGUARD_PUB_NIC} <(wg-quick strip ${WIREGUARD_PUB_NIC})</pre>

### Removing a Peer

When removing a user, I would suggest using the peer's public key and removing it instead of restarting the Wireguard server because it disrupts everyone's connection until the next KeepAlive occurs.

The syntax below drops the respective user's connection immediately and doesn't require a wireguard service restart. 

<pre>wg set wg0 peer PUBKEY remove</pre>

After line 1291, this will retrieve their public key:

<pre>clientkey=$(sed -n '/\# ${REMOVECLIENT} start/,/\# ${REMOVECLIENT} end/p' ${WIREGUARD_CONFIG} | grep PublicKey | cut -d= -f2)</pre>

and below will drop their connection immediately:

<pre>wg set ${WIREGUARD_PUB_NIC} peer ${clientkey} remove</pre>

The next time Wireguard gets loaded or restarted, the user's client configuration will have been removed with the existing Line 1292: 

The suggested change:

<pre>

 if [[ ${REPLY} =~ ^[Yy]$ ]]; then

    CLIENTKEY=$(sed -n '/\# ${REMOVECLIENT} start/,/\# ${REMOVECLIENT} end/p' ${WIREGUARD_CONFIG} | grep PublicKey | cut -d= -f2)
    wg set ${WIREGUARD_PUB_NIC} peer ${CLIENTKEY} remove
    sed -i "/\# ${REMOVECLclientkeyIENT} start/,/\# ${REMOVECLIENT} end/d" ${WIREGUARD_CONFIG}
    rm -f ${WIREGUARD_CLIENT_PATH}/"${REMOVECLIENT}"-${WIREGUARD_PUB_NIC}.conf
    echo "Client ${REMOVECLIENT} has been removed."

 elif [[ ${REPLY} =~ ^[Nn]$ ]]; then
 
       exit

fi

</pre>

**Comment by Prajwal-Koirala** [comment]
Hello,
Please make a PR.
- Prajwal

**Comment by thedunston** [comment]
This is my first pull request so I hope it came through. :D

**Comment by Prajwal-Koirala** [comment]
> This is my first pull request so I hope it came through. :D

Hey,
I will test the code and then merge it.
Thank you for the commit.
- Prajwal
