### ISSUE TITLE
Not able to get to local network's server via wireguard vpn

### ISSUE THREAD

**Issue by ArgoHA** [complexorganizations/wireguard-manager#138]
I have installed pivpn on raspbian to get access to local server while being away. I installed ios app (connected using qr code), and mac os app (connected using file). I have connected to vpn, and used mobile phone internet connection to get connection (it worked). But if I use another network, I can not get to 192.168..., I am just in other network (192.168.1.1 brings me not to my VPN server's router, nut to router in network where I am connected).

To make it work how I needed I used [this installer](https://github.com/complexorganizations/wireguard-install). I went through installation questions, got qr code, used it for new connection on ios app. Then I tried 192.168.1.1 again, but got the same thing as before. I did not manage to get into my network (where vpn is).

**Desktop (please complete the following information):**
 - OS: mac os Catalina
 - Browser chrome
 - Version 80.0.3987.87

**Smartphone (please complete the following information):**
 - Device:  iPhone10
 - OS: ios 13.3.1
 - Browser chrome 
 - Version 80.0.3987.95

**Comment by Prajwal-Koirala** [comment]
Hello,
Please remove pivpn and just use this and make you do a port forwarding and it should work.

I just tested it via my own setup and it works completely fine.

**Comment by ArgoHA** [comment]
uninstalled pivpn, rebooted pi, tried vpn connection. Same thing. I connect to second network, connect to vpn, go to chrome, open 192.168.1.1 and get to second network's router

**Comment by ArgoHA** [comment]
Did the same thing again. run that script answered questions, created new client, got qr code. Now I can load sites, but when I am on second network I still get second network's router
How can I remove everything to start from scratch?

**Comment by Prajwal-Koirala** [comment]
Download the script and use the uninstall feature.

**Comment by ArgoHA** [comment]
Ok, I run `bash /etc/wireguard/wireguard-server.sh` and chose `Uninstall WireGuard Interface`
Then I downloaded and installed it from scratch. Got new qr code, connected. And now I can not load any web-site while being connected to vpn. And if I am at second network - I get on second network's router

**Comment by Prajwal-Koirala** [comment]
i think the issue is port forwarding.

**Comment by ArgoHA** [comment]
I forwarded it on the router. Did not change anything from last set up. And I could use internet connection earlier. Does not that mean, that it is not a port forwarding issue?

**Comment by ArgoHA** [comment]
Sorry, closed occasionally

**Comment by Prajwal-Koirala** [comment]
> I forwarded it on the router. Did not change anything from last set up. And I could use internet connection earlier. Does not that mean, that it is not a port forwarding issue?

is there any way i can RDP into your setup and check it out?

**Comment by Prajwal-Koirala** [comment]
the problem isnt with this script, the problem is with the setup, something wrong is going on.

**Comment by ArgoHA** [comment]
Let's try one more time step by step.
`sudo wget https://raw.githubusercontent.com/complexorganizations/wireguard-install/master/wireguard-server.sh -P /etc/wireguard/
`
`sudo bash /etc/wireguard/wireguard-server.sh
`

Then I just tap enter over and over again (all settings by default). And I have a static IP address.
I use qr code to connect via ios WireGuard app.
now I have a connection. But when I change network - I can not get to my original network's server. I am just in another network despite VPN is 'on'. 
But if I check my IP address - it changes when I turn on VPN and matches to my original networks internal IP

And what about port forwarding - I just forwarded 51820 to 51820 and my raspberry's local ip address

Can we use team viewer or smth?

**Comment by ArgoHA** [comment]
<img width="509" alt="Снимок экрана 2020-02-13 в 22 35 00" src="https://user-images.githubusercontent.com/43640256/74471349-211dcb00-4eb1-11ea-91bb-b8c6425b1629.png">

**Comment by Prajwal-Koirala** [comment]
Protocol: UDP

**Comment by ArgoHA** [comment]
Ok, Now it is UDP only. Rebooted router, but that did not help

**Comment by Prajwal-Koirala** [comment]
do u have any modem in the house??

Client > Router > Modem > ISP > Internet

**Comment by Prajwal-Koirala** [comment]
also do u have a static ip on the device wireguard server is on???

**Comment by ArgoHA** [comment]
sorry, what do you mean by modem? I have to routers from different ISPs at home
Device is on lan, so ip address should not change, but I will make it static right now

**Comment by ArgoHA** [comment]
That did not help

**Comment by ArgoHA** [comment]
hm. I tried that script on another pi and that did not work. I deleted, now trying that again and here is what I get:

```
pi@raspberrypi:~ $ sudo bash /etc/wireguard/wireguard-server.sh
bash: /etc/wireguard/wireguard-server.sh: No such file or directory
pi@raspberrypi:~ $ sudo wget https://raw.githubusercontent.com/complexorganizations/wireguard-install/master/wireguard-server.sh -P /etc/wireguard/
--2020-02-14 09:32:22--  https://raw.githubusercontent.com/complexorganizations/wireguard-install/master/wireguard-server.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘raw.githubusercontent.com’
pi@raspberrypi:~ $ 
```
So I even can not download the script...

**Comment by ArgoHA** [comment]
Ok, I just reinstalled raspbian Buster with desktop on pi, and installed the script. All settings by default. Connected via new qr code. Got the same thing. I can access via LTE, but if I am in another network and go to 192.168.1.18 - I do not get to my server. I am just in another network.

**Comment by Prajwal-Koirala** [comment]
2x reasons.
1. DPI
2. UDP blocking.
3. Firewall
4. Router settings

**Comment by Prajwal-Koirala** [comment]
If you can connect via your data but can't connect via another router than the other router is the issue

**Comment by ArgoHA** [comment]
Sorry, I dont feel you understood me correctly.
I can connect to mu router and server via LTE. 192.168.1.1 - router settings. 192.168.1.18/nextcloud - my server.
But if I am on wi fi, no matter which, if I try to go to 192.168.1.1 I get not to my router, where vpn server is, but to router, where I physically am. If I go to 192.168.1.18/nextcloud - I do not get anywhere, because I am not in my home network.
There should not be any firewall issues, because I can get to my server when I am on mobile phone LTE (4g). Are you sure, that I should by default get to my home server (192.168.1.18) when I am outside my network in another network (with VPN turned on, of course)?

**Comment by Prajwal-Koirala** [comment]
the server Private IPv4 is ```10.8.0.1/24``` and client is ```10.8.0.3``` so chances are theses might be on the other router.

**Comment by ArgoHA** [comment]
What does that mean? Should I try 10.8.0.1 instead of 192.168.1.1? Or what?

**Comment by ArgoHA** [comment]
Should not it be configured? I researched a little bit and for example wireguard add-on for home assistant requires to choose 10.10.10.1 if local network is smth like 192.168.1.1
How should it be done with this script?

**Comment by Prajwal-Koirala** [comment]
Need to make some changes and make that optional too

**Comment by Prajwal-Koirala** [comment]
@ArgoHA
Were you able to fix this?

**Comment by ArgoHA** [comment]
Nope, same thing

**Comment by Prajwal-Koirala** [comment]
hey do u have discord or something??

**Comment by ArgoHA** [comment]
I do have a discord.
argo#1207
argo.47@mail.ru

**Comment by Prajwal-Koirala** [comment]
add me on discord `Prajwal#7477`
