### ISSUE TITLE
lost all my /etc/wireguard content!

### ISSUE THREAD

**Issue by francescor** [complexorganizations/wireguard-manager#144]
fedora 33: I've just tried to install and I lost all the content of my  /etc/wireguard 

installation script should 
* ask before doing it, or create a backup
* ask confirmation before updating o.s.

**Comment by francescor** [comment]
pretty annoying: I've lost all my client's vpn configuration files, including my wg private key (!)

my fault, next time a line by line check of the script: I saw a check before `rm` so I was a bit relaxed, but still `/etc/wireguard` have been gone

**Comment by Prajwal-Koirala** [comment]
Hey,
That's there for a reason most people who are coming from different scripts or manual config usually have something broken and they don't realize it, so this way it will remove old config and let u generate the new configs within one minute.
- Prajwal

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/pull/145

**Comment by Prajwal-Koirala** [comment]
Hello,
https://github.com/complexorganizations/wireguard-manager/pull/149
Thank you for taking the time to contribute.
- Prajwal

**Comment by Prajwal-Koirala** [comment]
Hello there,
It will make a copy of the old files and save it in the future before removing them.
Sorry for the inconvenience.
