### ISSUE TITLE
unbound + ads list

### ISSUE THREAD

**Issue by lodgnewt** [complexorganizations/wireguard-manager#148]
I want to add StevenBlack's https://github.com/StevenBlack/hosts ad list to unbound but it didn't work

`$ wget https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/social/hosts`

transform list for unbound format
`$ cat hosts | grep '^0\.0\.0\.0' | awk '{print "local-zone: \""$2"\" redirect\nlocal-data: \""$2" A 0.0.0.0\""}' > /etc/unbound/unbound.conf.d/ads.conf`

add to /etc/unbound/unbound.conf line 
`include: /etc/unbound/unbound.conf.d/ads.conf`

`unbound-control -c /etc/unbound/unbound.conf reload`

and get error
```
/etc/unbound/unbound.conf.d/ads.conf:1: error: syntax error
read /etc/unbound/unbound.conf failed: 1 errors in configuration file
[1620719330] unbound-control[2807:0] fatal error: could not read config file
```

Can anyone use blocklist in wireguard manager setup?

**Comment by Prajwal-Koirala** [comment]
Hey,
Instead of trying to build your own list with unbound; try pi-hole.
When the script is asking you `"Which DNS provider would you like to use?"` click on option 2 (Pi-hole)

If you don't want to use pi-hole and sill want to use this than let me know and ill provide the steps for it.
- Prajwal

**Comment by Fastidious** [comment]
Give this a try:

```
$ cat hosts | grep '^0\.0\.0\.0' | awk '{print "local-zone: \""$2"\" redirect\nlocal-data: \""$2" IN A 0.0.0.0\""}' > /etc/unbound/unbound.conf.d/ads.conf
```

**Comment by Prajwal-Koirala** [comment]
Hey,
Please run these commands.

```
curl https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/social/hosts -o /tmp/hosts
echo "include: \"/etc/unbound/unbound.conf.d/*.conf\"" >> /etc/unbound/unbound.conf
cat /tmp/hosts | grep '^0\.0\.0\.0' | awk '{print "local-zone: \""$2"\" redirect\nlocal-data: \""$2" IN A 0.0.0.0\""}' > /etc/unbound/unbound.conf.d/ads.conf
rm -f /tmp/hosts
systemctl restart unbound
```

**Comment by lodgnewt** [comment]
@Prajwal-Koirala Thank you! It all worked.
