### ISSUE TITLE
How to enable: WireGuard+Unbound+PiHole ?

### ISSUE THREAD

**Issue by realcs** [complexorganizations/wireguard-manager#150]
Hi there! First of all many thanks for your hard work and several improvements!

My question is: It is any posibility to use in the same time Wireguard, Unbound and PiHole ? If yes, can you guide me how to do it ?

Thanks !

**Comment by Prajwal-Koirala** [comment]
Hey,
Currently you can only enable either unbound or pihole, u can't use both of them at the same time.
Prajwal

**Comment by realcs** [comment]
Whats the reason ? In the near future we will be able to use both in same time ?

**Comment by Prajwal-Koirala** [comment]
I have a question, why would you want to do that?

**Comment by Prajwal-Koirala** [comment]
Also, Please make a PR.

**Comment by realcs** [comment]
Maybe because I dont trust Cloudflare or Google. Why is so bad to use this combination of wg,unbound,pihole ?

**Comment by Prajwal-Koirala** [comment]
So u want to block ads with unbound?

**Comment by realcs** [comment]
I want to block ads with pihole but not to use Google DNS or Cloudflare.

**Comment by Prajwal-Koirala** [comment]
Yes I am building something like that, will be production ready soon

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/unbound-manager

**Comment by realcs** [comment]
Thank you !

**Comment by Saugjunkie** [comment]
thank you to make this possible.

I have a question, you merge this in the next time into this projekt or not? 
What is about the installation first install the DNS Server and than wireguard on the same machine?

**Comment by Prajwal-Koirala** [comment]
Hey,
I will replace pihole with that.
- prajwal

**Comment by Saugjunkie** [comment]
Okay for me is unbound my own DNS Server and pihole stopt Ads.
You make unbound for own DNS Server and he stopt Ads? So we don't more use pi hole it is right?

**Comment by Prajwal-Koirala** [comment]
Yes

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/pull/154

**Comment by Prajwal-Koirala** [comment]
Note: Please go to that repo and submit a PR if you want to assist out with unbound management.
