### ISSUE TITLE
Command does not work again

### ISSUE THREAD

**Issue by alexlii1971** [complexorganizations/wireguard-manager#151]
**Describe the bug**

This command does not work again
curl https://raw.githubusercontent.com/complexorganizations/wireguard-manager/main/wireguard-manager.sh --create-dirs -o /usr/local/bin/wireguard-manager.sh

It works well before.

When I tried to reinstall it, and it only return as following:
```
root@AMS-VPN:~# curl https://raw.githubusercontent.com/complexorganizations/wireguard-manager/main/wireguard-manager.sh --create-dirs -o /usr/local/bin/wireguard-manager.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--   100 61833  100 61833    0     0  1372k      0 --:--:-- --:--:-- --:--:-- 1372k
```

**To Reproduce**
Just have a try

**Expected behavior**
works as before

**Screenshots**

https://prnt.sc/13buo68

**Desktop (please complete the following information):**
 - windows
 - I use shell: termius

**Comment by alexlii1971** [comment]
Sorry, I made a mistake, and I should run this command: bash /usr/local/bin/wireguard-manager.sh


and I am in China, seems server was blocked, and the server is Digitalocean Amsterdan.

It works for almost one month before it was blocked.

**Comment by Prajwal-Koirala** [comment]
@alexlii1971
Do you have discord or something?

**Comment by alexlii1971** [comment]
Hi,

discord? I did not catch you up, would you clarify please?

Have a nice day.

**Comment by Prajwal-Koirala** [comment]
> Hi,
> 
> discord? I did not catch you up, would you clarify please?
> 
> Have a nice day.

Are u on any platform where we can talk, i can fix this for u but i need to know what's wrong with the server, other people who use this are fine and you are always facing an issue so.

**Comment by alexlii1971** [comment]
Thanks for care.

I already install it on an new server which located in Amsterdam.

Usually, the new server will work for at least one day, and I am not sure this time, and I will let you know tomorrow.

So, discord is an social app? If yes, it does not work for me although I am using VPN now.

Facebook messenger and whatsup works for me if VPN works.

**Comment by alexlii1971** [comment]
> Thanks for care.
> 
> I already install it on an new server which located in Amsterdam.
> 
> Usually, the new server will work for at least one day, and I am not sure this time, and I will let you know tomorrow.
> 
> So, discord is an social app? If yes, i just did a try and i found it does not work for me although I am using VPN now.
> 
> Facebook messenger and whatsup works for me if VPN works.

Hello,

Well, this time, it does not work again.

I would like to send you SSH password for your check.

Would you please leave me your contact?

Or, please write to me alexlii1971@yahoo.com

**Comment by Prajwal-Koirala** [comment]
Hey,
I will add you on whats app.
prajwal

**Comment by Prajwal-Koirala** [comment]
@alexlii1971 

Can you use this https://github.com/complexorganizations/censorship-scanner and post the results.

**Comment by Prajwal-Koirala** [comment]
> Yes, I can.
> 
> But please let me know how to install it, it seems an Linux based? If yes, do you want me to test on server or local Linux?
> 
> Would you please clarify?
> 
> Actually, I am looking for a way to check whether the network is safe, because the largest local security & antivirus software show an warning that outline is spy software, so I deleted it, please check it at https://guanjia.qq.com
> 
> Thanks.

They are getting paid by china to say that or they are under pressure to say that.

**Comment by Prajwal-Koirala** [comment]
@alexlii1971 
Any updates?

**Comment by alexlii1971** [comment]
Sorry delay, will update before this evening.
