### ISSUE TITLE
Speed limit / Traffi shapping like TC?

### ISSUE THREAD

**Issue by Saugjunkie** [complexorganizations/wireguard-manager#153]
**Is your feature request related to a problem? Please describe.**
No Problem

**Describe the solution you'd like**
Bandwith Limit after 2 TB or more to speed limit to 2 MB pro Client per Month

**Describe alternatives you've considered**

**Additional context**

**Comment by Prajwal-Koirala** [comment]
Can u please make a PR.

**Comment by Saugjunkie** [comment]
I'm so sorry this is a idea, saw this in a another projekt on github [](https://github.com/cmln-vpn/autoscript-vpn[](url)). I ask google an he tell me about TC. A solution i have not sorry

**Comment by Prajwal-Koirala** [comment]
Hey,
All the code in the project is obfuscated, i don't recommend you use that.
- prajwal
