### ISSUE TITLE
Script forces ntp to be installed

### ISSUE THREAD

**Issue by whig0** [complexorganizations/wireguard-manager#155]
**Describe the bug**
The script removes systemd-timesyncd (on Ubuntu 20.04) and installes ntp on first run. Why is this needed?
If ntp is manually removed the script is installing it on the next run again.

**To Reproduce**
1. Run the script first time for installation
2. Replace ntp by chrony or systemd-timesyncd
3. Run the script again. ntp will be reinstalled and chrony will be removed.

**Expected behavior**
Do not change anything time related

**Server:**
 - OS: Ubuntu Server 
 - Version 20.04

**Comment by Prajwal-Koirala** [comment]
Hey,
Because most people who use this script will install it on a server and forget about it, they will never configure their time or other settings, NTP is required on the server. It is meant to have the right time just in case there are any mistakes or other issues.
- prajwal

**Comment by Fastidious** [comment]
@Prajwal-Koirala I would recommend to make `npt` optional (or remove the lines altogether). Every VPS or machine being built these days have time configured at build time.

**Comment by Prajwal-Koirala** [comment]
> @Prajwal-Koirala I would recommend to make `npt` optional (or remove the lines altogether). Every VPS or machine being built these days have time configured at build time.

Needs to do a bit of testing but will prob do this, and force the system time app to update the time.

**Comment by gaby** [comment]
For our use case, we use `systemd-timesyncd` to talk to our NTP server. We can't have the `ntp` package installed cause it breaks `systemd-timesyncd`.

This is on Ubuntu 20.04 LTS

**Comment by Prajwal-Koirala** [comment]
I will remove ntp soon.

**Comment by Prajwal-Koirala** [comment]
Will be replaced with system default options

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/pull/202
