### ISSUE TITLE
Google Adwords link in the google search are blocked

### ISSUE THREAD

**Issue by Saugjunkie** [complexorganizations/wireguard-manager#156]
Hello last Night i have install fresh wireguard manager with unbound an your list.

I would like to search anithing and in the google search the Adword links not working and end in a 404 Error.

I dont no it is right or not? it is would like to restrict the adword links?

I saw the last day you are verry verry hard work and make many many pushed in the unbound manager Thank You for that.

I think a custom error make more sin as a stupid 404 Error. anythink like "we have blocked this Website automaticly, have too much Adds. wen you have a problem with this Contact the Owner at Email adresse and say him while. 

Do you now what i mean? The first time i saw the 404 Error i was confused, the website he block visit it sometimes and then i saw i come frome the adwords link.

**Comment by Prajwal-Koirala** [comment]
Hey, AdWords is an ad, so it's blocked; if you want a specific domain that's been blocked unblocked, file an issue on the unbound manager repo; the list is new, so it may block too many sites for some people's tastes; just give it some time, and I'll smooth it out.

I can redirect to it, but the problem is that it will ping itself, consuming a lot of CPU and memory (I can make it optional)

Also, while pinhole requires roughly 1 GB of RAM and 0.5 GB of disk space, this just need 128MB of RAM and 25 MB of disk space, allowing it to run on nearly any system.

**Comment by Saugjunkie** [comment]
> 
> 
> Hey, AdWords is an ad, so it's blocked; if you want a specific domain that's been blocked unblocked, file an issue on the unbound manager repo; the list is new, so it may block too many sites for some people's tastes; just give it some time, and I'll smooth it out.
> 
I can wait and believe that the system will get even better.
Strictly speaking, Adwords belong to Ads, that is absolutely correct.
This is due to my work, so I don't take Google Adwords as "bad" ads.
> I can redirect to it, but the problem is that it will ping itself, consuming a lot of CPU and memory (I can make it optional)
> 
Unbound makes no difference whether the website is forbidden or not accessible.
We don't need to ping, maybe it is possible to use a comparison with the Unbound list?
That all websites that are forbidden but called get a block notice, all others if they are not reachable just a 404 error?
It's just an idea that I'll share with you, but whether it's technically feasible is up to you.

> Also, while pi-hole requires roughly 1 GB of RAM and 0.5 GB of disk space, this just need 128MB of RAM and 25 MB of disk space, allowing it to run on nearly any system.
Why yout talk about pin-hole? With your solution we don't need a pi-hole. Your unbound solution is great, I like it a lot. Both services wireguard and unbound work very well together. I am enthusiastic, keep going and keep working on it.

You're right, I run it on a 3 Euro KVM server and get the following values ​​at full speed in the download and upload at home and, in parallel, an 8K video via mobile internet on my cell phone.
CPU Usage 4 - 10%
Ram Usage 160-200 MB
Such values ​​can be shared with family and friends.

**Comment by Prajwal-Koirala** [comment]
> > Hey, AdWords is an ad, so it's blocked; if you want a specific domain that's been blocked unblocked, file an issue on the unbound manager repo; the list is new, so it may block too many sites for some people's tastes; just give it some time, and I'll smooth it out.
> 
> I can wait and believe that the system will get even better.
> Strictly speaking, Adwords belong to Ads, that is absolutely correct.
> This is due to my work, so I don't take Google Adwords as "bad" ads.
> 
> > I can redirect to it, but the problem is that it will ping itself, consuming a lot of CPU and memory (I can make it optional)
> 
> Unbound makes no difference whether the website is forbidden or not accessible.
> We don't need to ping, maybe it is possible to use a comparison with the Unbound list?
> That all websites that are forbidden but called get a block notice, all others if they are not reachable just a 404 error?
> It's just an idea that I'll share with you, but whether it's technically feasible is up to you.
> 
> > Also, while pi-hole requires roughly 1 GB of RAM and 0.5 GB of disk space, this just need 128MB of RAM and 25 MB of disk space, allowing it to run on nearly any system.
> > Why yout talk about pin-hole? With your solution we don't need a pi-hole. Your unbound solution is great, I like it a lot. Both services wireguard and unbound work very well together. I am enthusiastic, keep going and keep working on it.
> 
> You're right, I run it on a 3 Euro KVM server and get the following values ​​at full speed in the download and upload at home and, in parallel, an 8K video via mobile internet on my cell phone.
> CPU Usage 4 - 10%
> Ram Usage 160-200 MB
> Such values ​​can be shared with family and friends.

Because web servers such as apache and nginx consume too many system resources, it will instead use a simple golang web server (for more information, see https://github.com/complexorganizations/unbound-manager/pull/35) and then redirect blocked websites to that web server, informing them that they have been blocked.

**Comment by Saugjunkie** [comment]
`<!DOCTYPE html>
<html lang='en' xml:lang='en' xmlns='http://www.w3.org/1999/xhtml'>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='content-type'>
    <meta name="restrict" content="width=device-width">
    <title>Alert Message, website is blocked</title>
<table border="0" width="100%" cellspacing="0" cellpadding="0" bgcolor="#FF0000">
<tbody>
<tr>
<td width="100%">
<table border="0" width="100%" cellspacing="1" cellpadding="0">
<tbody>
<tr>
<td width="100%"><strong>ALERT: ADS Warning</strong></td>
</tr>
<tr>
<td colspan="2" bgcolor="#CDCDCD" width="100%"><center>
<h1><strong><font color=red>Warning: <br />The Website do you want to visit is blocked.</font></strong></h1>
</center><br /><center>
<h3>If you think this is wrong, please contact your Administrator by Email.<br /><br /><a href= "mailto:Saugjunkie@bt-technik.ovh">Send Email</a></h3>

 <p>
          <br>
          <a class='button' href='javascript:history.back()' style='margin-right:30px;'>go back</a>
          <a class='button' href='https://www.google.de/'>Google Suche</a>
        </p>



</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>`

**Comment by Prajwal-Koirala** [comment]
@Saugjunkie 
can you please just post the HTML code only.

**Comment by Saugjunkie** [comment]
yes here is the code 

<!DOCTYPE html>
<html lang='en' xml:lang='en' xmlns='http://www.w3.org/1999/xhtml'>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='content-type'>
    <meta name="restrict" content="width=device-width">
    <title>Alert Message, website is blocked</title>
<table border="0" width="100%" cellspacing="0" cellpadding="0" bgcolor="#FF0000">
<tbody>
<tr>
<td width="100%">
<table border="0" width="100%" cellspacing="1" cellpadding="0">
<tbody>
<tr>
<td width="100%"><strong>ALERT: ADS Warning</strong></td>
</tr>
<tr>
<td colspan="2" bgcolor="#CDCDCD" width="100%"><center>
<h1><strong><font color=red>Warning: <br />The Website do you want to visit is blocked.</font></strong></h1>
</center><br /><center>
<h3>If you think this is wrong, please contact your Administrator by Email.<br /><br /><a href= "mailto:Saugjunkie@bt-technik.ovh">Send Email</a></h3>

 <p>
          <br>
          <a class='button' href='javascript:history.back()' style='margin-right:30px;'>go back</a>
          <a class='button' href='https://www.google.de/'>Google Suche</a>
        </p>



</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>

**Comment by Prajwal-Koirala** [comment]
```
<!DOCTYPE html>
<html lang='en' xml:lang='en' xmlns='http://www.w3.org/1999/xhtml'>
   <head>
      <meta content='text/html; charset=UTF-8' http-equiv='content-type'>
      <meta name="restrict" content="width=device-width">
      <title>Alert Message, website is blocked</title>
      <table border="0" width="100%" cellspacing="0" cellpadding="0" bgcolor="#FF0000">
         <tbody>
            <tr>
               <td width="100%">
                  <table border="0" width="100%" cellspacing="1" cellpadding="0">
                     <tbody>
                        <tr>
                           <td width="100%"><strong>ALERT: ADS Warning</strong></td>
                        </tr>
                        <tr>
                           <td colspan="2" bgcolor="#CDCDCD" width="100%">
                              <center>
                                 <h1><strong><font color=red>Warning: <br />The Website do you want to visit is blocked.</font></strong></h1>
                              </center>
                              <br />
                              <center>
                              <h3>If you think this is wrong, please contact your Administrator by Email.<br /><br /><a href= "mailto:Saugjunkie@bt-technik.ovh">Send Email</a></h3>
                              <p>
                                 <br>
                                 <a class='button' href='javascript:history.back()' style='margin-right:30px;'>go back</a>
                                 <a class='button' href='https://www.google.de/'>Google Suche</a>
                              </p>
                        </tr>
                     </tbody>
                  </table>
               </td>
            </tr>
         </tbody>
      </table>
```

**Comment by Saugjunkie** [comment]
Thank you for correct my mistake. 
When it is time to testing, i will installing on a fresh systems and give feedback it is works

**Comment by Prajwal-Koirala** [comment]
![Screenshot_20210618-133038](https://user-images.githubusercontent.com/16564273/122597512-73d53d00-d039-11eb-8ea0-baed7c242d36.jpg)

It seems to be blocking nearly all of the advertisements I've come across.

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/unbound-manager/issues/45
