### ISSUE TITLE
It is possible to restrict to use another DNS server?

### ISSUE THREAD

**Issue by Saugjunkie** [complexorganizations/wireguard-manager#157]
You work very hard on the DNS server, only I am sitting here wondering how my children can handle it.

If you write another DNS server in the config e.g. cloudfare, then they no longer use my DNS server.

Is it enough to direct port 53 to my server via iptables?
In the end, all data traffic via port 53 should be automatically directed to my server.

If you enter 1.1.1.1 in the wireguard config, you still use my dns server?

Is that enough then, or do I have to redirect the ip 1.1.1.1?

**Comment by Prajwal-Koirala** [comment]
Hey,
They won't be able to use the wireguard app if you lock it with a separate app locker.
Yes, the script will take care of it, and you won't need to use your router to forward port 53.
- prajwal

**Comment by Saugjunkie** [comment]
okay for now i have tested it is and the ip rules on the server are not working correctly?

root@main:~# iptables -L -v -n | more
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
22451 1548K ACCEPT     udp  --  *      *       10.8.0.0/24          0.0.0.0/0            udp dpt:53 ctstate NEW

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
2574K  597M ACCEPT     all  --  wg0    *       0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
root@main:~# iptables -L INPUT -v -n
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
22462 1549K ACCEPT     udp  --  *      *       10.8.0.0/24          0.0.0.0/0            udp dpt:53 ctstate NEW
root@main:~# ip6tables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A INPUT -s fd42:42:42::/64 -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
-A FORWARD -i wg0 -j ACCEPT

in the wireguard conf on the pc replaced the dns with googles 
DNS = 8.8.8.8, 2001:4860:4860::8888 and i see it works with dns server from google and not use the local dns server

i tested it with https://ipleak.net/ and he show me i use 15 dns server all from google. This is what i want, he must use the local DNS server from the server.

**Comment by Prajwal-Koirala** [comment]
Hey,
You don't need to do any further manual configuration because everything you're asking for is currently in the script.
All you have to do now is install wireguard with unbound and utilize the block list.
- prajwal

**Comment by Saugjunkie** [comment]
oha im so sorry that have not see in the last pr, i will instantly to install new thank you

**Comment by Prajwal-Koirala** [comment]
> oha im so sorry that have not see in the last pr, i will instantly to install new thank you

All is OK, and the lists will be automatically updated every 24 hours.

**Comment by Prajwal-Koirala** [comment]
After about 30 days i think i finally managed to make it to work.

https://github.com/complexorganizations/wireguard-manager/pull/171

Will not merge to main until its stable.

**Comment by Prajwal-Koirala** [comment]
@Saugjunkie

Try it now, it will work perfectly.

**Comment by Saugjunkie** [comment]
> 
> 
> @Saugjunkie
> 
> Try it now, it will work perfectly.

Yeah nice thank you, testing and give report.
At this time i use wireguard and unbound manger from 16.06.2021 and have for me the best balance with performance and security.

**Comment by Prajwal-Koirala** [comment]
> At this time i use wireguard and unbound manger from 16.06.2021 and have for me the best balance with performance and security.

Also, enable automatic updates so that it is updated every 24 hours.

**Comment by Saugjunkie** [comment]
no no i dont updating.
I use another server with the same specs on a fresh install than can see what is the dfficult

**Comment by Prajwal-Koirala** [comment]
> no no i dont updating.
> I use another server with the same specs on a fresh install than can see what is the dfficult

Got it, now it should work on any device. I was testing on a high-end VPS and it worked great, so I didn't see the problem until I tried it on an embeed device.

**Comment by Saugjunkie** [comment]
> Got it, now it should work on any device. I was testing on a high-end VPS and it worked great, so I didn't see the problem until I tried it on an embeed device.

You're right, it works very well. I have now tested it extensively, the page loading is very fast and you can no longer see "Page not found".

Page structure (emailn.de) wireguard + unbound manager from June 16, 2021.
totalTime 25841 ms until the website has fully loaded
He tries to load "consent.cockiebot.com" for a long time

Page structure (emailn.de) wireguard + content-blocker from 07/13/2021.
totalTime 2797 ms until the website was fully loaded.

The time invested was worth it and I can only say it again and again, thank you very much for working on it.

**Comment by Prajwal-Koirala** [comment]
> > Got it, now it should work on any device. I was testing on a high-end VPS and it worked great, so I didn't see the problem until I tried it on an embeed device.
> 
> You're right, it works very well. I have now tested it extensively, the page loading is very fast and you can no longer see "Page not found".
> 
> Page structure (emailn.de) wireguard + unbound manager from June 16, 2021.
> totalTime 25841 ms until the website has fully loaded
> He tries to load "consent.cockiebot.com" for a long time
> 
> Page structure (emailn.de) wireguard + content-blocker from 07/13/2021.
> totalTime 2797 ms until the website was fully loaded.
> 
> The time invested was worth it and I can only say it again and again, thank you very much for working on it.

Once coredns is ready and pushed it will be less than 5 ms for dns response time
