### ISSUE TITLE
Make the switch from unbound to coredns.

### ISSUE THREAD

**Issue by Prajwal-Koirala** [complexorganizations/wireguard-manager#158]
Hello,
Therefore the issue is that resolving large quantities of dns or blocking large amounts of unbound hostnames consumes too much resource, so I want to use `coredns`.
```
. {
    bind 127.0.0.1 ::1
    any
    errors
    loop
    cache
    forward . tls://1.1.1.1 tls://1.0.0.1 {
        tls_servername cloudflare-dns.com
        health_check 5s
    }
    minimal
    reload
}
```

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/pull/159

**Comment by Saugjunkie** [comment]
Hello Iam back again :-D

Soo i have testing the core-dns branch, the ram usage looks pretty good in idle. What with the CPU Usage is, i can not say it doesn`t work. 

The first problem is, the wireguard conf file is without DNS settings and cannot import. When i put the old DNS settings that was inside befor i have new install, i can import the conf in Wireguard app.

I can connect to the wireguard server but becomes  only 404 Error.

**Comment by Prajwal-Koirala** [comment]
It's not ready.

**Comment by Prajwal-Koirala** [comment]
> Hello Iam back again :-D
> 
> Soo i have testing the core-dns branch, the ram usage looks pretty good in idle. What with the CPU Usage is, i can not say it doesn`t work.
> 
> The first problem is, the wireguard conf file is without DNS settings and cannot import. When i put the old DNS settings that was inside befor i have new install, i can import the conf in Wireguard app.
> 
> I can connect to the wireguard server but becomes only 404 Error.

https://github.com/complexorganizations/wireguard-manager/wiki/Unbound-block-domains

Follow these directions to block ads and more for now.

**Comment by Prajwal-Koirala** [comment]
Update: Since now we are using the `/8` subnet and the server can have 16m clients on paper, i need to get this to work since unbound cannot handle that kind of traffic.

**Comment by Prajwal-Koirala** [comment]
Done.

**Comment by ss-o** [comment]
CoreDNS is not very useful for VPN, for development, and Kubernetes it's awesome. Considering dnscrypt-proxy in the future?  As I am using it with the current wireguard-manager.sh. Best performance, as well I wrote a script to switch between, DNS via Tor, odoh fully anonymous, Cloudflare Teams Gateway, Fast 1.1.1.1 resolving and Private Local DNSCrypt server resolving to bundle networks. Also, Cloudflare started to make contributions recently. If interested let me know.

**Comment by Prajwal-Koirala** [comment]
@ss-o 
Can you post the code for it and than provide a bit more details.

**Comment by ss-o** [comment]
I need to strip out personal data and wrap it. If you give some details on what you want to achieve (what kind of DNS you want for this project safe/fast/secure or low resources) I would make it faster as code is on multiple servers for testing. Also, we working on the ODOH servers and ODOH relays which are considered the future of DNS by many.  So if you have no opinion I will wrap dnscrypt-proxy + ODOH through Cloudflare + ICloud Private Relay so no parties have complete records of users' queries. It's fast, secure but still in the early stage (often changes may occur), and there is a lack of choices for relays and etc. but very promising project. I'll follow you up soon. Also, I am looking for advice for easy binaries install/swap so users would have more choices. Here is an example: (Still in progress)

It will install the correct binary from GitHub according to your device. So requires fewer from package managers and wider compatibility.

```
# Install <user>/<repo> from GitHub
curl https://get.digitalclouds.one/<user>/<repo>@<release>! | bash

# Run in docker 
docker run -d -p 3000:3000 --restart always ghcr.io/ss-o/i:main
curl http://localhost:3000/<user>/<repo>@<release>! | bash 
```
Example:

`curl https://get.digitalclouds.one/coredns/coredns@v1.8.4 | bash` - will get binary

`curl https://get.digitalclouds.one/coredns/coredns@v1.8.4\!\! | bash` - will install to a path
