### ISSUE TITLE
Nothing is working anymore after a big upgrade

### ISSUE THREAD

**Issue by Pr0mises** [complexorganizations/wireguard-manager#161]
**Is your feature request related to a problem? Please describe.**

I wanted to add a new client after a very long time and thought about "Let's update the script"... 
Received an empty script with 404Empty msg. All fine, you changed the file wireguard-server.sh [old version](https://github.com/complexorganizations/wireguard-manager/tree/61fb780575183109bc361b991c155e955a753e82) to wireguard-manager.sh a long time ago. 

Starting of the problems begin...

Running the new script like the installation README told me, it deleted everything in /etc/wireguard shouldn't this be fixed #144 or did I just can't find the files? (glad I had backups).

After installing the new script and layout, my connection does work, but there's no internet available. Not sure why, I even changed the config to my old one again and used the new layout. 

While using the wireguard-manager.sh: _Show Interface_ and _Check WireGuard Status_ isn't working? It just closes the script.

**Describe the solution you'd like**

Mention a guide how to upgrade from the old setup to the new one. As a lot have been changed over the time. 

Is it rly necessary to have 2 folders where everything is stored in? 
Let the user choose the script folder or just use /etc/wireguard also please give us the option to setup every port not only 1024-65535 as in most public wifi they're blocked most of the time...

**Additional context**

I uninstalled the new version, copied the saved files and run start wireguard interface with the [old script](https://github.com/complexorganizations/wireguard-manager/tree/61fb780575183109bc361b991c155e955a753e82), everything is working again. Would like to use the new version tho.

**Comment by Prajwal-Koirala** [comment]
Hey,
Let me test it, what os are u running it on?

**Comment by Pr0mises** [comment]
I'm using Debian GNU/Linux 9.13 (stretch) 5.7.0-0.bpo.2-amd64

I know my version is outdated. The old version got uninstalled and the new one installed. But it was not possible to connect to the internet with the new version.

In terms of the port I was not able to, it said in range 1024-65535
[`PEER_PORT=$(shuf -i1024-65535 -n1)`](https://github.com/complexorganizations/wireguard-manager/blob/ef8e63536f22b07b65dbccb29807022640d157c1/wireguard-manager.sh#L1114)

It's not like I don't want to use the new version, it just didn't work for me.

**Comment by Prajwal-Koirala** [comment]
> PEER_PORT=$(shuf -i1024-65535 -n1)

This is the local system port, this is not the port that you forward.

**Comment by Prajwal-Koirala** [comment]
Note: It took around 3 minutes to deploy it to 32 VPS, and they were all ready.
There isn't a problem with the script itself; it's just that the config you're using is outdated and incompatible with the new features; you'll need to reinstall everything.

**Comment by Pr0mises** [comment]
> 
> 
> > PEER_PORT=$(shuf -i1024-65535 -n1)
> 
> This is the local system port, this is not the port that you forward.
Correct linked the wrong [line](https://github.com/complexorganizations/wireguard-manager/blob/ef8e63536f22b07b65dbccb29807022640d157c1/wireguard-manager.sh#L479)

It's late for me, gotta sleep now. I'll try it again tomorrow

**Comment by Prajwal-Koirala** [comment]
> > > PEER_PORT=$(shuf -i1024-65535 -n1)
> > 
> > 
> > This is the local system port, this is not the port that you forward.
> 
> Correct linked the wrong [line](https://github.com/complexorganizations/wireguard-manager/blob/ef8e63536f22b07b65dbccb29807022640d157c1/wireguard-manager.sh#L479)
> 
> It's late for me, gotta sleep now. I'll try it again tomorrow

I really did fuck that up, sorry about that, give me 2 mins, i am fixing that issue now.

**Comment by Prajwal-Koirala** [comment]
@Pr0mises 
Any updates?

**Comment by Pr0mises** [comment]
Yes, it works now. 
I had a parse error tho
>How would you like to detect IPv6?
 > 1) Curl (Recommended)
 > 2) IP (Advanced)
  >3) Custom (Advanced)
>IPv6 Choice [1-3]: 1

`parse error: Invalid numeric literal at line 3, column 0`

Just did another uninstall, deleted all files also services and installed with the script again. 
My download speed isn't as good as it was before, but it's working (50mbps instead of 100+) and yes my server has enough power and 1gb up/down

**Comment by Prajwal-Koirala** [comment]
I'm not sure what country you're in, but go up the client config and fiddle with the MTU values, which should be between 1250 and 1500, once you find the sweet spot for you it will get better.

**Comment by Prajwal-Koirala** [comment]
@Pr0mises

Do u still need help with this or am i free to close the issue?

**Comment by Pr0mises** [comment]
Sry, forgot to close the issue, feel free to do so. 

I didn't manage do fix the speed issuey doesn't bother me too much tho. Only using wireguard for public wifis anyway.

**Comment by Prajwal-Koirala** [comment]
> Sry, forgot to close the issue.
> 
> I didn't manage do fix the speed issue doesn't bother me too much tho. Only using wireguard for public wifis anyway.

Hey,
Change your MTU to `1280` and it will be fixed.
