### ISSUE TITLE
Mtu choice bug

### ISSUE THREAD

**Issue by gzfrozen** [complexorganizations/wireguard-manager#164]
**Describe the bug**
What MTU do you want to use?
   1) 1280 (Recommended)
   2) 1420
   3) Custom (Advanced)
MTU choice [1-3]: 3

If you choose 3 here, the script will set the mtu as 3, instead of setting your own value.

**To Reproduce**
During the installing.

**Comment by alpineboi20** [comment]
> 
> 
> **Describe the bug**
> What MTU do you want to use?
> 
>     1. 1280 (Recommended)
> 
>     2. 1420
> 
>     3. Custom (Advanced)
>        MTU choice [1-3]: 3
> 
> 
> If you choose 3 here, the script will set the mtu as 3, instead of setting your own value.
> 
> **To Reproduce**
> During the installing.

Confirmed.

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/commit/1730ab1244df92a32f57e3edc8f338df9e272268

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/commit/bf4bfb8429e73c64eae94c91ff831b6689609db4
