### ISSUE TITLE
What do you think about creating testcases for this in bats framework?

### ISSUE THREAD

**Issue by pratikbalar** [complexorganizations/wireguard-manager#170]
https://github.com/bats-core/bats-core

**Comment by Prajwal-Koirala** [comment]
Open for any PR.

**Comment by pratikbalar** [comment]
Not right now, Just proposing it and figuring out how

**Comment by Prajwal-Koirala** [comment]
All of the necessary checks are contained inside the code itself.

PR are always welcome.
