### ISSUE TITLE
CentOS 7: Unit systemd-resolved.service could not be found.

### ISSUE THREAD

**Issue by alpineboi20** [complexorganizations/wireguard-manager#173]
Hi, I'm getting the error "Redirecting to /bin/systemctl status systemd-resolved.service
Unit systemd-resolved.service could not be found." On a fresh 25gb $5 Vultr instance. 
Let me know if you need any more Info.

**Comment by Prajwal-Koirala** [comment]
no this is part of the script.

**Comment by alpineboi20** [comment]
> 
> 
> no this is part of the script.
> Ill prob make this hidden

Yea, may be a good idea, as using the script to check the status of the interface fails & throws this error every time.

**Comment by Prajwal-Koirala** [comment]
> > no this is part of the script.
> > Ill prob make this hidden
> 
> Yea, may be a good idea, as using the script to check the status of the interface fails & throws this error every time.

https://github.com/complexorganizations/wireguard-manager/commit/b2ad8b045abf223c04b71def7600fe8c41aaed5c

**Comment by Prajwal-Koirala** [comment]
Hello,
Star, Sponsors, Fork, Follow is not mandatory but is much appreciated.
- Prajwal
