### ISSUE TITLE
RE: b2ad8b0

### ISSUE THREAD

**Issue by alpineboi20** [complexorganizations/wireguard-manager#175]
Hi I tried to test b2ad8b0 as requested, but got this before the script executed.

[root@vps ~]# bash /etc/wireguard/wireguard-server.sh
/etc/wireguard/wireguard-server.sh: line 412: syntax error near unexpected token `fi'
/etc/wireguard/wireguard-server.sh: line 412: `    fi'

**Comment by Prajwal-Koirala** [comment]
Try it again, and update the script and see if the error comes again.

If the error comes every time I'll look into it otherwise I won't since there isn't a problem with the code it self, might be a one time thing.

**Comment by alpineboi20** [comment]
Just did same error, script won't even start.

**Comment by alpineboi20** [comment]
From shell check. Looks like its expecting a done after a do.

$ shellcheck myscript

Line 362:
    if [ "$INSTALL_UNBOUND" == "n" ]; then
                                      ^-- SC1009: The mentioned syntax error was in this then clause. 

Line 375:
      until [[ "$CLIENT_DNS_SETTINGS" =~ ^[1-11]$ ]]; do
      ^-- SC1073: Couldn't parse this until loop. Fix to allow more checks.
                                                      ^-- SC1061: Couldn't find 'done' for this 'do'.

Line 412:
    fi
    ^-- SC1062: Expected 'done' matching previously mentioned 'do'.
      ^-- SC1072: Unexpected keyword/token. Fix any mentioned problems and try again.

$

**Comment by ptts** [comment]
Just add a new line saying `done` right before [this line](https://github.com/complexorganizations/wireguard-manager/blob/f05ce571ff5fb2b23b83dd4e5cc51faf1c4d0f11/wireguard-server.sh#L377)

![image](https://user-images.githubusercontent.com/17811564/75367377-806fd800-58c0-11ea-8064-83955a54dcd2.png)

**Comment by alpineboi20** [comment]
> 
> 
> Just add a new line saying `done` right before [this line](https://github.com/complexorganizations/wireguard-manager/blob/f05ce571ff5fb2b23b83dd4e5cc51faf1c4d0f11/wireguard-server.sh#L377)
> 
> ![image](https://user-images.githubusercontent.com/17811564/75367377-806fd800-58c0-11ea-8064-83955a54dcd2.png)
> 
> Edit line in nano:
> `nano +377 /etc/wireguard/wireguard-server.sh`

That did the trick, was able to execute the script and install.  However, checking the interface using option 1 of the script, fails and does nothing. Can anyone else confirm ?

**Comment by alpineboi20** [comment]
Another Problem. When I get to the option "Do You Want To Install Unbound (y/n): y" if I select n/no and try to select any resolver 2-11, it won't accept it & defaults to 1 which is the adguard resolver.

**Comment by Prajwal-Koirala** [comment]
can you guys make a pull.

i added `done`

**Comment by alpineboi20** [comment]
> 
> 
> can you guys make a pull.
> 
> i added `done`

I don't have the knowledge to fix sorry, or I would fix & req a pull.

**Comment by Prajwal-Koirala** [comment]
ill push a major update today.

give me a bit.

**Comment by Prajwal-Koirala** [comment]
> > can you guys make a pull.
> > i added `done`
> 
> I don't have the knowledge to fix sorry, or I would fix & req a pull.

Hey, can you please test this and once we have stop getting errors this will be the final version of the script for now.

https://github.com/complexorganizations/wireguard-manager/blob/Fixed/wireguard-server.sh

**Comment by Prajwal-Koirala** [comment]
@alpineboi20
@ptts

Can you please test out the latest version of the script.

**Comment by alpineboi20** [comment]
> 
> 
> > > can you guys make a pull.
> > > i added `done`
> > 
> > 
> > I don't have the knowledge to fix sorry, or I would fix & req a pull.
> 
> Hey, can you please test this and once we have stop getting errors this will be the final version of the script for now.
> 
> https://github.com/complexorganizations/wireguard-manager/blob/Fixed/wireguard-server.sh

Just tested on CentOS 7 & Ubuntu 18.04 both installed the script, however selecting a custom DNS resolver won't work, only choice 1 = Adguard will work.

I had to add manually "systemctl enable wg-quick@wg0" & "systemctl start wg-quick@wg0"
to enable & start the interface too.

After install if I run the script again to check the interface "Option 1"  it won't show. 
I have to type " wg show wg0" for it to display the status.

This might just be an issue with vultr,  I don't have any other providers to test. Would be interested to know if anyone else is facing these issues.

**Comment by Prajwal-Koirala** [comment]
> > > > can you guys make a pull.
> > > > i added `done`
> > > 
> > > 
> > > I don't have the knowledge to fix sorry, or I would fix & req a pull.
> > 
> > 
> > Hey, can you please test this and once we have stop getting errors this will be the final version of the script for now.
> > https://github.com/complexorganizations/wireguard-manager/blob/Fixed/wireguard-server.sh
> 
> Just tested on CentOS 7 & Ubuntu 18.04 both installed the script, however selecting a custom DNS resolver won't work, only choice 1 = Adguard will work.
> 
> I had to add manually "systemctl enable wg-quick@wg0" & "systemctl start wg-quick@wg0"
> to enable & start the interface too.
> 
> After install if I run the script again to check the interface "Option 1" it won't show.
> I have to type " wg show wg0" for it to display the status.
> 
> This might just be an issue with vultr, I don't have any other providers to test. Would be interested to know if anyone else is facing these issues.

I fixed all of those issues on the latest version of the script. 

Update the script and try again.

**Comment by alpineboi20** [comment]
I just did, let me try once more. I copied from here in raw, is that correct?

**Comment by alpineboi20** [comment]
Going to try again on a fresh instance.

**Comment by Prajwal-Koirala** [comment]
> Going to try again on a fresh instance.

okay.

Fixed the custom DNS too.

https://github.com/complexorganizations/wireguard-manager/commit/89fa92b6601c0bca206a98bd9f48b506a511d692

**Comment by alpineboi20** [comment]
Waiting for kernel module to install, dns worked, will report back in a few mins.

**Comment by alpineboi20** [comment]
Everything works now, thanks. Finally, got there 👍
