### ISSUE TITLE
Separate querie labels?

### ISSUE THREAD

**Issue by ben-dd** [complexorganizations/wireguard-manager#179]
**Is your feature request related to a problem? Please describe.**
`Queries answered by` section shows four separate `one.one.one.one#53` sections

**Describe the solution you'd like**
I assume one of those is unbound, could we change those labels to show their actual service?

![Screen Shot 2021-07-22 at 11 55 07](https://user-images.githubusercontent.com/40916720/126686507-fc9867b3-42a5-4a98-a309-d118b703663a.png)

**Comment by Prajwal-Koirala** [comment]
Can u please explain further.

**Comment by ben-dd** [comment]
Well maybe I just don't understand why there are four different versions of `one.one.one.one#53`...

**Comment by Prajwal-Koirala** [comment]
> Well maybe I just don't understand why there are four different versions of `one.one.one.one#53`...

I believe that's from pihole, it has nothing to do with wireguard manager

**Comment by ben-dd** [comment]
Ok, I apologize. Thank you for the responses and thank you for the Wireguard-Manager project!

**Comment by Prajwal-Koirala** [comment]
> Ok, I apologize. Thank you for the responses and thank you for the Wireguard-Manager project!

Also one more thing if u want complete privacy use unbound or coredns, or the build in dns with wireguard manager, pihole forwards your dns query to cloudflare and we don't.

**Comment by ben-dd** [comment]
When I setup WM, I selected to use unbound. Im really ignorant to all this.

**Comment by Prajwal-Koirala** [comment]
> When I setup WM, I selected to use unbound. Im really ignorant to all this.

There are 2x options, 1. Remove pihole or 2. Complete reinstall.

It's all good.

Also you should just create a new VPS and deploy wireguard manager and just use that

**Comment by ben-dd** [comment]
Ok, thanks for your help.
