### ISSUE TITLE
[Feature] allow the use of domain names

### ISSUE THREAD

**Issue by senden9** [complexorganizations/wireguard-manager#180]
**Is your feature request related to a problem? Please describe.**
Wireguard-manager uses only the IP address of the server for the generated configuration. If the server IP address changes we need to update our client config or update our client config right away to use a domain name.

**Describe the solution you'd like**
Add a flag/question/option to to use a domain name for the server field in the client configuration.

**Describe alternatives you've considered**
Manually edit the configuration on the client.

**Additional context**
Noting relevant. Just thanks for such a simple working solution :D

**Comment by Prajwal-Koirala** [comment]
If we use domain name.
The A or AAAA records needs to be changed everytime.

We can use a 3rd party provider to make this happen

**Comment by Prajwal-Koirala** [comment]
https://www.noip.com/

**Comment by senden9** [comment]
Exactly. I try to clarify what I want to say with an example:

Current:
```ini
# client-name
[Interface]
Address = "..."
DNS = "..."
MTU = "..."
PrivateKey = "..."
[Peer]
AllowedIPs = "..."
Endpoint = 1.2.3.4:51820
PersistentKeepalive = "..."
PresharedKey = "..."
PublicKey = "..."
```

Proposed optional mode:
```ini
# client-name
[Interface]
Address = "..."
DNS = "..."
MTU = "..."
PrivateKey = "..."
[Peer]
AllowedIPs = "..."
Endpoint = vpn.mydomain.name:51820
PersistentKeepalive = "..."
PresharedKey = "..."
PublicKey = "..."
```

The updating of the A / AAAA entries can be done by something else of course.

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/pull/181

**Comment by Prajwal-Koirala** [comment]
Try this service.

https://www.duckdns.org/domains

**Comment by Prajwal-Koirala** [comment]
Hello,
Star, Sponsors, Fork, Follow is not mandatory but is much appreciated.
- Prajwal

**Comment by senden9** [comment]
Thanks!

**Comment by Prajwal-Koirala** [comment]
@senden9
https://github.com/complexorganizations/wireguard-manager/pull/184

Would this be better since this uses hostnames instead of IP or Domains?

please feel free to test and provide feedback.
