### ISSUE TITLE
Uninstall script deletes root user's CRONTAB

### ISSUE THREAD

**Issue by Nwevyn** [complexorganizations/wireguard-manager#180]
**Describe the bug**
When Wireguard is installed via the script multiple lines could be added to the root user's CRON table.  If Wireguard is then uninstalled via the script, the entire root user's CRON table is deleted.  This includes lines pre-existing the original installation. 

**To Reproduce**
1. Use "sudo crontab -e".  Then add a line to the existing table, eg. "7 7 7 7 * echo "hello" > /dev/null 2>$1".  Save and exit CRONTAB.
2.  Use "sudo crontab -l" to view the updated CRON table.
3. Use the script to install Wireguard (options chosen should be irrelevant).
4. Use "sudo crontab -l" to see what, if any, commands were added to the root user's CRON table
5. Use the script to un-install Wireguard.
6. Use "sudo crontab -l".  See the error that all CRON table commands (including the one added in step 1) are missing.

**Expected behavior**
Only the CRON table lines that could have been added by the installation script should be deleted.  Any existing, or subsequently added, lines should still be present after the un-installation.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: n/a

**Smartphone (please complete the following information):**
 - Device: n/a

**Additional context**
Possible solution, I believe, is to replace the existing "crontab -r" command with 'crontab -l | grep -v $(realpath "$0") | crontab -'

**Comment by Prajwal-Koirala** [comment]
Please make a PR, also thank you for reporting the bug.

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/pull/182

**Comment by Prajwal-Koirala** [comment]
Hello,
Thank you for taking the time to contribute.
- Prajwal
