### ISSUE TITLE
Hello, can you add Udp2raw-tunnel support or something similar? thank you

### ISSUE THREAD

**Issue by qnyblog** [complexorganizations/wireguard-manager#181]
Hello, can you add Udp2raw-tunnel support or something similar? thank you
ISP providers in some countries add QoS restriction, if use Udp2raw-tunnel can helps Bypass UDP masking or QoS restrictions

**Comment by Prajwal-Koirala** [comment]
Use outline, its designed to get around isp and government blocking.

**Comment by qnyblog** [comment]
Thank you, have a nice day

**Comment by Prajwal-Koirala** [comment]
> Thank you, have a nice day

We have tried stuff like this before and its a patch work, i still have the docs i wrote a while ago on how to do this, but its just some patch work and its just better if you use outline.

We have tested outline from china and it works perfectly.
