### ISSUE TITLE
execute the script  : bash /usr/local/bin/wireguard-manager.sh .An error occurred

### ISSUE THREAD

**Issue by leiyuxin** [complexorganizations/wireguard-manager#184]
**Describe the bug**
Follow the installation steps
execute the script  : bash /usr/local/bin/wireguard-manager.sh 

**Screenshots**
Ign:11 http://ppa.launchpad.net/wireguard/wireguard/ubuntu xenial/main i386 Packages
Ign:12 http://ppa.launchpad.net/wireguard/wireguard/ubuntu xenial/main all Packages
Ign:13 http://ppa.launchpad.net/wireguard/wireguard/ubuntu xenial/main Translation-en_US
Ign:14 http://ppa.launchpad.net/wireguard/wireguard/ubuntu xenial/main Translation-en
Ign:10 http://ppa.launchpad.net/wireguard/wireguard/ubuntu xenial/main amd64 Packages
Ign:11 http://ppa.launchpad.net/wireguard/wireguard/ubuntu xenial/main i386 Packages
Ign:12 http://ppa.launchpad.net/wireguard/wireguard/ubuntu xenial/main all Packages
Ign:13 http://ppa.launchpad.net/wireguard/wireguard/ubuntu xenial/main Translation-en_US
Ign:14 http://ppa.launchpad.net/wireguard/wireguard/ubuntu xenial/main Translation-en
Err:10 http://ppa.launchpad.net/wireguard/wireguard/ubuntu xenial/main amd64 Packages
  403  Forbidden [IP: 91.189.95.85 80]
Ign:11 http://ppa.launchpad.net/wireguard/wireguard/ubuntu xenial/main i386 Packages
Ign:12 http://ppa.launchpad.net/wireguard/wireguard/ubuntu xenial/main all Packages
Ign:13 http://ppa.launchpad.net/wireguard/wireguard/ubuntu xenial/main Translation-en_US
Ign:14 http://ppa.launchpad.net/wireguard/wireguard/ubuntu xenial/main Translation-en
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://build.openvpn.net/debian/openvpn/stable trusty InRelease: The following signatures were invalid: KEYEXPIRED 1595684909  KEYEXPIRED 1595684909  KEYEXPIRED 1595684909
W: The repository 'http://ppa.launchpad.net/wireguard/wireguard/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Failed to fetch http://build.openvpn.net/debian/openvpn/stable/dists/trusty/InRelease  The following signatures were invalid: KEYEXPIRED 1595684909  KEYEXPIRED 1595684909  KEYEXPIRED 1595684909
E: Failed to fetch http://ppa.launchpad.net/wireguard/wireguard/ubuntu/dists/xenial/main/binary-amd64/Packages  403  Forbidden [IP: 91.189.95.85 80]
_W: Some index files failed to download. They have been ignored, or old ones used instead.
_**/usr/local/bin/wireguard-manager.sh: line 90: bc: command not found
**Error: Kernel 4.14 not supported, please update to 3.1**__**

**Additional context**

root@localhost:/usr/local/bin# hostnamectl
   Static hostname: localhost.localdomain
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 5480c447d4f140d48e1f21a17d19e2e7
           Boot ID: fe42cb33e9854ea2b4b39056208eeacb
    Virtualization: kvm
  Operating System: Ubuntu 16.04.7 LTS
            Kernel: Linux 4.14.129-bbrplus
      Architecture: x86-64

**Comment by Prajwal-Koirala** [comment]
`apt-get install bc`

**Comment by Prajwal-Koirala** [comment]
Hey @leiyuxin
Any update?
- Prajwal
