### ISSUE TITLE
Hello, does this script has "no Log VPN" feature? thank you

### ISSUE THREAD

**Issue by qnyblog** [complexorganizations/wireguard-manager#185]
Hello, does this script has "no Log VPN" feature? thank you

**Comment by Prajwal-Koirala** [comment]
Hey,

The default is no logging on the vpn side, there are some logs that the script will generate but they are temp and not store on the drive it self.

It's impossible to instal something without logs.

As long as you use the script with default values and don't go too crazy you will be fine.

**Comment by qnyblog** [comment]
Thank you
