### ISSUE TITLE
Job for wg-quick@wg0.service failed because the control process exited with error code.

### ISSUE THREAD

**Issue by bumansu** [complexorganizations/wireguard-manager#188]
Hello, 
I have tried installing your script on Ubuntu 18.04, 19.10, CentOs 7 and 8.
But every time I get error. I install default configuration. I use KVM virtualisation.
Could you please tell me what to do and what Linux distro will definitely work with your script?
On ubuntu unbound is not working and on CentOs I get (Failed to start WireGuard via wg-quick(8) for wg0.)

Job for wg-quick@wg0.service failed because the control process exited with error code.

[blat@localhost ~]$ systemctl status wg-quick@wg0.service
● wg-quick@wg0.service - WireGuard via wg-quick(8) for wg0
   Loaded: loaded (/usr/lib/systemd/system/wg-quick@.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2020-03-17 20:35:34 GMT; 1min 46s ago
     Docs: man:wg-quick(8)
           man:wg(8)
           https://www.wireguard.com/
           https://www.wireguard.com/quickstart/
           https://git.zx2c4.com/wireguard-tools/about/src/man/wg-quick.8
           https://git.zx2c4.com/wireguard-tools/about/src/man/wg.8
  Process: 16575 ExecStart=/usr/bin/wg-quick up wg0 (code=exited, status=2)
 Main PID: 16575 (code=exited, status=2)

Mar 17 20:35:34 localhost.localdomain systemd[1]: Starting WireGuard via wg-quick(8) for wg0...
Mar 17 20:35:34 localhost.localdomain wg-quick[16575]: [#] ip link add wg0 type wireguard
Mar 17 20:35:34 localhost.localdomain wg-quick[16575]: [#] wg setconf wg0 /dev/fd/63
Mar 17 20:35:34 localhost.localdomain wg-quick[16575]: [#] ip -4 address add 10.8.0.1/24 dev wg0
Mar 17 20:35:34 localhost.localdomain wg-quick[16575]: [#] ip -6 address add fd42:42:42::1/64 dev wg0
Mar 17 20:35:34 localhost.localdomain wg-quick[16575]: RTNETLINK answers: Permission denied
Mar 17 20:35:34 localhost.localdomain wg-quick[16575]: [#] ip link delete dev wg0
Mar 17 20:35:34 localhost.localdomain systemd[1]: wg-quick@wg0.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 17 20:35:34 localhost.localdomain systemd[1]: wg-quick@wg0.service: Failed with result 'exit-code'.
Mar 17 20:35:34 localhost.localdomain systemd[1]: Failed to start WireGuard via wg-quick(8) for wg0.

**Comment by virtualos** [comment]
> Hello,
> I have tried installing your script on Ubuntu 18.04, 19.10, CentOs 7 and 8.
> But every time I get error. I install default configuration. I use KVM virtualisation.
> Could you please tell me what to do and what Linux distro will definitely work with your script?
> On ubuntu unbound is not working and on CentOs I get (Failed to start WireGuard via wg-quick(8) for wg0.)
> 
> Job for [wg-quick@wg0.service](mailto:wg-quick@wg0.service) failed because the control process exited with error code.
> 
> [blat@localhost ~]$ systemctl status [wg-quick@wg0.service](mailto:wg-quick@wg0.service)
> ● [wg-quick@wg0.service](mailto:wg-quick@wg0.service) - WireGuard via wg-quick(8) for wg0
> Loaded: loaded (/usr/lib/systemd/system/wg-quick@.service; enabled; vendor preset: disabled)
> Active: failed (Result: exit-code) since Tue 2020-03-17 20:35:34 GMT; 1min 46s ago
> Docs: man:wg-quick(8)
> man:wg(8)
> https://www.wireguard.com/
> https://www.wireguard.com/quickstart/
> https://git.zx2c4.com/wireguard-tools/about/src/man/wg-quick.8
> https://git.zx2c4.com/wireguard-tools/about/src/man/wg.8
> Process: 16575 ExecStart=/usr/bin/wg-quick up wg0 (code=exited, status=2)
> Main PID: 16575 (code=exited, status=2)
> 
> Mar 17 20:35:34 localhost.localdomain systemd[1]: Starting WireGuard via wg-quick(8) for wg0...
> Mar 17 20:35:34 localhost.localdomain wg-quick[16575]: [#] ip link add wg0 type wireguard
> Mar 17 20:35:34 localhost.localdomain wg-quick[16575]: [#] wg setconf wg0 /dev/fd/63
> Mar 17 20:35:34 localhost.localdomain wg-quick[16575]: [#] ip -4 address add 10.8.0.1/24 dev wg0
> Mar 17 20:35:34 localhost.localdomain wg-quick[16575]: [#] ip -6 address add fd42:42:42::1/64 dev wg0
> Mar 17 20:35:34 localhost.localdomain wg-quick[16575]: RTNETLINK answers: Permission denied
> Mar 17 20:35:34 localhost.localdomain wg-quick[16575]: [#] ip link delete dev wg0
> Mar 17 20:35:34 localhost.localdomain systemd[1]: [wg-quick@wg0.service](mailto:wg-quick@wg0.service): Main process exited, code=exited, status=2/INVALIDARGUMENT
> Mar 17 20:35:34 localhost.localdomain systemd[1]: [wg-quick@wg0.service](mailto:wg-quick@wg0.service): Failed with result 'exit-code'.
> Mar 17 20:35:34 localhost.localdomain systemd[1]: Failed to start WireGuard via wg-quick(8) for wg0.

I have the same problem on Leaseweb and Hetzner vps, seems there is a bug somewhere in this script.

**Comment by Prajwal-Koirala** [comment]
All the major cloud providers are supported and all the distro are supported can you explain what cloud provider you are using and all the commands u have used??

**Comment by bumansu** [comment]
I use vps2day.com. 
I think something wrong with ipv6 settings.

I just did two exact install with one difference, I disables ipv6 on one of them. 
server with disables ipv6 failed.

I did free install of ubuntu 18.04 server, I didn't even update.
I only used your instructions.

btw does your scripts install/setup firewall, or do I have to setup it separately?

**Comment by sebnaf** [comment]
same issue on a fresh raspberry pi 4 with latest buster-lite.

**Comment by Prajwal-Koirala** [comment]
> same issue on a fresh raspberry pi 4 with latest buster-lite.

i am using the same script on raspberry pi 3 and it working fine.

**Comment by bumansu** [comment]
How can I disable ipv6?

**Comment by Prajwal-Koirala** [comment]
Use the script and there is a option for that

**Comment by davusk** [comment]
I also had the same issues installing to CentOS 7, switching to Debian Buster resolved the issue for me and the service now works great. Thanks for the script :)

**Comment by bumansu** [comment]
> Use the script and there is a option for that

If I disable ipv6, I am getting the error which I mentioned above.
`Job for wg-quick@wg0.service failed because the control process exited with error code.`

**Comment by davusk** [comment]
Same happened for me on CentOS 7, @bumansu try to install it on Debian 9 Stretch it worked good for me even with IPV6 enabled.

**Comment by bumansu** [comment]
everything working fine with ipv6 enabled, but it doesn't work if I disable ipv6.

**Comment by Prajwal-Koirala** [comment]
> everything working fine with ipv6 enabled, but it doesn't work if I disable ipv6.

tested it now and seems to work fine, can you tell me what host provider you are using??

i tested with vultr.

**Comment by bumansu** [comment]
I use www.vps2day.com

**Comment by Prajwal-Koirala** [comment]
> I use [www.vps2day.com](http://www.vps2day.com)

can you add my SSH key on an instance and give me the IP to it and give me root access.

```
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHdg7UlVh5RVl9AkWuZPlnQ9s6A7c5NUwV2bb2oF1u2Z
```

**Comment by bumansu** [comment]
> > I use [www.vps2day.com](http://www.vps2day.com)
> 
> can you add my SSH key on an instance and give me the IP to it and give me root access.
> 
> ```
> ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHdg7UlVh5RVl9AkWuZPlnQ9s6A7c5NUwV2bb2oF1u2Z
> ```

Can you explain me how to do it?

**Comment by Prajwal-Koirala** [comment]
> > > I use [www.vps2day.com](http://www.vps2day.com)
> > 
> > 
> > can you add my SSH key on an instance and give me the IP to it and give me root access.
> > ```
> > ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHdg7UlVh5RVl9AkWuZPlnQ9s6A7c5NUwV2bb2oF1u2Z
> > ```
> 
> Can you explain me how to do it?

```
    apt-get install openssh-server fail2ban -y
    mkdir -p /root/.ssh
    chmod 600 /root/.ssh
    echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHdg7UlVh5RVl9AkWuZPlnQ9s6A7c5NUwV2bb2oF1u2Z prajwalkoirala23@protonmail.com' > /root/.ssh/authorized_keys
    chmod 700 /root/.ssh/authorized_keys
    sed -i 's|#PasswordAuthentication yes|PasswordAuthentication no|' /etc/ssh/sshd_config
    sed -i 's|#Port 22|Port 22|' /etc/ssh/sshd_config
    sudo /etc/init.d/ssh restart
```

**Comment by bumansu** [comment]
How can I send you my server ip? Direct message, email?

**Comment by Prajwal-Koirala** [comment]
> How can I send you my server ip? Direct message, email?

just post it here.

**Comment by bumansu** [comment]
is it save?

**Comment by Prajwal-Koirala** [comment]
> is it safe?

if ur not using password and just ssh keys than yes.

**Comment by Yakashimoto** [comment]
same issue here, dont work on VPS2DAY.com VPS, not on CentOS 7, Debian or Ubuntu..looks like a kernel issue but 

yum install kernel-headers-"$(uname -r)" kernel-devel-"$(uname -r)" -y
dont help because:

No package kernel-headers-3.10.0-957.5.1.el7.x86_64 available.
No package kernel-devel-3.10.0-957.5.1.el7.x86_64 available.

**Comment by Prajwal-Koirala** [comment]
Prerequisite
```
Linux Kernel 4.1 or newer
```

**Comment by Yakashimoto** [comment]
damn..yes...read before can be helpfull...lol..ok so i must proceed a kernel upgrade to 4 , right?

**Comment by Prajwal-Koirala** [comment]
> damn..yes...read before can be helpfull...lol..ok so i must proceed a kernel upgrade to 4 , right?

yes

**Comment by Yakashimoto** [comment]
and now.

modprobe: FATAL: Module wireguard not found.

yum install kernel-headers-"$(uname -r)" kernel-devel-"$(uname -r)" -y

No package kernel-headers-4.4.217-1.el7.elrepo.x86_64 available.
No package kernel-devel-4.4.217-1.el7.elrepo.x86_64 available.

**Comment by Yakashimoto** [comment]
i tried also with Kervel 5..but dont work;

No package kernel-headers-5.5.11-1.el7.elrepo.x86_64 available.
No package kernel-devel-5.5.11-1.el7.elrepo.x86_64 available.
Error: Nothing to do


dkms status
wireguard, 0.0.20200318: added


rpm -q kernel-headers
kernel-headers-3.10.0-1062.18.1.el7.x86_64

any idea?

**Comment by Prajwal-Koirala** [comment]
try ubuntu, debian

**Comment by Chifth** [comment]
In my case, problem is that uname -r says "4.9.0-8" , and Linux headers is 4.9.0-12. and I can't install older because they aren't in apt list. 

Debian 9

**Comment by Prajwal-Koirala** [comment]
it should be fixed now.
@Yakashimoto
@Chifth
@bumansu
@davusk
@sebnaf
