### ISSUE TITLE
Broken network access. Some domains load, others will not while connected. w/ Debian 10 Hetzner Cloud

### ISSUE THREAD

**Issue by xCykrix** [complexorganizations/wireguard-manager#189]
**Description**
While connected to WireGuard, there is no network connection and near-everything fails to load.

**To Reproduce**
1. Generated Hetzner Cloud CX11 (Falkenstein, fsn1-dc14, Germany)
2. Follow Default Installation Steps on README
    - I also tried opting out of unbound and disabling IPv6, neither offered any fix for the issue.
    - Disabling unbound allowed some websites to load, but others not. GitHub will not load while connected to the VPN with only unbound opt-out enabled, but Google search results will.
   - Notably, I have seen that IPv6 based "What is my IP" work, but not IPv4 lookups. (ip6.me works, ip4.me does not)
3. Connect to the VPN on any device. (I tested both Android and Windows)
4. Attempt to load a website, such as GitHub, and it should timeout.

**Server Debugging**
```
+ super-user-check
+ '[' 0 -ne 0 ']'
+ virt-check
++ systemd-detect-virt
+ '[' kvm == openvz ']'
++ systemd-detect-virt
+ '[' kvm == lxc ']'
+ dist-check
+ '[' -e /etc/os-release ']'
+ source /etc/os-release
++ PRETTY_NAME='Debian GNU/Linux 10 (buster)'
++ NAME='Debian GNU/Linux'
++ VERSION_ID=10
++ VERSION='10 (buster)'
++ VERSION_CODENAME=buster
++ ID=debian
++ HOME_URL=https://www.debian.org/
++ SUPPORT_URL=https://www.debian.org/support
++ BUG_REPORT_URL=https://bugs.debian.org/
+ DISTRO=debian
+ DISTRO_VERSION=10
+ check-system-requirements
++ command -v iptables
+ '[' -x /usr/sbin/iptables ']'
++ command -v curl
+ '[' -x /usr/bin/curl ']'
++ command -v ip
+ '[' -x /usr/sbin/ip ']'
++ command -v shuf
+ '[' -x /usr/bin/shuf ']'
+ usage
+ '[' 0 -ne 0 ']'
+ headless-install
+ '[' '' == y ']'
+ WIREGUARD_PUB_NIC=wg0
+ WG_CONFIG=/etc/wireguard/wg0.conf
+ '[' '!' -f /etc/wireguard/wg0.conf ']'
+ wireguard-next-questions
+ echo 'Looks like Wireguard is already installed.'
+ echo 'What do you want to do?'
+ echo '   1) Show WireGuard Interface'
+ echo '   2) Start WireGuard Interface'
+ echo '   3) Stop WireGuard Interface'
+ echo '   4) Restart WireGuard Interface'
+ echo '   5) Add WireGuard Peer'
+ echo '   6) Remove WireGuard Peer'
+ echo '   7) Uninstall WireGuard Interface'
+ echo '   8) Update this script'
+ echo '   9) Exit'
+ [[ '' =~ ^[1-9]$ ]]
+ read -rp 'Select an Option [1-9]: ' -e -i 1 WIREGUARD_OPTIONS
Select an Option [1-9]: 1
+ [[ 1 =~ ^[1-9]$ ]]
+ case $WIREGUARD_OPTIONS in
+ pgrep systemd-journal
+ wg show
```
```
root@hub-amethyst-live:~# cat /etc/wireguard/wireguard-server.log
Looks like Wireguard is already installed.
What do you want to do?
   1) Show WireGuard Interface
   2) Start WireGuard Interface
   3) Stop WireGuard Interface
   4) Restart WireGuard Interface
   5) Add WireGuard Peer
   6) Remove WireGuard Peer
   7) Uninstall WireGuard Interface
   8) Update this script
   9) Exit
1621
interface: wg0
  public key: GTHQP4m9ljgBOotUG/o/l0gG/egEapUI5uE5eLcGeVI=
  private key: (hidden)
  listening port: 51820

peer: pILcziUMRx7/60J47yAJsB2hX3EaKnNW/LLXswOTZRc=
  preshared key: (hidden)
  endpoint: 73.120.239.236:58223
  allowed ips: 10.8.0.3/32, fd42:42:42::3/128
  latest handshake: 34 seconds ago
  transfer: 925.51 KiB received, 10.09 MiB sent
```

**Expected behavior**
All websites and services should load as expected, but seemingly all services that depend on IPv4 are failing.

**Remote Server:**
 - OS: Debian Hetzner Cloud Deployment
 - Version: Debian 10

**Additional context**
It does really feel as though any IPv4 dependant services are failing. I had it working previously but now I cannot get it to work at all for whatever reason after I tried to update it and ended up rebuilding the server due to cascading issues regarding WireGuard failing and causing a lot of service errors, which was not due to this script but the previous I was using.

**Comment by Prajwal-Koirala** [comment]
There is always an issue with "Hetzner" try a different cloud provider

**Comment by xCykrix** [comment]
While I would've wished for a little more assistance then just use something else... I believe the final issue was having Docker installed before WireGuard. I believe it may have been causing issues with automatic interface detection.

I also had an issue with restarting, but if a "reinstall" option would be possible that may help in the future. If you update your Linux kernel headers, it will refuse to start after a restart.

The fix for that, if you would like it to be documented anywhere, was.
```
sudo apt install linux-headers-4.19.0-8-all-amd64
sudo apt-get install --reinstall wireguard-dkms wireguard-tools wireguard
```
Where the headers match the latest applicable version and proper architecture of course.

**Comment by Prajwal-Koirala** [comment]
> While I would've wished for a little more assistance then just use something else... I believe the final issue was having Docker installed before WireGuard. I believe it may have been causing issues with automatic interface detection.
> 
> I also had an issue with restarting, but if a "reinstall" option would be possible that may help in the future. If you update your Linux kernel headers, it will refuse to start after a restart.
> 
> The fix for that, if you would like it to be documented anywhere, was.
> 
> ```
> sudo apt-get install linux-headers-4.19.0-8-all-amd64
> sudo apt-get install --reinstall wireguard-dkms wireguard-tools wireguard
> ```
> 
> Where the headers match the latest applicable version and proper architecture of course.
> 
> I did a crontab specifically, just with `@reboot` to recover the kernel module on each reboot if an update was executed.

pull?

**Comment by revunix** [comment]
Its working for me with the newest kernel update!

**Comment by warwickchapman** [comment]
I am using Hetzner and I think it is working fine.

**Comment by greekbookhero** [comment]
I have the newest Linux mint (19 Tara) but I have the same problems

**Comment by soundsnick** [comment]
> I have the newest Linux mint (19 Tara) but I have the same problems

My mama always used to tell me "Use OpenVPN, you son of..."

**Comment by revunix** [comment]
> I have the newest Linux mint (19 Tara) but I have the same problems

Try newest Debian 10.

**Comment by greekbookhero** [comment]
> > I have the newest Linux mint (19 Tara) but I have the same problems
> 
> Try newest Debian 10.
funny 
friend helped me solving problem saying just changing dns in conf
