### ISSUE TITLE
No Dual-Stack with Wireguard?

### ISSUE THREAD

**Issue by Gill-Bates** [complexorganizations/wireguard-manager#192]
I am running a VPS (Debian Bullseye) with Dual-Stack IP (IPv4 and IPv6).

When I connect to my iOS device via Wireguard, I notice that I am only browsing with the IPv4 address. Now, I would have expected my iOS devices to be dual-stack capable as well.

**Comment by Prajwal-Koirala** [comment]
Hey,
Dual stack is presently supported by wireguard-manager and wireguard, however because most apps and services only work in IPv4, it is preferable even with IPv6, therefore if you want to force IPv6 and deactivate IPv4 when installing it, you may do so.

**Comment by Prajwal-Koirala** [comment]
Test your IPv6 with this.
https://test-ipv6.com/

**Comment by Prajwal-Koirala** [comment]
@Gill-Bates 
Any updates?
