### ISSUE TITLE
create new client file

### ISSUE THREAD

**Issue by joksik** [complexorganizations/wireguard-manager#201]
hello i use Arch linux i install your script and i see in shell error with bad argument after question:
Do you want to disable IPv4 or IPv6 on the server?
  1) No (Recommended)
  2) Disable IPV4
  3) Disable IPV6

sysctl: ustawianie klucza "net.ipv4.conf.all.rp_filter": Zły argument
sysctl: ustawianie klucza "net.ipv4.conf.all.accept_source_route": Zły argument
sysctl: ustawianie klucza "net.ipv4.conf.all.promote_secondaries": Zły argument

and i think i found little bug.
when i choose disable ipv6 (i have only ipv4 internet) in /etc/wireguard/wg0.conf i also have entries with network address from ip6 and when i want start wg-quick@wg0.service i cannot i have in system logs:
● wg-quick@wg0.service - WireGuard via wg-quick(8) for wg0
     Loaded: loaded (/usr/lib/systemd/system/wg-quick@.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Thu 2020-04-02 04:10:42 CEST; 15s ago
       Docs: man:wg-quick(8)
             man:wg(8)
             https://www.wireguard.com/
             https://www.wireguard.com/quickstart/
             https://git.zx2c4.com/wireguard-tools/about/src/man/wg-quick.8
             https://git.zx2c4.com/wireguard-tools/about/src/man/wg.8
    Process: 48176 ExecStart=/usr/bin/wg-quick up wg0 (code=exited, status=2)
   Main PID: 48176 (code=exited, status=2)

kwi 02 04:10:42 anarchy wg-quick[48176]: [#] ip link add wg0 type wireguard
kwi 02 04:10:42 anarchy wg-quick[48176]: [#] wg setconf wg0 /dev/fd/63
kwi 02 04:10:42 anarchy wg-quick[48176]: [#] ip -4 address add 10.0.0.1/24 dev wg0
kwi 02 04:10:42 anarchy wg-quick[48176]: [#] ip link set mtu 1420 up dev wg0
kwi 02 04:10:42 anarchy wg-quick[48176]: [#] ip -6 route add fd42:42:42::1/128 dev wg0
kwi 02 04:10:42 anarchy wg-quick[48204]: Error: IPv6 is disabled on nexthop device.
kwi 02 04:10:42 anarchy wg-quick[48176]: [#] ip link delete dev wg0
kwi 02 04:10:42 anarchy systemd[1]: wg-quick@wg0.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
kwi 02 04:10:42 anarchy systemd[1]: wg-quick@wg0.service: Failed with result 'exit-code'.
kwi 02 04:10:42 anarchy systemd[1]: Failed to start WireGuard via wg-quick(8) for wg0.

i fix this manual change /etc/wireguard/wg0.conf and delete all entries in AllowedIPs with ipv6 address - after that when i save wg0.conf i can successful start  wg-quick@wg0.service

status after i remove all ipv6 entries:
● wg-quick@wg0.service - WireGuard via wg-quick(8) for wg0
     Loaded: loaded (/usr/lib/systemd/system/wg-quick@.service; enabled; vendor preset: disabled)
     Active: active (exited) since Thu 2020-04-02 04:18:43 CEST; 7s ago
       Docs: man:wg-quick(8)
             man:wg(8)
             https://www.wireguard.com/
             https://www.wireguard.com/quickstart/
             https://git.zx2c4.com/wireguard-tools/about/src/man/wg-quick.8
             https://git.zx2c4.com/wireguard-tools/about/src/man/wg.8
    Process: 48267 ExecStart=/usr/bin/wg-quick up wg0 (code=exited, status=0/SUCCESS)
   Main PID: 48267 (code=exited, status=0/SUCCESS)

kwi 02 04:18:43 anarchy systemd[1]: Starting WireGuard via wg-quick(8) for wg0...
kwi 02 04:18:43 anarchy wg-quick[48267]: [#] ip link add wg0 type wireguard
kwi 02 04:18:43 anarchy wg-quick[48267]: [#] wg setconf wg0 /dev/fd/63
kwi 02 04:18:43 anarchy wg-quick[48267]: [#] ip -4 address add 10.0.0.1/24 dev wg0
kwi 02 04:18:43 anarchy wg-quick[48267]: [#] ip link set mtu 1420 up dev wg0
kwi 02 04:18:43 anarchy wg-quick[48267]: [#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o enp2s0 -j MASQUERADE; iptables -A INPUT>
kwi 02 04:18:43 anarchy systemd[1]: Finished WireGuard via wg-quick(8) for wg

and what strange when i create new config for users even when i disable as i say before in setup ipv6 new entries are added to wg0.conf and wg-quick@.service stop running :/ so i must again edit wg0.conf and clean from ipv6 entries to start wg-quick@.service

it would probably be better that when we choose the option to disable ipv6 such entries will not appear in the config and when generating clients user does not have to correct the configuration file all the time like me ;(

**Comment by Prajwal-Koirala** [comment]
pull?

**Comment by joksik** [comment]
ok it can be pull request for next release. anyway good work

**Comment by Prajwal-Koirala** [comment]
fixed.
https://github.com/complexorganizations/wireguard-manager/commit/9454fed0f54ff608c8c508af3d47b9e2459e4ed4
