### ISSUE TITLE
Error: Kernel version 3.1 please update to 3.1

### ISSUE THREAD

**Issue by propagare** [complexorganizations/wireguard-manager#203]
lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.7.1908 (Core)
Release:        7.7.1908
Codename:       Core

wireguard-tools v1.0.20191226 - https://git.zx2c4.com/wireguard-tools/

debugging:
bash -x /etc/wireguard/wireguard-(server|client).sh >> /etc/wireguard/wireguard-(server|client).log 
==> Syntax error at word `('

**Comment by Prajwal-Koirala** [comment]
```
bash -x /etc/wireguard/wireguard-server.sh >> /etc/wireguard/wireguard-server.log
```

**Comment by propagare** [comment]
[root@xyz ~]# bash -x /etc/wireguard/wireguard-server.sh >> /etc/wireguard/wi                                                                                                                    reguard-server.log

+ super-user-check
+ '[' 0 -ne 0 ']'
+ virt-check
++ systemd-detect-virt
+ '[' kvm == openvz ']'
++ systemd-detect-virt
+ '[' kvm == lxc ']'
+ '[' -f /.dockerenv ']'
+ check-system-requirements
++ command -v iptables
+ '[' -x /sbin/iptables ']'
++ command -v curl
+ '[' -x /bin/curl ']'
++ command -v ip
+ '[' -x /sbin/ip ']'
++ command -v shuf
+ '[' -x /bin/shuf ']'
++ command -v bc
+ '[' -x /bin/bc ']'
++ command -v uname
+ '[' -x /bin/uname ']'
++ command -v jq
+ '[' -x /bin/jq ']'
++ command -v sed
+ '[' -x /bin/sed ']'
+ kernel-check
+ KERNEL_VERSION_LIMIT=3.1
++ uname -r
++ cut -c1-3
+ KERNEL_CURRENT_VERSION=3.1
++ echo '3.1 > 3.1'
++ bc -l
+ ((  0  ))
+ echo 'Error: Kernel version 3.1 please update to 3.1'
Error: Kernel version 3.1 please update to 3.1
+ exit

**Comment by NotYourGuy** [comment]
I've managed to install the wireguard server with a simple typo fix seen here: https://github.com/complexorganizations/wireguard-manager/pull/204

**Comment by Prajwal-Koirala** [comment]
:)

**Comment by propagare** [comment]
https://github.com/complexorganizations/wireguard-manager/blob/master/wireguard-client.sh#L68

**Comment by Prajwal-Koirala** [comment]
> https://github.com/complexorganizations/wireguard-manager/blob/master/wireguard-client.sh#L68

fixed
