### ISSUE TITLE
Things wrong

### ISSUE THREAD

**Issue by ShayBox** [complexorganizations/wireguard-manager#21]
So many things wrong
1. The script shouldn't be in /etc, that's not where they go
2. It shouldn't be pre-filling out input fields for me to then erase
3. It shouldn't be uninstalling packages I already had installed, when it also didn't install missing packages it needed.

**Comment by Prajwal-Koirala** [comment]
please make a PR.

**Comment by ShayBox** [comment]
Closing, inactivity.

**Comment by Leopere** [comment]
The easiest fix here is to explain to the end-user that this script is to be executed on a new machine with no other prior configurations.  The script is entirely YMMV and may break configurations in favor of its own configuration.

**Comment by Prajwal-Koirala** [comment]
Pull Request.

**Comment by Prajwal-Koirala** [comment]
@ShayBox
@Leopere

Finally updated a couple of things;
Try now.

**Comment by Prajwal-Koirala** [comment]
- [ ] The script shouldn't be in /etc, that's not where they go
- [ ] It shouldn't be pre-filling out input fields for me to then erase
- [ ] It shouldn't be uninstalling packages I already had installed, when it also didn't install missing packages it needed.

**Comment by Prajwal-Koirala** [comment]
1. Done
2. Done
3. In Progress

Hello,
Star, Sponsors, Fork, Follow is not mandatory but is much appreciated.
- Prajwal

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/pull/50

**Comment by Prajwal-Koirala** [comment]
Hello,
Star, Sponsors, Fork, Follow is not mandatory but is much appreciated.
- Prajwal

**Comment by Prajwal-Koirala** [comment]
1. Done
2. Sorry, I wont change this.
3. Done
