### ISSUE TITLE
Error creating peer

### ISSUE THREAD

**Issue by fpizzichillo** [complexorganizations/wireguard-manager#213]
**Describe the bug**
When creating a new peer, option 5 of the menu, it gives an error when parsing the configuration

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

**Expected behavior**

**Screenshots**

![WhatsApp Image 2021-09-20 at 08 49 25](https://user-images.githubusercontent.com/3205587/133999951-50c829ef-9674-4bc5-82eb-5daf3c019df4.jpeg)

**Comment by Prajwal-Koirala** [comment]
Did u manually edit the config file?

**Comment by fpizzichillo** [comment]
Hi, I didn't manually edit the file.

**Comment by Prajwal-Koirala** [comment]
> Hi, I didn't manually edit the file.

Do u have anydesk?

**Comment by Prajwal-Koirala** [comment]
@fpizzichillo 
Can you please pull the latest version of the script?

**Comment by Prajwal-Koirala** [comment]
@fpizzichillo

Any update?

**Comment by fpizzichillo** [comment]
Hi @Prajwal-Koirala 
I got the latest version, but the problem still exists. :(

**Comment by Prajwal-Koirala** [comment]
> Hi @Prajwal-Koirala
> I got the latest version, but the problem still exists. :(

Can you download anydesk and give me your desk id, i will connect, you can just post it here.

**Comment by MarcosMartinezArg** [comment]
> > Hi @Prajwal-Koirala
> > I got the latest version, but the problem still exists. :(
> 
> Can you download anydesk and give me your desk id, i will connect, you can just post it here.

Hi @Prajwal-Koirala, my name is Marcos and i work with @fpizzichillo.. my anydesk ID is 876 579 983.

Rgds.

**Comment by Prajwal-Koirala** [comment]
> > > Hi @Prajwal-Koirala
> > > I got the latest version, but the problem still exists. :(
> > 
> > 
> > Can you download anydesk and give me your desk id, i will connect, you can just post it here.
> 
> Hi @Prajwal-Koirala, my name is Marcos and i work with @fpizzichillo.. my anydesk ID is 876 579 983.
> 
> Rgds.

Accept it please.

**Comment by Prajwal-Koirala** [comment]
Done.

Note: User was using a very old version of the script and all that was needed was to update it.
