### ISSUE TITLE
Auto Populate Prompt Risk; Bad Idea

### ISSUE THREAD

**Issue by doughnet** [complexorganizations/wireguard-manager#214]
When running wireguard-manager it will automatically populate the selection for 1.  If not paying attention or unaware of this and you hit "5" to add a new peer it is actually "15" that gets entered and all the wireguard peers get purged.  This is a terrible idea.

```
Select an Option [1-15]:1
   1) Show WireGuard
   5) Add WireGuard Peer (client)
   15) Purge WireGuard Peers
```

Luckily I have my wireguard running in a VM and was able to restore within a few minutes but someone else might not be as lucky as I was.

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/pull/209/commits/54191b3e7934c6aeb7d99da526edff3d78935c9f

Fixed.

Will be merged soon.
