### ISSUE TITLE
Updated wireguard-manager errors/breaks adding new client

### ISSUE THREAD

**Issue by doughnet** [complexorganizations/wireguard-manager#215]
OS: Ubuntu 20.04 LTS (KVM)

Adding a new client gets this output:

```
Let's name the WireGuard Peer. Use one word only, no special characters, no spaces.
New client peer: iPhone
Unable to parse IP address: `12.0.0.012'
Configuration parsing error
Unable to parse IP address: `12.0.0.012'
Configuration parsing error
```

Confirmed both the client configuration file & wireguard configuration file are both using 12.0.0.012 for the IP.

**Comment by Prajwal-Koirala** [comment]
What subnet are you using?

**Comment by Prajwal-Koirala** [comment]
How in the world are people having this issue?
When I am doing the testing it works fine. And I can add thousands of peers without a single error.

**Comment by doughnet** [comment]
> What subnet are you using?

This is the Interface data I'm using.

```
[Interface]
Address = 12.0.0.1/24,fd42:42:42::1/64, 10.0.0.0/24
```

**Comment by doughnet** [comment]
> How in the world are people having this issue?
> When I am doing the testing it works fine. And I can add thousands of peers without a single error.

I've been using wireguard-manager for about 4 months now with no problem.  Just today I ran the "update" script and then first attempt adding a peer client the issue happened.

**Comment by Prajwal-Koirala** [comment]
> > How in the world are people having this issue?
> > When I am doing the testing it works fine. And I can add thousands of peers without a single error.
> 
> I've been using wireguard-manager for about 4 months now with no problem. Just today I ran the "update" script and then first attempt adding a peer client the issue happened.

Download anydesk and post your anydesk ID

**Comment by Prajwal-Koirala** [comment]
# Note: For other people the issue will not happen since the user manually added multiple subnet.
```
[Interface]
Address = 12.0.0.1/24,fd42:42:42::1/64, 10.0.0.0/24
```

**Comment by Prajwal-Koirala** [comment]
@doughnet 
Any update?

**Comment by doughnet** [comment]
> @doughnet Any update?

I regret the delay.

Yes that was the cause.  Oddly prior to the update I did it was not doing that even though I had the duplicate subnets.
