### ISSUE TITLE
Endpoint after install

### ISSUE THREAD

**Issue by KolosovVD** [complexorganizations/wireguard-manager#22]
Hello,

After installing on clean Ubuntu 20.04 server endpoint in configuration is null:51820

UPD: Cannot detect IPs via CURL.

**Comment by Prajwal-Koirala** [comment]
can u please update the script and try again.

or if possible please post ur public ipv4 here and i can check the issue.

**Comment by KolosovVD** [comment]
I use latest version (1.0.3). 

`209.182.216.147 `

**Comment by Prajwal-Koirala** [comment]
The IP is fine, can u please use the latest version in the master branch.

I always make sure the latest master branch always works.

**Comment by Prajwal-Koirala** [comment]
```
curl https://raw.githubusercontent.com/complexorganizations/wireguard-manager/master/wireguard-server.sh --create-dirs -o /etc/wireguard/wireguard-server.sh
chmod +x /etc/wireguard/wireguard-server.sh
bash /etc/wireguard/wireguard-server.sh
```

**Comment by KolosovVD** [comment]
> curl https://raw.githubusercontent.com/complexorganizations/wireguard-manager/master/wireguard-server.sh --create-dirs -o /etc/wireguard/wireguard-server.sh
> chmod +x /etc/wireguard/wireguard-server.sh
> bash /etc/wireguard/wireguard-server.sh

Exactly this I used.

**Comment by Prajwal-Koirala** [comment]
impossible it would return a null, since if we don't find any info we don't return anything
not even null.

**Comment by KolosovVD** [comment]
I tried to install it on clean Ubuntu/Debian with latest version and it returns “null”.

**Comment by Prajwal-Koirala** [comment]
```
curl -4 https://api.ipengine.dev
```

Please post the response here, please do it from the same vps

**Comment by KolosovVD** [comment]
Interesting..

`<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>500 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered an error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>`

**Comment by Prajwal-Koirala** [comment]
Found the issue, will be fixed within 72 hours.

**Comment by Prajwal-Koirala** [comment]
Fixed.
