### ISSUE TITLE
resolvconf not in Ubuntu 21.10

### ISSUE THREAD

**Issue by ziogref** [complexorganizations/wireguard-manager#226]
**Describe the bug**
Wireguard fails to start with exit code 127 due to Ubuntu 21.10 not having resolvconf installed
once manually installing resolvconf, wireguard starts as expected and clients can connect.

**To Reproduce**
install fresh copy of Ubuntu 21.10
Download and run wireguard-manager.sh
start wireguard interface

**Additional context**
adding resolvconf as a required package as part of the initial install would fix this

**Comment by Prajwal-Koirala** [comment]
It is apart of unbound installation but I will look into this and push a fix if needed.

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/pull/228

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/runs/4190093059?check_suite_focus=true
