### ISSUE TITLE
I  have got a /48 ipv6 block, I hope to using public routable ipv6 in my vpn and sub level, is it possible? like a v6 broker.

### ISSUE THREAD

**Issue by youxiaojie** [complexorganizations/wireguard-manager#23]
quiestion1:The ipv4 is easy to deal with nat, but I hope to assign public routable ipv6 in my vpn, and sub level clients (pc). is it feasible? using forward instead of nat in ipv6?
```

   +-------+                                +----------+          +--------+
   |       |                                |          |          | 2001:1:2:2:x:x:x:x/64 slaac
   |       |                                |          +----------+        |
   |       |                                |          |          |        |
   |       |                                |          |          +--------+
   |public |                                | openwrt  +
   |server |                              2001:1:2:2::1/64
 2001:1:2::/48                              |  radvd   +
   |       |                                |          |          +--------+
   |       |     wireguard                  |          |          |        |
   |       |                                |          +----------+ 2001:1:2:2:x:x:x:x/64 slaac
   |       +--------------------------------+          |          |        |
   +-------+                                +----------+          +--------+
         2001:1:2:1::1/127            2001:1:2:1::/127
in my view here 2 ipv6 can use fdxx in-site address,am I right?

```

question2: I roam my openwrt to a new place , but the server side's endpoint does not change automatically, why? I did not write down endpoint in server side's configure file.
server side:

```
interface: wghub
  public key: xxxxc=
  private key: (hidden)
  listening port: 41089

peer: xxxxE=
  preshared key: (hidden)
  endpoint: 60.247.127.220:2185 /* this part is autoadded by system when "wg show". not write in conf file and not change when roam*/
  allowed ips: 10.8.3.10/32, 2001:x:x::10/128, 2001:x:x:x:1::/80
  latest handshake: 7 hours, 55 minutes, 27 seconds ago
  transfer: 2.84 MiB received, 6.32 MiB sent

```

here I use /80 because the server has /64 block, and I hope to try dhcpv6 with /80 prefix.

**Comment by Prajwal-Koirala** [comment]
try the script and find out for ur self.

**Comment by youxiaojie** [comment]
ok, got it! in server side, add allowips=2001:1:2::/48, therefore system will adding an item in route table. in openwrt, adding ipv6prefix=2001:1:2:2::/64 in wan settings, open server side and openwrt's ipv6 forward. as before, ip forward and route table.

**Comment by Prajwal-Koirala** [comment]
@youxiaojie

Any update?

**Comment by youxiaojie** [comment]
yes, I got it, I got two ways, which is ok, 
1. devide an upper link eth with /64 to /80 or similar, but need to maunually setup v6
2. if isp gives you an /64 or /48 block,  can deligated to client by radvd or odhcpd.
the key is adding these ipv6 range to allowed ips items in server, and when wg-quick up, the route will be added automaticlly.
the wireguard is transpant.
