### ISSUE TITLE
cant update os

### ISSUE THREAD

**Issue by shyton** [complexorganizations/wireguard-manager#231]
**Describe the bug**
after install wireguard-manager i cant update os

**To Reproduce**
#yum update

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/14165540/141687464-fb9a0946-dc8c-4274-9ec5-d58a10f653b6.png)
**Desktop (please complete the following information):**

 - OS: centos 8

**Comment by Prajwal-Koirala** [comment]
```
cat /etc/resolv.conf
cat /etc/unbound/unbound.conf
cat /var/lib/unbound/root.key
cat /etc/unbound/root.hints
cat /etc/wireguard/wg0.conf
```

Post these things.

Also can you give me access to the server i am not sure what's wrong with it.

**Comment by Prajwal-Koirala** [comment]
Try this.
```
rm -f /var/lib/unbound/root.key
unbound-anchor -a /var/lib/unbound/root.key
service unbound restart
```

**Comment by shyton** [comment]
Failed to restart unbound.service: Unit unbound.service not found.

**Comment by Prajwal-Koirala** [comment]
Can u please give me access to the server.

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/pull/233

**Comment by Prajwal-Koirala** [comment]
@shyton

If you run into the issue where dns is not being resolved, than run this command.
```
sed "s|auto-trust-anchor-file: /var/lib/unbound/root.key|# auto-trust-anchor-file: /var/lib/unbound/root.key|" /etc/unbound/unbound.conf
```
than finally restart unbound.
```
service unbound restart
```
