### ISSUE TITLE
wireguardmanager.sh creates client with bogus IP

### ISSUE THREAD

**Issue by wh33t** [complexorganizations/wireguard-manager#232]
> Select an Option [1-15]:5
> Let's name the WireGuard Peer. Use one word only, no special characters, no spaces.
> New client peer:lindsay
> Unable to parse IP address: `10.0.0.04'
> Configuration parsing error
> Unable to parse IP address: `10.0.0.04'
> Configuration parsing error
> 311
> Removed /etc/systemd/system/multi-user.target.wants/wg-quick@wg0.service.
> Created symlink /etc/systemd/system/multi-user.target.wants/wg-quick@wg0.service → /lib/systemd/system/wg-quick@.service.
> Job for wg-quick@wg0.service failed because the control process exited with error code.
> See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.

The really strange thing is that the first client I created works just fine, it was auto assigned an IP of 10.0.0.3, but the second client gets .04 and the 0 seems to be the issue?

**Comment by Prajwal-Koirala** [comment]
Can you give me access to the server?

I am not sure what wrong with it, I am testing the script and it works fine for me.

**Comment by wh33t** [comment]
> Can you give me access to the server?
> 
> I am not sure what wrong with it, I am testing the script and it works fine for me.

I cannot unfortunately. Is there some config files or something I could send to you though? Really appreciate the response.

**Comment by Prajwal-Koirala** [comment]
Can we do a meeting over Google duo or something?

I want to see what's wrong with the script.

**Comment by wh33t** [comment]
I may be able to copy the VM out of our network, then give you access to it. I shall report back.

**Comment by Prajwal-Koirala** [comment]
Some guy had the same issue and all I did was `rm -rf /etc/wireguard` and than did a reinstall and everything worked fine.

**Comment by Prajwal-Koirala** [comment]
> I may be able to copy the VM out of our network, then give you access to it. I shall report back. 

Manually remove the invalid IP and than update the wireguard manager and than add a new client, this will work.

**Comment by wh33t** [comment]
> > I may be able to copy the VM out of our network, then give you access to it. I shall report back.
> 
> Manually remove the invalid IP and than update the wireguard manager and than add a new client, this will work.

How exactly do I do this?

**Comment by wh33t** [comment]
I uninstalled everything, and the re-installed it all using the default options. Seems to work now with more than one peer. Thanks so much for the help.

For the record, the only options I changed from defaults during the install previously was to only use ipv4.

**Comment by Prajwal-Koirala** [comment]
> I uninstalled everything, and the re-installed it all using the default options. Seems to work now with more than one peer. Thanks so much for the help.
> 
> For the record, the only options I changed from defaults during the install previously was to only use ipv4.

can you please explain this?
```
I changed from defaults during the install previously was to only use ipv4.
```

**Comment by wh33t** [comment]
Sure thing. During the setup wizard where the script gives you options to decide various configurations, one of them was to go IPv4 only. That's how I initially had it set up. The second time around I literally just hit <enter> <enter> <enter> on all of the defaults. I think the first time I set it up I also chose not to install Unbound.

**Comment by Prajwal-Koirala** [comment]
> Sure thing. During the setup wizard where the script gives you options to decide various configurations, one of them was to go IPv4 only. That's how I initially had it set up. The second time around I literally just hit enter enter enter on all of the defaults. I think the first time I set it up I also chose not to install Unbound.

This isn't the issue, the issue is that you were using an older version of the script that has bugs on it.

**Comment by wh33t** [comment]
Good to know! Thanks for your help.

**Comment by WMP** [comment]
I have this same, and i found where is problem:
```
  # Private Subnet Ipv4
  PRIVATE_SUBNET_V4=${PRIVATE_SUBNET_V4:-"${IPV4_SUBNET}"}
  # Private Subnet Mask IPv4
  PRIVATE_SUBNET_MASK_V4=$(echo "${PRIVATE_SUBNET_V4}" | cut -d "/" -f 2)
  # IPv4 Getaway
  GATEWAY_ADDRESS_V4="${PRIVATE_SUBNET_V4::-3}1"
```

If you use mask /8 all works, becaouse your script remove last 3 charts from PRIVATE_SUBNET_V4, ex.:

```
root@vpn-client:~# PRIVATE_SUBNET_V4="192.168.124.0/8"
root@vpn-client:~# GATEWAY_ADDRESS_V4="${PRIVATE_SUBNET_V4::-3}"
root@vpn-client:~# echo $GATEWAY_ADDRESS_V4
192.168.124.
root@vpn-client:~# GATEWAY_ADDRESS_V4="${PRIVATE_SUBNET_V4::-3}1"
root@vpn-client:~# echo $GATEWAY_ADDRESS_V4
192.168.124.1
root@vpn-client:~#
```

If you have mask /24, you must remove 4 charsets:
```
root@vpn-client:~# PRIVATE_SUBNET_V4="192.168.124.0/24"
root@vpn-client:~# GATEWAY_ADDRESS_V4="${PRIVATE_SUBNET_V4::-3}"
root@vpn-client:~# echo $GATEWAY_ADDRESS_V4
192.168.124.0
root@vpn-client:~# GATEWAY_ADDRESS_V4="${PRIVATE_SUBNET_V4::-3}1"
root@vpn-client:~# echo $GATEWAY_ADDRESS_V4
192.168.124.01
root@vpn-client:~# GATEWAY_ADDRESS_V4="${PRIVATE_SUBNET_V4::-4}1"
root@vpn-client:~# echo $GATEWAY_ADDRESS_V4
192.168.124.1
root@vpn-client:~#

```

What is best method to fix this?
```
root@vpn-client:~# PRIVATE_SUBNET_V4="192.168.124.0/24"
root@vpn-client:~# GATEWAY_ADDRESS_V4=$(echo $PRIVATE_SUBNET_V4 | cut -d'.' -f1-3).1; echo $GATEWAY_ADDRESS_V4
192.168.124.1
root@vpn-client:~# PRIVATE_SUBNET_V4="192.168.124.0/8"
root@vpn-client:~# GATEWAY_ADDRESS_V4=$(echo $PRIVATE_SUBNET_V4 | cut -d'.' -f1-3).1; echo $GATEWAY_ADDRESS_V4
192.168.124.1
root@vpn-client:~# PRIVATE_SUBNET_V4="10.0.0.0/8"
root@vpn-client:~# GATEWAY_ADDRESS_V4=$(echo $PRIVATE_SUBNET_V4 | cut -d'.' -f1-3).1; echo $GATEWAY_ADDRESS_V4
10.0.0.1
root@vpn-client:~#
```

**Comment by WMP** [comment]
And this same in 927 line:
```
 CLIENT_ADDRESS_V4="${PRIVATE_SUBNET_V4::-3}3"
```

**Comment by Prajwal-Koirala** [comment]
@WMP
Can you please make a PR about this?

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/pull/242

**Comment by Prajwal-Koirala** [comment]
Fixed.

**Comment by Prajwal-Koirala** [comment]
### Note: Just need the code when adding new client too.

**Comment by Prajwal-Koirala** [comment]
Done.
