### ISSUE TITLE
Error Message: qemu virtualization is not supported (yet).

### ISSUE THREAD

**Issue by ziogref** [complexorganizations/wireguard-manager#236]
Updated Virtual Server from Ubuntu 21.04 to 21.10 and this no longer works. When running the script I get 

`qemu virtualization is not supported (yet).`

Which is odd as I have been using it on my qemu server for 2 years.

**Comment by Prajwal-Koirala** [comment]
I will update this later today, just wait for an update.

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/commit/4dc016a4ba3f3ec8d663b9fe708615bba78d11bc
