### ISSUE TITLE
Add peer name to peer display list

### ISSUE THREAD

**Issue by darkworks** [complexorganizations/wireguard-manager#237]
**Is your feature request related to a problem? Please describe.**
when ` bash /usr/local/bin/wireguard-manager.sh ` is executed default option `0` is shown

**Describe the solution you'd like**
will be good if `1` is displayed

**Is your feature request related to a problem? Please describe.**
when first option ` 1) Show WireGuard ` is selected its missing Peer Name

**Describe the solution you'd like**
will be good if Peer Name is also displayed like

```
 Peer Name : User1
  preshared key: (hidden)
  endpoint: xxxxxxxx
  allowed ips: xxxxxxxxxxx
  latest handshake: 2 minutes, 13 seconds ago
  transfer: 1.37 MiB received, 1.59 MiB sent
```

**Is your feature request related to a problem? Please describe.**
when first option ` 1) Show WireGuard ` is selected its missing # of unique connections made from client side

**Describe the solution you'd like**
will be good if # of connections made from clients feature is added incase creds are leaked like that

```
 Peer Name : User1
 # of connections : 1
  preshared key: (hidden)
  endpoint: xxxxxxxx
  allowed ips: xxxxxxxxxxx
  latest handshake: 2 minutes, 13 seconds ago
  transfer: 1.37 MiB received, 1.59 MiB sent
```

**Is your feature request related to a problem? Please describe.**
when fifth option ` 5) Add Peer` is selected it Generate QR Code

**Describe the solution you'd like**
will be good if QR Code png is saved to /etc/wireguard/clients/user1_qr.png  or some other location so that we can share it

thanks for amazing script

**Comment by Prajwal-Koirala** [comment]
Hey,
1 & 2 are controlled by wireguard and there is no way to change that via this script at the current moment and that should be changed in wireguard itself.

For 3 https://github.com/complexorganizations/wireguard-manager/pull/238
