### ISSUE TITLE
Wireguard-manager doesn't work with PiHole anymore

### ISSUE THREAD

**Issue by zigapovhe** [complexorganizations/wireguard-manager#245]
**Describe the bug**
I've been using your wireguard-manager script for years in combination with PiHole. It all worked excellent until I've updated your script to the latest version today. Since I've updated the script, whole PiHole stops working for all clients on my network. PiHole and wireguard-manager are both running on same machine (RPI 3b+ with latest Rasbian OS - based on Debian 11 bullseye). I've even tried formatting SD-card and reinstalling everything but without any luck.

**To Reproduce**
1. Install PiHole
2. Enable unbound
3. Run your script
**Expected behavior**
PiHole will stop working immediately.

**Screenshots**
https://i.imgur.com/jZG3Suy.png

**Desktop (please complete the following information):**
 - OS: Linux raspberrypi 5.10.63-v7+

I've done everything the same, as I did countless number of times before. Same wireguard config, same pihole conf. When I start wireguard service, PiHole stops replying, and shows error "Maximum number of concurrent DNS queries reached (max: 150)". After disabling WireGuard service, PiHole works fine.

**Comment by Prajwal-Koirala** [comment]
Not really a bug more or less a feature,

u don't need an external ad blocker anymore, when the questions are asking hey do u want to block ads and tracker just say yes and than don't change anything.


its already apart of unbound and doesn't need any external software to block ads.

**Comment by zigapovhe** [comment]
I really hope that was not done intentionally. You can't say that's feature. It's clearly breaking something that it shouldn't break. If it worked before, why can't it now? Sure, it's your project,  but it really isn't cool to decide on purpose which scripts can work together and which can not. That's literally becoming a locked ecosystem. Technology is indeed driven by competition, but that's similar to what's apple was(is) doing. They were(are) preventing iOS users to use competitor apps as their main app and they intentionally prevented some competitors to even upload iOS apps to their AppStore.  That was also a feature, not a bug.

Your content-blocker looks really promising. PiHole was (I think) originally developed as DNS-level AD blocker and a lot of domains use subdomains for ther ads. For example `ads.google.com` `adservice.google.com`. You can't just block whole `google.com` domain for that. And If I'm not wrong, with PiHole, you could do exactly what you are saying (add whole domain with enabled 'checkbox' saying `Add domain as wildcard` ([Screenshot](https://i.imgur.com/JLYSNF1.png))). What I'm missing from content-blocker is somewhat similar webapp as PiHole webapp. But, of course, that would probably destroy the beauty of your bash programming.  I admire your work, keep on going with those interesting and helpful bash scripts. For me, it looks like that I will need to find new wireguard-manager, but as your projects grow fast, it would be interesting to see in a year or two, what you created. If there is no plan to fix this, you can freely close this issue. Thanks.

**Comment by Prajwal-Koirala** [comment]
Install pihole,
Choose custom DNS server and than put in your pihole address.

**Comment by zigapovhe** [comment]
I'm sorry, I forgot to mention that. I've done exactly that. I've left everthing at default, except DNS server option. Selected custom dns, and entered private IPv4 address of pihole. And that's where everything goes down. Can you please check that content blocking system is not enabled if user select customd dns?

**Comment by Prajwal-Koirala** [comment]
> I'm sorry, I forgot to mention that. I've done exactly that. I've left everthing at default, except DNS server option. Selected custom dns, and entered private IPv4 address of pihole. And that's where everything goes down. Can you please check that content blocking system is not enabled if user select custom dns?

Can u come on anydesk in 30 mins?

Yes, when custom DNS is enabled, the whole DNS setup is given to the user.

**Comment by zigapovhe** [comment]
I'm happy to help, but unfortunatelly can't tonight (its around midnight in my timezone). Can we do that tomorow around 7PM UTC?

**Comment by Prajwal-Koirala** [comment]
Sure sounds good.

**Comment by zigapovhe** [comment]
Thanks! Just accept me on Twitter so we can dm tomorow.

**Comment by Prajwal-Koirala** [comment]
Hey,

I found your issue and I already have a fix for it.

Wipe your raspberry pi SD card, and reinstall the raspberry pi OS, 64 bit is better than 32 bit.

Install wireguard manager using the normal installation, everything should be the same except for the DNS, when the dns prompts choose Custom DNS and type in `10.0.0.1`.

After installing wireguard using wireguard manager than finally go ahead and install pihole on the `wg0` interface or the interface of your choice, and it will work.

also if u don't want to reinstall than just change the interface of the pihole to the wireguard one. and don't forget to use the address `10.0.0.1`

**Comment by Prajwal-Koirala** [comment]
> Thanks! Just accept me on Twitter so we can dm tomorow.

What's your Twitter?

**Comment by Prajwal-Koirala** [comment]
Done.

Fixed the issue.

Hello,
Star, Sponsors, Fork, Follow is not mandatory but is much appreciated.
- Prajwal
