### ISSUE TITLE
Error: microsoft virtualization is not supported (yet). 

### ISSUE THREAD

**Issue by ferdavs** [complexorganizations/wireguard-manager#248]
**Describe the bug**
Getting error
microsoft virtualization is not supported (yet).

**To Reproduce**
sudo ./wireguard-manager.sh

**Expected behavior**
run as expected

**Additional context**
OS: Linux 5.11.0-1022-azure #23~20.04.1-Ubuntu

**Comment by Prajwal-Koirala** [comment]
can you give me access to your VPS?

**Comment by Prajwal-Koirala** [comment]
Note: microsoft virtualization is on dev channel and still needs more testing.
But if u want to give it a try, than try this.
```
curl https://raw.githubusercontent.com/complexorganizations/wireguard-manager/main/wireguard-manager.sh --create-dirs -o /usr/local/bin/wireguard-manager.sh
sudo sed -i 's/"kvm" | "none" | "qemu"/"kvm" | "none" | "qemu" | "microsoft"/g' /usr/local/bin/wireguard-manager.sh
chmod +x /usr/local/bin/wireguard-manager.sh
bash /usr/local/bin/wireguard-manager.sh
```

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/commit/296cdac87fc805a81493a66b8cc1cf5229fc5960

workaround isnt needed anymore.
