### ISSUE TITLE
Running this from a virtualized lxc container works, suggest to remove limitation from script

### ISSUE THREAD

**Issue by partoneoftwo** [complexorganizations/wireguard-manager#250]
Running this from a virtualized lxc container works, suggest to remove limitation from script

I commented out the function that checks if the program is run from a virtualized environment, as I do not believe there are any reasons it should not work in LXC. Lo and behold it worked just fine and my wireguard server is working perfectly.

Setup:
Hypervisor OS: Proxmox
Container technology: LXC, Linux Containers
Container OS: Debian 11

Custom tweaks: None

Installation steps followed:
Download the script
Comment out the restrictive function from the script which stops virtualized environments from running
Run the script

Result:
Wireguard Server correctly configured
Client config correctly generated
Clients able to connect

Thanks for writing this!

**Comment by Prajwal-Koirala** [comment]
This needs a bit more testing from my side, soon I will test this and push a fix for this.

**Comment by partoneoftwo** [comment]
Sure thing. But you can consider LXC container virtualization as tested and confirmed working. 

Well done and thanks again.

**Comment by Prajwal-Koirala** [comment]
> Sure thing. But you can consider LXC container virtualization as tested and confirmed working.
> 
> Well done and thanks again. This took all the quirks and guesswork out of managing and setting up my wireguard server.

Do u have an extra VPS or something where i can test it, i can find KVM very easily but LXC doesn't seem to be supported.

**Comment by partoneoftwo** [comment]
Hey

I'm running Proxmox on bare metal hardware. But you can install Proxmox on any VPS that supports custom OS images.

**Comment by Prajwal-Koirala** [comment]
I will update this soon, but here is a workaround.
```
curl https://raw.githubusercontent.com/complexorganizations/wireguard-manager/main/wireguard-manager.sh --create-dirs -o /usr/local/bin/wireguard-manager.sh
sudo sed -i 's/"kvm" | "none" | "qemu"/"kvm" | "none" | "qemu" | "lxc"/g' /usr/local/bin/wireguard-manager.sh
chmod +x /usr/local/bin/wireguard-manager.sh
bash /usr/local/bin/wireguard-manager.sh
```

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/commit/296cdac87fc805a81493a66b8cc1cf5229fc5960

Workaround isnt needed anymore.
