### ISSUE TITLE
VMware Virtualization support

### ISSUE THREAD

**Issue by Rebelllious** [complexorganizations/wireguard-manager#255]
Is there any specific reason why VMware Virtualization is not supported by this project?
Recently I have started something similar to this script, and all the testing has been performed in ESXi environment. All has been working totally fine there so far.

**Comment by Prajwal-Koirala** [comment]
can u please post the error message.

**Comment by Rebelllious** [comment]
`vmware virtualization is not supported (yet).`
This is the actual error.
Also, as long as we are discussing this, I believe the virtualization check should occur as close to the script execution start as possible. I am testing everything mainly on CentOS7, which prior to getting to the virtualization check in its current implementation needs to upgrade 110 packets. This results in an unnecessary waiting time of 5 and more minutes just to get to the "not supported" messaged.

**Comment by Prajwal-Koirala** [comment]
Here is the execution of the script.

1. Check for root.
2. Get system os info
3. install system requirements.
4. check for virt.

This is the fastest option, since it needs to install the requirements before it verify that its correct.

**Comment by Rebelllious** [comment]
The order you listed is not optimal for the workflow. I would go with the below:
1. Check for root.
2. Get system os info.
3. Check if systemd-detect-virt is present (only this package). For instance, with CentOS 7 it is present by default, the same may be true for multiple other distributions. If not present, install just this one, without all other dependencies listed in the OS update section.
4. If current virtualization is not supported, exit. If supported, go with further steps like OS update and installing dependencies.

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/pull/267

This should speed up the things and no longer have to wait for your system to update.

**Comment by Prajwal-Koirala** [comment]
```
real    1m47.184s
user    0m2.848s
sys     0m0.565s
```

**Comment by Rebelllious** [comment]
We have diverted from the original topic of this issue.
Why is VMware virtualization not supported by this project? Any specific issues @Prajwal-Koirala?

**Comment by Rebelllious** [comment]
I can help with this, I have an ESXi server available. Also, I am testing the script only on ESXi virtualization and have not had any issues related to virtualization until now. I would say it's worth adding it to the supported scenarios unless we hit any specific bug related to it.

**Comment by Prajwal-Koirala** [comment]
Done.
