### ISSUE TITLE
Script failing on latest CentOS 7 with kernel 3.10

### ISSUE THREAD

**Issue by Rebelllious** [complexorganizations/wireguard-manager#256]
**Describe the bug**
Error: Kernel 3.10 not supported, please update to 3.1.

**To Reproduce**
1. Download the script;
2. Make it executable;
3. Run the script;
4. Obtained error: 
Error: Kernel 3.10 not supported, please update to 3.1.
[root@wireguard-centos7 ~]# _uname -r_
_3.10.0-1160.el7.x86_64_

**Expected behavior**
Installation expected to complete successfully on kernel 3.10 according to project how-to.

**Comment by Prajwal-Koirala** [comment]
Just update the kernel.

**Comment by Rebelllious** [comment]
I may be missing something, but 3.1 (stated as supported) is less than 3.10 (which turns out to be unsupported), isn't it?

**Comment by Rebelllious** [comment]
Pull request #264 submitted
