### ISSUE TITLE
resolvconf not available for CentOS/RHEL/Alma/Rocky

### ISSUE THREAD

**Issue by Rebelllious** [complexorganizations/wireguard-manager#258]
**Describe the bug**
No package named _resolvconf_ is present in repositories for CentOS, RHEL, Alma, or Rocky.

**To Reproduce**
1. Launch the script to install/configure Wireguard;
2. At the step of DNS provider selection, go with the default option of installing Unbound, which also attempts installing resolvconf;
3. Installation fails, as at a certain point the script is no longer available to resolve the URLs defined in the global variables (like raw.githubcontent.com etc.)

**Expected behavior**
Script is expected to complete installation successfully.

**Comment by Prajwal-Koirala** [comment]
Any resolutions for this?

**Comment by Rebelllious** [comment]
Why is this closed? It's not yet resolved, which means there is still a bug in the script.
I have spent some time investigating how this can be fixed, but in fact it's not as simple as it could be and requires more effort that I will put into this a bit later.

**Comment by Prajwal-Koirala** [comment]
Ping me once you create a PR

**Comment by Prajwal-Koirala** [comment]
> Why is this closed? It's not yet resolved, which means there is still a bug in the script. I have spent some time investigating how this can be fixed, but in fact it's not as simple as it could be and requires more effort that I will put into this a bit later.

Any update on this?

**Comment by Rebelllious** [comment]
I feel like a project manager is breathing at my neck forcing me to do something 🗡️ 
In fact, I am participating in this project in my free time, so this will not be lightning fast.
Back to the thing:
openresolv is most likely what we need. I have found the way to install it to both rhel family 7 and family 8 distros as a separate rpm, but have not done any testing of its installation as part of the script. Will still need some time.
If you think you can do that faster and on multiple distros, here are the commands to install openresolve:

family 8 (Rocky / Alma / RHEL / Oracle Linux 8):
`yum install https://download-ib01.fedoraproject.org/pub/fedora/linux/releases/35/Everything/x86_64/os/Packages/o/openresolv-3.12.0-2.fc35.noarch.rpm`

family 7 (CentOS 7 / Oracle Linux 7):
`
wget https://copr.fedorainfracloud.org/coprs/macieks/openresolv/repo/epel-7/macieks-openresolv-epel-7.repo -P /etc/yum.repos.d/
yum install openresolv
`

**Comment by Prajwal-Koirala** [comment]
> 

Thanks, I will get it done today.

**Comment by Rebelllious** [comment]
by the way, it should be available on Fedora in its repositories, based on where we are going to install the rpm, but I just have no Fedora VM deployed at the moment to test it.

**Comment by Prajwal-Koirala** [comment]
I have a 72 hour VM if u want, send me a email , `prajwalkoirala23@protonmail.com` and I see you the logins.

**Comment by Rebelllious** [comment]
Tested on Fedora Server 35 - openresolv is available in the default repositories right after OS installation is completed.

**Comment by Rebelllious** [comment]
Tested my code on CentOS 7 / Rocky - it works, but requires configuration of the firewall (masquerading and allowing VPN port on firewall). The firewall config is not yet scripted, I hope to complete it this weekend.
P.S. I was surprised to see the script did not have any firewall related stuff at all.

**Comment by Prajwal-Koirala** [comment]
> Tested my code on CentOS 7 / Rocky - it works, but requires configuration of the firewall (masquerading and allowing VPN port on firewall). The firewall config is not yet scripted, I hope to complete it this weekend. P.S. I was surprised to see the script did not have any firewall related stuff at all.

The firewall will not be apart of this since, this is just wireguard, there is another script for firewall.

**Comment by Rebelllious** [comment]
Apparently, for RHEL I will have to include firewall config commands, otherwise it won't work.

**Comment by Prajwal-Koirala** [comment]
> Apparently, for RHEL I will have to include firewall config commands, otherwise it won't work.

Sure, please push the code changes.

**Comment by Prajwal-Koirala** [comment]
> Apparently, for RHEL I will have to include firewall config commands, otherwise it won't work.

This is the only major issue in Radhat based OS, if u can push some code for this, it will be done.

**Comment by Rebelllious** [comment]
I have the code, will push it today. I wanted to give it a test in Fedora, which could behave a bit different from the rest of the distros.

**Comment by Rebelllious** [comment]
So, yeah, mulitple issues with Fedora found.
1. resolvconf / openresolv installs differently from other RHEL distros (compare below):
```
[root@wireguard-centos7 ~]# ls -la /usr/sbin/resolvconf
-rwxr-xr-x. 1 root root 21692 Nov 17  2017 /usr/sbin/resolvconf
```
```
[root@wireguard-fedora ~]# ls -la /usr/sbin/resolvconf
lrwxrwxrwx. 1 root root 28 Feb 21 18:55 /usr/sbin/resolvconf -> /etc/alternatives/resolvconf
[root@wireguard-fedora unbound.conf.d]# ls -la /etc/alternatives/resolvconf
lrwxrwxrwx. 1 root root 31 Feb 21 18:55 /etc/alternatives/resolvconf -> /usr/sbin/resolvconf.openresolv
[root@wireguard-fedora unbound.conf.d]# ls -la /usr/sbin/resolvconf.openresolv
-rw-r--r--. 1 root root 23971 Jul 23  2021 /usr/sbin/resolvconf.openresolv
```
Making this last file executable (755, same as in CentOS, for example) solves the issue with wireguard tunnel service start.

2. In Fedora Server, the default firewalld zone is FedoraServer, while all other RHEL based distros have it as "public".
```
[root@wireguard-fedora unbound.conf.d]# firewall-cmd --get-default-zone
FedoraServer
```
```
[root@wireguard-centos7 ~]# firewall-cmd --get-default-zone
public
```
Will adjust the code tonight, give it some more testing and finally make the pull request.

**Comment by ziogref** [comment]
Just installed on a raspberry pi 3B+ running Ubuntu 20.04.4 LTS and it was also missing resolvconf

Once it apt install resolvconf then the wireguard successfully started the service.

**Comment by Prajwal-Koirala** [comment]
> Just installed on a raspberry pi 3B+ running Ubuntu 20.04.4 LTS and it was also missing resolvconf
> 
> Once it apt install resolvconf then the wireguard successfully started the service.

Did u use unbound?
