### ISSUE TITLE
Incorrect CURL parameters in CentOS 7

### ISSUE THREAD

**Issue by Rebelllious** [complexorganizations/wireguard-manager#259]
**Describe the bug**
1. the latest curl in CentOS 7 does not accept a decimal numeral (e.g. 5.00) value for the "--connection-timeout" parameter. Integer works fine.
2. the latest curl CentOS 7 needs to use the "--tlsv1.3" to produce any output from https://api.ipengine.dev

**To Reproduce**
1. Go to a CentOS 7 instance
2. Run and compare the commands below:
_curl -4 --connect-timeout 5.00 -s 'https://api.ipengine.dev'_ (error due to "_curl: option --connect-timeout: expected a proper numerical parameter_")
_curl -4 --connect-timeout 5 -s 'https://api.ipengine.dev'_ (empty output)
_curl -4 --connect-timeout 5 -s 'https://api.ipengine.dev' --tlsv1.3_ (proper output)

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/pull/262

**Comment by Prajwal-Koirala** [comment]
Merged.
