### ISSUE TITLE
under arch linux wireguard-manager not work

### ISSUE THREAD

**Issue by joks-arch** [complexorganizations/wireguard-manager#26]
hello so first error what i saw when i first run script was messages that:

1) file /etc/sysctl.conf does not exist.

referring to arch wiki https://wiki.archlinux.org/index.php/sysctl#Configuration
From version 207 and 21x, systemd only applies settings from /etc/sysctl.d/*.conf and /usr/lib/sysctl.d/*.conf. If you had customized /etc/sysctl.conf, you need to rename it as /etc/sysctl.d/99-sysctl.conf

2) second error what i saw was that package  **wireguard-arch** does not exist and pacman can`t find it
referring to arch wiki with installation wireguard:
https://wiki.archlinux.org/index.php/WireGuard#Installation
under arch linux we have only this package: wireguard-tools, wireguard-lts for the LTS and wireguard-dkms no mention about package wireguard-arch

3) and the last error is command not found in lines 820,821,822,823,826

Created symlink /etc/systemd/system/multi-user.target.wants/unbound.service → /usr/lib/systemd/system/unbound.service.
/etc/wireguard/wireguard-server.sh: linia 820: wg: nie znaleziono polecenia
/etc/wireguard/wireguard-server.sh: linia 821: wg: nie znaleziono polecenia
/etc/wireguard/wireguard-server.sh: linia 822: wg: nie znaleziono polecenia
/etc/wireguard/wireguard-server.sh: linia 823: wg: nie znaleziono polecenia
/etc/wireguard/wireguard-server.sh: linia 826: wg: nie znaleziono polecenia
257
Failed to enable unit: Unit file wg-quick@wg0.service does not exist.
Failed to restart wg-quick@wg0.service: Unit wg-quick@wg0.service not found.

all these errors mean that the system cannot even start the wireguard service

**Comment by Prajwal-Koirala** [comment]
PR.

**Comment by joks-arch** [comment]
today i look into code and i think that first error:
**file /etc/sysctl.conf does not exist**

appears because in the code in lines 485, 491, 498 we have command  sysctl -p but no specified file name so system search default file /etc/sysctl.con but in new systemd version this file does not exist.
after i change in code sysctl -p to sysctl -p /etc/sysctl.d/wireguard.conf no error appears

second error i also fix removing in 636 line wireguard-arch

**Comment by Prajwal-Koirala** [comment]
Please make the changes and make a pull request.

**Comment by joks-arch** [comment]
i think now you can close this issue ;)
today when i install wireguard-manager on other computer I saw small bug - I chose not to install Unbound but in last steps i have:
`242
Failed to enable unit: Unit file unbound.service does not exist.
Failed to restart unbound.service: Unit unbound.service not found.
242
`
i think when we choosing not to install Unbound there should not even be attempts for launching this service. my skills in bash 
are limited but if I can figure out why i will do full request.

**Comment by Prajwal-Koirala** [comment]
> i think now you can close this issue ;)
> today when i install wireguard-manager on other computer I saw small bug - I chose not to install Unbound but in last steps i have:
> `242 Failed to enable unit: Unit file unbound.service does not exist. Failed to restart unbound.service: Unit unbound.service not found. 242 `
> i think when we choosing not to install Unbound there should not even be attempts for launching this service (lines in code 807,808). my skills in bash are limited but if I can figure out how to fix it i will do full request.

https://github.com/complexorganizations/wireguard-manager/commit/933a6caca4a2777068b48935f4a5bd65cc4fe82b

Done.
