### ISSUE TITLE
Uninstall Unbound - wrong commands for Alma Linux and Rocky Linux

### ISSUE THREAD

**Issue by Rebelllious** [complexorganizations/wireguard-manager#260]
**Describe the bug**
the code section for uninstalling _unbound_ has got Alma Linux and Rocky Linux added to the same family as Arch Linux and Manjaro and thus asks both Alma/Rocky to use Pacman for uninstalling unbound. Which is totally wrong.

**To Reproduce**
Looking at the code will be enough

**Comment by Prajwal-Koirala** [comment]
Please create PR.
