### ISSUE TITLE
Unbound failing to start when DNS server cache download attempted from combinatronics.io (502 Bad Gateway)

### ISSUE THREAD

**Issue by Rebelllious** [complexorganizations/wireguard-manager#271]
**Describe the bug**
If at random combinatronics.io source is selected by the script, unbind fails to start due to incorrect information dumped into the config file (html page with error 502 rather than the proper cache file).

**To Reproduce**
1. Attempting to access https://combinatronics.io/complexorganizations/wireguard-manager/main/assets/named.cache gives error 502, although https://combinatronics.io/complexorganizations/wireguard-manager/main/wireguard-manager.sh responds with proper content.

The issue may have temporal or permanent nature and needs additional checks later on.

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/commit/4e253e48375c1f6f48feee92be0ddb4db9685dbc
