### ISSUE TITLE
check number of cpu threads and insert into /etc/unbound/unbound.conf

### ISSUE THREAD

**Issue by joks-arch** [complexorganizations/wireguard-manager#29]
Hi again,
today i figure out that one of my computer with wireguard-manager have 6 threads and another server has only two.
for best unbound performance I think the value **num-threads** in the file unbound.conf should be selected individually (people have different computers).
as i say before I'm not that good as you in bash but I had the idea of something like this:

https://github.com/joks-arch/wireguard-manager/commit/24f758311ac8be46a422c8708f4277a5e9c9cbcc

you'll probably do better anyway so i don't send any new pulle

**Comment by Prajwal-Koirala** [comment]
i think 1-2 is fine; honestly.
cause its just handing DNS traffic for a couple of connections.

**Comment by Prajwal-Koirala** [comment]
> Hi again,
> today i figure out that one of my computer with wireguard-manager have 6 threads and another server has only two.
> for best unbound performance I think the value **num-threads** in the file unbound.conf should be selected individually (people have different computers).
> as i say before I'm not that good as you in bash but I had the idea of something like this:
> 
> [joks-arch@24f7583](https://github.com/joks-arch/wireguard-manager/commit/24f758311ac8be46a422c8708f4277a5e9c9cbcc)
> 
> you'll probably do better anyway so i don't send any new pulle

https://github.com/complexorganizations/wireguard-manager/pull/31
