### ISSUE TITLE
Update command is broken

### ISSUE THREAD

**Issue by PeterRob** [complexorganizations/wireguard-manager#3]
The update URL in the script is wrong:

https://raw.githubusercontent.com/complexorganizations/wireguard-installer-manager/master/wireguard-server.sh

should be:

https://raw.githubusercontent.com/complexorganizations/wireguard-manager/master/wireguard-server.sh

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/commit/cd10c9e35e3439f54f5457b12335e513263b4ef5

**Comment by Prajwal-Koirala** [comment]
![image](https://user-images.githubusercontent.com/16564273/80663466-00055900-8a62-11ea-89b7-8bbc0f18329a.png)

**Comment by Prajwal-Koirala** [comment]
![image](https://user-images.githubusercontent.com/16564273/80664029-a6059300-8a63-11ea-867b-4f399eabcaaf.png)
