### ISSUE TITLE
UX Improvement: Don't just individually list through the packages that aren't installed smash them into a variable and echo the full list at the end.

### ISSUE THREAD

**Issue by Leopere** [complexorganizations/wireguard-manager#30]
**Is your feature request related to a problem? Please describe.**
When you're executing that [big IF](https://github.com/complexorganizations/wireguard-manager/blob/master/wireguard-server.sh#L37-L83) statement checking for installed prerequisites you can echo the previous value of a variable into itself along with the new item name. This way it's just a list of all packages at the end rather than a number of ambiguous progress install requests.

**Describe the solution you'd like**
Just instead of just denying the user and stopping the script you should avoid that workflow and try to progress regardless until the end of the checks entirely.
https://stackoverflow.com/a/2250199
```bash
s=test1
s="${s}test2"
```

**Describe alternatives you've considered**
Not using this script I guess.  The only other thing is to just offer to install but with the number of platforms, that you say you support that will become a big nightmare.

**Additional context**
Just an annoying UX problem that breaks the flow especially since it's not documented anywhere as prerequisites and the fact that you're requiring a few non-standard packages be installed it seems strange to not have them documented or included in the autoinstaller.

**Comment by Prajwal-Koirala** [comment]
Pull Request.

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/pull/37
