### ISSUE TITLE
Enpoint after Install Issue

### ISSUE THREAD

**Issue by lynx85** [complexorganizations/wireguard-manager#32]
**Describe the bug**
Wireguard server install script uses curl -4 -s https://api.ipengine.dev.  Website is down, at least for the past few days.  Due to this the ip address is not being placed into client configurations.

**To Reproduce**
1. Run server install script
2. examine client configuration
3. look for null:51820

**Expected behavior**
Normally the remote ip address of the server is included in the client configuration file

**Comment by Prajwal-Koirala** [comment]
Hey;
Sorry about this.
I was making some improvements to the API.

**Comment by lynx85** [comment]
No problem!  Thanks for your work on this, I use it regularly.

**Comment by Prajwal-Koirala** [comment]
👍
