### ISSUE TITLE
AWS Lightsail Ubuntu 20.04 xen virtualization is not supported (yet).

### ISSUE THREAD

**Issue by Zonder730** [complexorganizations/wireguard-manager#322]
Hello, I am trying to install WireGuard using your script on AWS lightsail Ubuntu 20.04  (Linux 5.4.0-1018-aws x86_64). Few weeks ago everything works fine, but now I get this issue

xen virtualization is not supported (yet).

Can somebody help me to fix this issue?

**Comment by prajwal-koirala-0000** [comment]
I will test it and approve it soon, can you try and deploy it on KVM virtualization?
