### ISSUE TITLE
ifupdown on Arch?

### ISSUE THREAD

**Issue by EliteCodexer** [complexorganizations/wireguard-manager#324]
The script is failing on Arch on my Linode instance. Is expecting to install the ifupdown package, but as far as I know that's a debian thing is it not?
![image](https://user-images.githubusercontent.com/13368848/166816576-8dfb5b5a-a1c6-4860-bc09-a067134d4be7.png)

**Comment by prajwal-koirala-0000** [comment]
Do u know any other package that does the same thing?

**Comment by EliteCodexer** [comment]
netctl does I believe

**Comment by Prajwal-Koirala** [comment]
Here are some top hosting providers who support Arch Linux for cheap, based on a combination of factors like price, reliability, and user reviews:

**Budget-Friendly:**

* **Vultr:** Starting at $5 per month for a 1GB RAM, 1 CPU core, 25GB SSD VPS. Offers multiple locations and flexible configurations.
* **Linode:** Starting at $5 per month for a 1GB RAM, 1 CPU core, 25GB SSD VPS. Known for its high performance and reliability.
* **UpCloud:** Starting at $4.50 per month for a 512MB RAM, 1 CPU core, 20GB SSD VPS. Offers hourly billing and good performance for lightweight tasks.
* **Hetzner:** Starting at €3.65 per month for a 1GB RAM, 1 CPU core, 20GB SSD VPS. Popular choice for European users with competitive pricing and good performance.
* **OVHcloud:** Starting at €3.99 per month for a 1GB RAM, 1 CPU core, 25GB SSD VPS. Large European provider with extensive infrastructure and various configurations.

**Performance-Focused:**

* **DigitalOcean:** Starting at $5 per month for a 1GB RAM, 1 CPU core, 25GB SSD VPS. Reliable and well-known provider with good performance and global reach.
* **Kamatera:** Starting at $4 per month for a 1GB RAM, 1 CPU core, 20GB SSD VPS. Offers high-performance bare metal servers and VPS options.
* **VPSDime:** Starting at $4.95 per month for a 1GB RAM, 1 CPU core, 20GB SSD VPS. Known for its high-bandwidth options and good network performance.
* **Scaleway:** Starting at €2.99 per month for a 512MB RAM, 1 CPU core, 20GB SSD VPS. Affordable French provider with good performance and various configurations.

**Additional Considerations:**

* **Location:** Choose a provider with datacenters close to your target audience for optimal performance.
* **Features:** Compare features like storage, bandwidth, backups, and control panel access to find a suitable fit.
* **Reviews:** Read user reviews and benchmarks to get insights into real-world experiences with different providers.

Remember, the "best" provider depends on your specific needs and budget. Consider your requirements carefully and compare options before making a decision.

I hope this list helps you find a reliable and affordable Arch Linux hosting provider!
