### ISSUE TITLE
Not deleting peer info in wg conf file

### ISSUE THREAD

**Issue by pepgubau** [complexorganizations/wireguard-manager#33]
Hi Prajwal, thanks for your awesome work.

**Describe the bug**
When deleting a peer, client file is deleted but not info in wg conf file

**Additional context**
My guess is in line #1000 is missing a return between "echo" and "sed"

<img width="1153" alt="Screen Shot 2020-08-19 at 13 24 46" src="https://user-images.githubusercontent.com/8314689/90629291-67b4ff00-e21f-11ea-8824-9a66cbc8e686.png">

**Comment by Fastidious** [comment]
Not missing, I don't think `echo` goes there at all. Removing it does the trick.

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/pull/34
