### ISSUE TITLE
Error when attempting to add clients

### ISSUE THREAD

**Issue by charlieresendiz** [complexorganizations/wireguard-manager#340]
I was able to create 5 client config files after the initial install. About 2 weeks later, I attempted to create a new file but with no success

Error Message:
```
./wireguard-manager.sh: line 1152: [: : integer expression expected
Unable to parse IP address: `[Interface].7'
Configuration parsing error
Unable to parse IP address: `[Interface].7'
Configuration parsing error
```

Using Option:
 5) Add WireGuard Peer (client)

I expect a client config and QR code to be generated after assigning a name however, instead I receive the error message stated above. Here is what that client config looks like: [NOTE: Private key and PSK were generated but have been removed in the example below]

```
# https://www.wireguard.com
[Interface]
Address = [Interface].7/[Interface],[Interface]:1/[Interface]
DNS = [Interface]
ListenPort = 11719
MTU = [Interface]
PrivateKey = 
[Peer]
AllowedIPs = [Interface]
Endpoint = [Interface]
PersistentKeepalive = [Interface]
PresharedKey = 
PublicKey = [Interface]
# https://www.wireguard.com
[Interface]
Address = [Interface].7/[Interface],[Interface]:1/[Interface]
DNS = [Interface]
ListenPort = 28259
MTU = [Interface]
PrivateKey = 
[Peer]
AllowedIPs = [Interface]
Endpoint = [Interface]
PersistentKeepalive = [Interface]
PresharedKey = 
PublicKey = [Interface]

```
Desktop:
Ubuntu 22.04.1 LTS

**Comment by Rebelllious** [comment]
what does line 1152 look like in your script?

**Comment by charlieresendiz** [comment]
> what does line 1152 look like in your script?

`while [ "${SMALLEST_USED_IPV6}" -le "${LARGEST_USED_IPV6}" ]; do`

**Comment by charlieresendiz** [comment]
```
wireguard-manager.sh: No such file or directory
4067F4BA807F0000:error:80000002:system library:file_ctrl:No such file or directory:../crypto/bio/bss_file.c:297:calling fopen(wireguard-manager.sh, r)
4067F4BA807F0000:error:10080002:BIO routines:file_ctrl:system lib:../crypto/bio/bss_file.c:300:

```

**Comment by charlieresendiz** [comment]
Thanks for the info, I take it this means I will need to generate new client configs as well? Or can those be saved and imported back in?

**Comment by charlieresendiz** [comment]
I went through the steps and after rebooting the server I get this error when attempting to add a new client:

```
/usr/local/bin/wireguard-manager.sh: line 1142: [: : integer expression expected
/usr/local/bin/wireguard-manager.sh: line 1152: [: : integer expression expected
Unable to modify interface: No such device
Warning: `/etc/wireguard/wg0.conf' is world accessible
Unable to modify interface: No such device
```

```
1142       while [ "${SMALLEST_USED_IPV4}" -le "${LARGEST_USED_IPV4}" ]; do

1152       while [ "${SMALLEST_USED_IPV6}" -le "${LARGEST_USED_IPV6}" ]; do

```

Client config: Everything generated but I believe the Address line is wrong

```
# https://www.wireguard.com
[Interface]
Address = 172.21.121.2/172.21.121.0,fd00:00:00::2/8
```

**Comment by Rebelllious** [comment]
Yes, the subnet mask for IPv4 interface is wrong there for sure.

**Comment by charlieresendiz** [comment]
Yes, that was my mistake.

I was able to generate a client config and get connected. But it looks like I can't access anything outside our VPN server or external websites

**Comment by charlieresendiz** [comment]
This issue has been resolved. The steps above took care of the issue. The internet issue previously mentioned was due to a mistake I made when configuring the IPv4 address.
