### ISSUE TITLE
AWS Lightsail Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-1017-aws x86_64) amazon virtualization is not supported (yet).

### ISSUE THREAD

**Issue by Zonder730** [complexorganizations/wireguard-manager#342]
Hello, I am trying to install WireGuard using your script on AWS lightsail Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-1017-aws x86_64). After update from 20.04 to 22.04.1 I get this issue:

ubuntu@MyWireGuard:~$ sudo bash /usr/local/bin/wireguard-manager.sh
amazon virtualization is not supported (yet).

**Comment by Zonder730** [comment]
Hello guys do you have any updates here?

**Comment by Rebelllious** [comment]
Run "hostnamectl" in the VM and provide the output.

**Comment by Zonder730** [comment]
ubuntu@MyWireGuard:~$ hostnamectl
 Static hostname: MyWireGuard
       Icon name: computer-vm
         Chassis: vm
      Machine ID: ec22fbb044b1ba56729ad946da4981f8
         Boot ID: 85d28a5bb82f47c8968946859cc79cf6
  Virtualization: amazon
Operating System: Ubuntu 22.04.1 LTS
          Kernel: Linux 5.15.0-1017-aws
    Architecture: x86-64
 Hardware Vendor: Amazon EC2
  Hardware Model: t3.nano

**Comment by Rebelllious** [comment]
https://github.com/complexorganizations/wireguard-manager/issues/248#issuecomment-1004488652

From this, adjust it to "amazon" virtualization and tell us if it works.

To be honest,  I have zero idea what stands behind "amazon" virtualization in this scenario...  Probably some sort of KVM home brewed one

**Comment by Zonder730** [comment]
I don’t understand what should I do? If you tell me, how to adjust it to Amazon virtualization, I will do it.

**Comment by Zonder730** [comment]
The same result
![Снимок экрана 2022-08-23 104201](https://user-images.githubusercontent.com/104627018/186101006-affe629a-035a-4176-8fb6-f847b06438cc.png)

**Comment by Zonder730** [comment]
I just create new vm. Upgrade it from 20.04 to 22.04.1. And everything works fine, so I have this issue only with VM with already installed Wireguard. Script does not work.

**Comment by Rebelllious** [comment]
It looks like the DNS resolution gets broken somewhere in between. I remember I reported this bug earlier and we reworked the way it does resolution (order of actions changed), but cannot recollect what exactly was changed from the top of my head.
@fX4N1DmH311X39SpxXLWxMWy49n6o8zb you know the code better, probably.

**Comment by Zonder730** [comment]
Guys do you have any updates here?
