### ISSUE TITLE
Script tries to use dpkg on a CentOS7 server

### ISSUE THREAD

**Issue by drphr4ud** [complexorganizations/wireguard-manager#36]
**Describe the bug**

What do you want to do?
   1) Show WireGuard Interface
   2) Start WireGuard Interface
   3) Stop WireGuard Interface
   4) Restart WireGuard Interface
   5) Add WireGuard Peer
   6) Remove WireGuard Peer
   **7) Reinstall WireGuard Interface**
   8) Uninstall WireGuard Interface
   9) Update this script
Select an Option [1-9]: **7**
340
`/usr/local/bin/wireguard-server.sh: line 1015: dpkg-reconfigure: command not found`

**To Reproduce**
Install server, re-run script. Select option 7.

**Expected behavior**
It should restart the configuration questions and let me reinstall.

**Screenshots**

```
CentOS Linux release 7.8.2003 (Core)
Linux kiv.hlex.pw 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
wireguard-dkms-1.0.20200729-1.el7.noarch
wireguard-tools-1.0.20200513-1.el7.x86_64
```

**Comment by Prajwal-Koirala** [comment]
Please update the script and try again.
Read the script; that should not have happened.

**Comment by drphr4ud** [comment]
Just created a new CentOS7 VM on a different cloud platform and pulled the current revision of the script from master. The issue can be replicated.
![wg2](https://user-images.githubusercontent.com/23167595/92072091-fe1e1e80-ede2-11ea-92c2-70d0b54ee57f.JPG)

**Comment by Prajwal-Koirala** [comment]
Will test it.

**Comment by Prajwal-Koirala** [comment]
Hey;
Question what cloud provider are u using?

**Comment by drphr4ud** [comment]
I tested on CentOS 7 images provided by Hetzner, Trabia and Vultr.

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/commit/41fcebedd03485bb21913b6075414207a5452848

**Comment by Prajwal-Koirala** [comment]
Fixed.
