### ISSUE TITLE
wireguard-server.sh: line 53: bc: command not found

### ISSUE THREAD

**Issue by hundehausen** [complexorganizations/wireguard-manager#38]
**Describe the bug**
wireguard-server.sh: line 53: bc: command not found

**To Reproduce**
1. git clone master
2. make files executable
3. run `sudo ./wireguard-server.sh --help`

**Expected behavior**
see help page

**Desktop (please complete the following information):**
 - OS: Ubuntnu 20.04
 - Version: master branch

**Comment by Prajwal-Koirala** [comment]
```
    apt-get update && apt-get install iptables curl coreutils bc jq sed e2fsprogs -y
```

**Comment by Prajwal-Koirala** [comment]
UPDATE:
Fixed the design of the software as well so this issue doesn't occur for more people.
