### ISSUE TITLE
errors right after install

### ISSUE THREAD

**Issue by digim-s15** [complexorganizations/wireguard-manager#397]
Select an Option [1-16]:5
Let's name the WireGuard Peer. Use one word only, no special characters, no spaces.
New client peer:8a241f1d6561b1ad0fdf6609bd735b21e248d92d049dab1f5c293105cc33325557f4f3b57b76fc62bf23e8931fa1c03c38d3
/usr/local/bin/wireguard-manager.sh: line 1401: [: 10.66.241.2: integer expression expected
/usr/local/bin/wireguard-manager.sh: line 1479: 10.66.241.2: syntax error: invalid arithmetic operator (error token is ".66.241.2")

**To Reproduce**
install, run, select 5

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04.03 LTS

**Comment by Rebelllious** [comment]
Before I spin up this specific OS in a VM, can you tell me what that option 5 is exactly? Is it about adding new peer?

**Comment by Rebelllious** [comment]
And what version of the script you are using, too. As the current version has variable assignment in line 1479, for example, which does not help.

**Comment by digim-s15** [comment]
this was latest script, downloaded yesterday, 5 is add new peer, yes
i managed to fix this. maybe somehow previous installs of WG on this server interfering with current install
**uninstall and reinstall from script menu worked for me**
