### ISSUE TITLE
unbound error

### ISSUE THREAD

**Issue by shanny36** [complexorganizations/wireguard-manager#40]
```
Sep 24 03:54:08 service1 systemd[1]: unbound.service: Scheduled restart job, restart counter is at 7.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- Automatic restarting of the unit unbound.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Sep 24 03:54:08 service1 systemd[1]: Stopped Unbound DNS server.
-- Subject: A stop job for unit unbound.service has finished
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A stop job for unit unbound.service has finished.
-- 
-- The job identifier is 1668 and the job result is done.
Sep 24 03:54:08 service1 systemd[1]: unbound.service: Start request repeated too quickly.
Sep 24 03:54:08 service1 systemd[1]: unbound.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit unbound.service has entered the 'failed' state with result 'exit-code'.
Sep 24 03:54:08 service1 systemd[1]: Failed to start Unbound DNS server.
-- Subject: A start job for unit unbound.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit unbound.service has finished with a failure.
-- 
-- The job identifier is 1668 and the job result is failed.
Sep 24 03:54:08 service1 systemd[1]: unbound-resolvconf.service: Start request repeated too quickly.
Sep 24 03:54:08 service1 systemd[1]: unbound-resolvconf.service: Failed with result 'start-limit-hit'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- The unit unbound-resolvconf.service has entered the 'failed' state with result 'start-limit-hit'.
Sep 24 03:54:08 service1 systemd[1]: Failed to start Unbound DNS server via resolvconf.
-- Subject: A start job for unit unbound-resolvconf.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit unbound-resolvconf.service has finished with a failure.
-- 
-- The job identifier is 1737 and the job result is failed.
```

Debian 9, Debian 10, Ubuntu 18.04, Ubuntu 20.04 error with unbound

**Comment by shanny36** [comment]
```
/etc/unbound/root.hints
```

error not created this file

**Comment by Prajwal-Koirala** [comment]
```
      curl https://www.internic.net/domain/named.cache --create-dirs -o /etc/unbound/root.hints
```

**Comment by Prajwal-Koirala** [comment]
any comments?

**Comment by quyleanh** [comment]
I don't know. I have to create `/etc/unbound/root.hints` to restart `unbound` service.
Could you check again your script?
https://github.com/complexorganizations/wireguard-manager/blob/1f45a2558ab847fcdfc82878aa7e2bc46f879b74/wireguard-manager.sh#L1113-L1114

**Comment by Prajwal-Koirala** [comment]
Hey during installation on some versions of unbound there are already root hints and we are removing those if found and updating to the newest version.

**Comment by quyleanh** [comment]
Thanks, but mine does not. I have manually created this file.
My server is Ubuntu 20.04.

**Comment by Prajwal-Koirala** [comment]
I already have the code for doing it automatically.
https://github.com/complexorganizations/wireguard-manager/blob/1f45a2558ab847fcdfc82878aa7e2bc46f879b74/wireguard-manager.sh#L1118

**Comment by quyleanh** [comment]
Hmm, I see this line. But still don't know why I have to manually create....
There is a log about could not resolve host. Don't know why... Access through browser is fine. Please refer.
```
~/work/vpn sudo curl https://www.internic.net/domain/named.cache --create-dirs -o /etc/unbound/root.hints
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: www.internic.net
```

**Comment by Prajwal-Koirala** [comment]
> Hmm, I see this line. But still don't know why I have to manually create....
> There is a log about could not resolve host. Don't know why... Access through browser is fine. Please refer.
> 
> ```
> ~/work/vpn sudo curl https://www.internic.net/domain/named.cache --create-dirs -o /etc/unbound/root.hints
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: www.internic.net
> ```

I will update this on the next version and fix this error.

**Comment by quyleanh** [comment]
Thank you very much.
Last time I gave up your script with the same problem about unbound. Now I'm back without problem.

**Comment by Prajwal-Koirala** [comment]
> Thank you very much.
> Last time I gave up your script with the same problem about unbound. Now I'm back without problem.

Do you have anydesk?

**Comment by quyleanh** [comment]
Yes. But for what?

**Comment by Prajwal-Koirala** [comment]
Can you please post it here, and i will connect.
i want to see what's causing the problem.

**Comment by quyleanh** [comment]
Here you are
`688 072 428`

**Comment by Prajwal-Koirala** [comment]
You need to give any desk permission to capture screen.

**Comment by Prajwal-Koirala** [comment]
https://support.anydesk.com/Security_Permissions_on_macOS

**Comment by quyleanh** [comment]
It's ok now.
