### ISSUE TITLE
Configuration for additional clients provided with error — duplicated port in the Endpoint

### ISSUE THREAD

**Issue by vasylenko** [complexorganizations/wireguard-manager#439]
**Describe the bug**
When an additional client config is created, there's an error in the output: the Endpoint value provided with a duplicated port value, for example: 
```
Endpoint = 17.143.212.215:1023010230
```

While it should be
```
Endpoint = 17.143.212.215:10230
```

**To Reproduce**

Run: `NEW_CLIENT_NAME="client-name" wireguard-manager.sh --add`

**Expected behavior**
Client's `Endpoint` configuration should be provided without error as: IP:PORT

**Additional context**
https://github.com/complexorganizations/wireguard-manager/blob/dbe16ccf9b64cdc7554046fcd0acb4e3484733b0/wireguard-manager.sh#L1575
Looks like the bug occurs here, where the SERVER_HOST variable is read from the config file.
The thing is that the field number 4 is already in the format "IP:PORT" (e.g, "17.143.212.215:10230") 

```
SERVER_HOST=$(head --lines=1 ${WIREGUARD_CONFIG} | cut --delimiter=" " --fields=4)
```

```
# head --lines=1 /etc/wireguard/wg0.conf
# 10.0.0.0/8 fd00:00:00::0/8 17.143.212.215:10230 KEY_REDACTED 10.0.0.1,fd00:00:00::1 1280 25 0.0.0.0/0,::/0

# head --lines=1 /etc/wireguard/wg0.conf  | cut --delimiter=" " --fields=4
17.143.212.215:10230
```

So when the final configuration is created, it goes as
https://github.com/complexorganizations/wireguard-manager/blob/dbe16ccf9b64cdc7554046fcd0acb4e3484733b0/wireguard-manager.sh#L1627

```
Endpoint = ${SERVER_HOST}${SERVER_PORT}
```

Which ultimately makes this port duplication as `17.143.212.215:1023010230`

**Comment by Prajwal-Koirala** [comment]
Dear Developer,

Thank you so much for your valuable contribution to our project. Your detailed bug report and the proposed solution have significantly helped us in improving our codebase. We appreciate the time and effort you've put into this.

We would also like to extend an invitation for you to join our community on Discord and Slack. These platforms offer a great space for discussions, collaboration, and getting to know other contributors. You can find the invitation links in our project's `README.md` file.

Once again, thank you for your contribution. We look forward to seeing more of your work!

Best Regards,
Prajwal
