### ISSUE TITLE
Unbound setup on Raspberry PI OS 

### ISSUE THREAD

**Issue by eveenendaal** [complexorganizations/wireguard-manager#46]
It doesn't appear the unbound.conf is being generated on RPI OS anymore during setup. The end result is clients don't get DNS resolution.

-- Steps
1. Run default install of wireguard manager on RPI
2. Look in /etc/unbound

-- Expect Result
There should be an unbound.conf file

-- Actual Result
No unbound.conf created

**Comment by Prajwal-Koirala** [comment]
can u please do
```
cat /etc/os-release
```
and post the output here.

**Comment by Prajwal-Koirala** [comment]
either u didn't run the script as sudo or the OS is supported.

**Comment by eveenendaal** [comment]
Here you go:

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by Prajwal-Koirala** [comment]
It should work, Can u please try it again and make sure, You run this as `sudo` && `root`

**Comment by eveenendaal** [comment]
I tried again:

- I ran "sudo su" to switch to root
- Ran uninstall (option 8 in the script). I also uninstalled dnsmasq I was using as a workaround.
- Run install with all defaults
- After the install finished there was no unbound.conf file.

**Comment by Prajwal-Koirala** [comment]
Found and fixed the issue, please just update the script and than run the installer.

There are 2x reasons why users get the error.
1. Unbound hasn't been installed
2. Unbound folder has been deleted

**Comment by eveenendaal** [comment]
That worked. Thank you.

**Comment by Prajwal-Koirala** [comment]
> That worked. Thank you.

Hello,
Star, Sponsors, Fork, Follow is not mandatory but is much appreciated.
- Prajwal
