### ISSUE TITLE
App Stores (both on iOS & macOS)

### ISSUE THREAD

**Issue by OmanCoding** [complexorganizations/wireguard-manager#5]
**Describe the bug**
All other connections work. Except the connection to these stores on both iOS and macOS seem to be broken.

**To Reproduce**
1. Activate Wiregurad connection
2. Visit App Store on either Apple devices.

**Expected behavior**
Should be able to navigate the stores.

**Screenshots**
<img width="1176" alt="Screen Shot 2020-05-18 at 12 05 28 PM" src="https://user-images.githubusercontent.com/38236933/82189166-01f36700-9900-11ea-92cc-f1212b286eaa.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6 (18G103)
 - Browser N/A

**Additional context**
The update section of the App Store on macOS seems to be working however navigating the store is not

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/commit/a52d35b347684006e166bd3d641407eb1e2c0f21

Updated
