### ISSUE TITLE
Config not written to the wg0.conf

### ISSUE THREAD

**Issue by grzchr15** [complexorganizations/wireguard-manager#51]
**Describe the bug**

Fresh install with wireguard-manager

**To Reproduce**
1. Fresh install with wireguard-manager
2. select option --reinstall   Reinstall WireGuard Interface
3. reinstallation happens , wg0.conf created, but no config line inside just
4. [Interface]
Address = 185.x.x.x/26
Address = fd86:ea04:1115::1/64
SaveConfig = true
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; ip6tables -A FORWARD -i wg0 -j ACCEPT; ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE; ip6tables -D FORWARD -i wg0 -j ACCEPT; ip6tables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
ListenPort = 8081
PrivateKey = xxxxxxxxxxx
4. Subsequent create of peers fails

**Expected behavior**wireguard-setconf
wireguard-setconf gets not called

**Screenshots**

**Desktop (please complete the following information):**
 - OS: uname -a
Linux fqdn 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu

**Additional context**

**Comment by grzchr15** [comment]
hat do you want to do?
   1) Show WireGuard Interface
   2) Start WireGuard Interface
   3) Stop WireGuard Interface
   4) Restart WireGuard Interface
   5) Add WireGuard Peer
   6) Remove WireGuard Peer
   7) Reinstall WireGuard Interface
   8) Uninstall WireGuard Interface
   9) Update this script
Select an Option [1-9]: 7

-------- Uninstall Beginning --------
Module:  wireguard
Version: 1.0.20201112
Kernel:  4.15.0-128-generic (x86_64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

wireguard.ko:
 - Uninstallation
   - Deleting from: /lib/modules/4.15.0-128-generic/
rmdir: failed to remove '': No such file or directory
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod...

DKMS: uninstall completed.

------------------------------
Deleting module version: 1.0.20201112
completely from the DKMS tree.
------------------------------
Done.
Loading new wireguard-1.0.20201112 DKMS files...
Building for 4.15.0-128-generic
Building initial module for 4.15.0-128-generic
Done.

wireguard:
Running module version sanity check.

Good news! Module version 1.0.20201112 for wireguard.ko
exactly matches what is already found in kernel 4.15.0-128-generic.
DKMS will not replace this module.
You may override by specifying --force.

depmod....

DKMS: install completed.

**Comment by grzchr15** [comment]
Remove wg0.conf
./wireguard-server.sh
Now Setup runs as expected

**Comment by Prajwal-Koirala** [comment]
yeah, cause u were using ur own config and this script will create its own config.

**Comment by Prajwal-Koirala** [comment]
Hello,
Star, Sponsors, Fork, Follow is not mandatory but is much appreciated.
- Prajwal

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/commit/9e32292f813a5524464a416688061dad06ec4a97

Fixed this issue for everyone.
