### ISSUE TITLE
Bug with 1.0.9

### ISSUE THREAD

**Issue by KolosovVD** [complexorganizations/wireguard-manager#53]
Ubuntu 20.04
After update to v1.0.9 every start of .sh with any parameters starts new installation

**Comment by Prajwal-Koirala** [comment]
Already fixed the bug, just use the latest changes.

**Comment by KolosovVD** [comment]
It’s already latest version. I wrote that in first comment.

**Comment by Prajwal-Koirala** [comment]
run the installer again and than install everything.

**Comment by KolosovVD** [comment]
Doesn’t work, yeah. And idk why. Before this update all was good

**Comment by Prajwal-Koirala** [comment]
can u send me an email with your server info and ill take a look at it.
`prajwalkoirala23@protonmail.com`

**Comment by KolosovVD** [comment]
So... now I have that error:
How would you like to detect IPv4?
  1) Curl (Recommended)
  2) IP (Advanced)
  3) Custom (Advanced)
IPv4 Choice [1-3]: 1
parse error: Invalid numeric literal at line 3, column 0
How would you like to detect IPv6?
  1) Curl (Recommended)
  2) IP (Advanced)
  3) Custom (Advanced)
IPv6 Choice [1-3]: 1
parse error: Invalid numeric literal at line 3, column 0

**Comment by Prajwal-Koirala** [comment]
Problem: `JQ` isn't being installed.

Answer:
```
if { ! [ -x "$(command -v curl)" ] || ! [ -x "$(command -v iptables)" ] || ! [ -x "$(command -v bc)" ] || ! [ -x "$(command -v jq)" ] || ! [ -x "$(command -v sed)" ]; }; then
```

Please pull the latest changes and it should be fixed, this has been fixed days ago.

**Comment by KolosovVD** [comment]
Unfortunately but jq is already the newest version (1.6-1).

**Comment by Prajwal-Koirala** [comment]
```

**Comment by Prajwal-Koirala** [comment]
Update: A while ago i managed to get the same issue and after that i added a fix for this in the script already.
