### ISSUE TITLE
Can't use WireGuard manager commands

### ISSUE THREAD

**Issue by zigapovhe** [complexorganizations/wireguard-manager#55]
**Describe the bug**
Unable to use most of the ./wireguard-server.sh parameters (commands) - except for --install and --help. 

**To Reproduce**
1. Type ./wireguard-server.sh --list
2. The script ask about which ipv4 subnet to use

**Expected behavior**
Show the correct information based on entered commands.

**Screenshots**
[Screenshot](https://i.imgur.com/9qR7hJT.png)

**Desktop (please complete the following information):**
 - OS: Linux raspberrypi 5.4.72-v7+ #1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - Browser /
 - Version /

**Additional context**
Tested on the latest version of WireGuard Manager (I've installed it today). The installation went without any problems.

EDIT: Added Additional context

**Comment by Prajwal-Koirala** [comment]
Thought you found a bug, got excited and than tested it on a new VM. (No Bugs.)
```
root@wireguard:/usr/local/bin# ./wireguard-server.sh --stop
What do you want to do?
   1) Show WireGuard Interface
   2) Start WireGuard Interface
   3) Stop WireGuard Interface
   4) Restart WireGuard Interface
   5) Add WireGuard Peer
   6) Remove WireGuard Peer
   7) Reinstall WireGuard Interface
   8) Uninstall WireGuard Interface
   9) Update this script
224
Removed /etc/systemd/system/multi-user.target.wants/wg-quick@wg0.service.
root@wireguard:/usr/local/bin# wg
root@wireguard:/usr/local/bin# ./wireguard-server.sh --start
What do you want to do?
   1) Show WireGuard Interface
   2) Start WireGuard Interface
   3) Stop WireGuard Interface
   4) Restart WireGuard Interface
   5) Add WireGuard Peer
   6) Remove WireGuard Peer
   7) Reinstall WireGuard Interface
   8) Uninstall WireGuard Interface
   9) Update this script
224
Created symlink /etc/systemd/system/multi-user.target.wants/wg-quick@wg0.service → /lib/systemd/system/wg-quick@.service.
root@wireguard:/usr/local/bin# wg
interface: wg0
  public key: CO3lGwp7adKjXisnwd2ejK92ErirkkMfuaGtofthZBo=
  private key: (hidden)
  listening port: 51820

peer: GfIUEa3Ihd3dxuCjfRVx+v+dSMSz/GSD5ielTaPxBBQ=
  preshared key: (hidden)
  allowed ips: 10.8.0.3/32, fd42:42:42::3/128
  ```

There are no bugs here.

**Comment by zigapovhe** [comment]
You were right. The problem was in 5.4.72-v7+ kernel which in fact broke a lot of wireguard setups around the net. Removed all wireguard packages, updated the kernel, downloaded headers and your script works fine now. Thanks!

**Comment by Prajwal-Koirala** [comment]
> You were right. The problem was in 5.4.72-v7+ kernel which in fact broke a lot of wireguard setups around the net. WireGuard never really fully installed because it always failed at the end. Removed all wireguard packages, updated the kernel, downloaded headers and your script works fine now. Thanks!

This is a known bug, the fix for this is 
```
./wireguard-server.sh --reinstall
```
