### ISSUE TITLE
All commands rewrite the config

### ISSUE THREAD

**Issue by pigger-nidoras** [complexorganizations/wireguard-manager#56]
**Describe the bug**
```
root@ubuntu:~# uname -a
Linux ubuntu 4.15.0-123-generic #126-Ubuntu SMP Wed Oct 21 09:40:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
Starting from version 1.0.8, the script overwrites the same config, and reacts to any command as `--install`. I had to go back to version 1.0.7.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Prajwal-Koirala** [comment]
Hey,
This is a known bug and its already fixed, please use the latest version of wireguard manager, it has already been fixed.

```
curl https://raw.githubusercontent.com/complexorganizations/wireguard-manager/main/wireguard-server.sh --create-dirs -o /usr/local/bin/wireguard-server.sh
chmod +x /usr/local/bin/wireguard-server.sh
bash /usr/local/bin/wireguard-server.sh
```
