### ISSUE TITLE
Option to backup WireGuard configuration and client files.

### ISSUE THREAD

**Issue by zigapovhe** [complexorganizations/wireguard-manager#57]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm updating my Raspberry Pi, and see the kernel update. It happens often, that the WireGuard just fails to build on the newly installed kernel. The next thing I have to do, is to reinstall WireGuard through WireGuard-Manager script which also removes all previous client and server configurations. 

**Describe the solution you'd like**
I know that is not the issue of the WireGuard-Manager, but I wish that there would be an option to simply backup current configuration, and option to restore one. It would be cool if you can restore it in the similar way that you remove peers with the script.

**Describe alternatives you've considered**
Currently I'm manually copying /etc/wireguard/ folder, reinstalling then copying configuration files back, but again, it would be cool if that would be supported with script.

**Additional context**

**Comment by Prajwal-Koirala** [comment]
Backup & Restore should be apart of the script and will be implemented soon.

**Comment by Prajwal-Koirala** [comment]
also this is a know issue and there is a fix for this.

```
      if { [ "$DISTRO" == "ubuntu" ] || [ "$DISTRO" == "debian" ] || [ "$DISTRO" == "raspbian" ] || [ "$DISTRO" == "pop" ] || [ "$DISTRO" == "kali" ]; }; then
        dpkg-reconfigure wireguard-dkms
        modprobe wireguard
        systemctl restart wg-quick@$WIREGUARD_PUB_NIC
      elif { [ "$DISTRO" == "fedora" ] || [ "$DISTRO" == "centos" ] || [ "$DISTRO" == "rhel" ]; }; then
        yum reinstall wireguard-dkms -y
        service wg-quick@$WIREGUARD_PUB_NIC restart
      elif { [ "$DISTRO" == "arch" ] || [ "$DISTRO" == "manjaro" ]; }; then
        pacman -Rs --noconfirm wireguard-tools
        service wg-quick@$WIREGUARD_PUB_NIC restart
      fi
```


just use this command and u won't have to manually reinstall and it wont delete the configs

```
./wireguard-server.sh --reinstall
```
