### ISSUE TITLE
/etc/wireguard/wireguard-server.sh: line 940: -4: substring expression < 0

### ISSUE THREAD

**Issue by 0Zinc** [complexorganizations/wireguard-manager#6]
**Describe the bug**
I get `/etc/wireguard/wireguard-server.sh: line 940: -4: substring expression < 0` when attempting to add a new peer.

**To Reproduce**
1. `sudo bash /etc/wireguard/wireguard-manager.sh`
2. Enter 5 to add a new peer
3. Name the peer anything, you get the same error

**Expected behavior**
The peer should be added

**Screenshots**

**Desktop (please complete the following information):**
 - Raspbian Stretch

**Additional context**
I'm running this on a raspberry pi, and have already setup wireguard before running this script.

**Comment by Prajwal-Koirala** [comment]
update the script.
```
cd /etc/wireguard
./wireguard-server.sh --update
```

**Comment by 0Zinc** [comment]
Same issue after updating

**Comment by Prajwal-Koirala** [comment]
you might be using the old script so to force update it to the new one, please use this command.

```
curl https://raw.githubusercontent.com/complexorganizations/wireguard-manager/master/wireguard-server.sh --create-dirs -o /etc/wireguard/wireguard-server.sh
```
```
chmod +x /etc/wireguard/wireguard-server.sh
```
```
bash /etc/wireguard/wireguard-server.sh
```

This should fix the issue, but if this dosen't please send me a msg and we can work on fixing it together.

**Comment by 0Zinc** [comment]
Done those commands, same error but on a different line
`/etc/wireguard/wireguard-server.sh: line 944: -4: substring expression < 0`

**Comment by Prajwal-Koirala** [comment]
Delete the file and download it again
