### ISSUE TITLE
DNS Resolver not working

### ISSUE THREAD

**Issue by bumansu** [complexorganizations/wireguard-manager#61]
I've been using your script on my server since late August, everything worked like a charm.
Thanks for the great job !!

Today I decided to reinstall my server and your script.
DNS resolver is not working.
I can ping 8.8.8.8 but not google.com.
Wireguad is working and establishing connections normally.

Did you change anything in your script that could cause DNS problems?

**Comment by bumansu** [comment]
I used your script from September 19, 2020 and it works now.

Would look into that issue? Would really like to use your current script.

**Comment by Prajwal-Koirala** [comment]
for some users it seems like DNSSEC isnt working, i will fix this issue within 24 hours from now.

**Comment by Prajwal-Koirala** [comment]
Update: The issue was fixed, and fixed the DNSSEC issue for everyone without having to disable DNSSEC.
