### ISSUE TITLE
Support Oracle Linux

### ISSUE THREAD

**Issue by pomazanbohdan** [complexorganizations/wireguard-manager#74]
pls add support Oracle Linux (ol) 8.3

**Comment by LM1LC3N7** [comment]
Hello, I have the same need if possible :smiley: 
It is very close to CentOS, maybe even identical.

**Comment by Prajwal-Koirala** [comment]
Do u know which Hosting Provider Supports it?

**Comment by pomazanbohdan** [comment]
oracle cloud ))

a lot of people converted to it after the news about centos

**Comment by pomazanbohdan** [comment]
> If someone provides me with a testing VPS or tells me a Provider who supports it than it will just take a couple of hours.

public key to pomazan.bogdan@gmail.com

**Comment by pomazanbohdan** [comment]
- Oracle Linux
- https://www.almalinux.org/

**Comment by LM1LC3N7** [comment]
I also have migrated to Oracle Linux because of the last CentOs news. 
I used IPMI on a bare metal server (scaleway) but I am pretty sure that AWS or Azure have Oracle Linux images.

**Comment by Prajwal-Koirala** [comment]
Note: Working on it, should be completed within 48 hours.

**Comment by Prajwal-Koirala** [comment]
If anyone has an extra VPS to test things on please feel free to send me the info at `prajwalkoirala23@protonmail.com` and than just delete the VPS after 24 hours.

**Comment by Prajwal-Koirala** [comment]
Anyone willing to beta test it?

@pomazanbohdan 
@LM1LC3N7

**Comment by LM1LC3N7** [comment]
I can. Did you change anything in your code or just add a new test for ol in order to reuse the red hat existing code?

**Comment by Prajwal-Koirala** [comment]
I changed a bunch of things.

**Comment by LM1LC3N7** [comment]
I ask because in my last test (manually sets up Wireguard), I blocked all the incoming network when starts the wg0 card 😅 

My server is using the defaults: firewalld with nftables (with still an iptables like interface).

**Comment by LM1LC3N7** [comment]
How can I try?

**Comment by Prajwal-Koirala** [comment]
Making a PR, sorry for the delay.

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/pull/183

**Comment by Prajwal-Koirala** [comment]
```
[root@prajwal-koirala /]# cat /etc/os-release 
NAME="Oracle Linux Server"
VERSION="8.5"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.5"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:5:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.5
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.5
```
