### ISSUE TITLE
Is it possible to BULK add peers?

### ISSUE THREAD

**Issue by mmomasters** [complexorganizations/wireguard-manager#76]
I need to wireguard-manager.sh --add 100 clients

Like peer1 peer2 .... peer100

Is it possible?

Thank you!

**Comment by Prajwal-Koirala** [comment]
Yes.
The client names have to be random for this to work, it will take way too long if the client name is manual.

**Comment by mmomasters** [comment]
I see and what if I write a bash script like:

wireguard-manager.sh --add peer1
wireguard-manager.sh --add peer2
........................................................................
wireguard-manager.sh --add peer100

**Comment by Prajwal-Koirala** [comment]
```
echo -e "Client-Name" | ./wireguard-manager.sh --add
```
