### ISSUE TITLE
Max 255 Peers. After add 10.8.0.255 ip script add 10.8.0.256, and service restart fail. 

### ISSUE THREAD

**Issue by iqdoctor** [complexorganizations/wireguard-manager#84]
Need integer counter to count peers and integer 2 ip conversion.

**Comment by Prajwal-Koirala** [comment]
So there is this variable that says `LAST_IPV4` we can use that to see if it's less then or greater than a number

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/blob/main/wireguard-manager.sh#L1117

```
        LASTIP4=$(grep "/32" $WIREGUARD_CONFIG | tail -n1 | awk '{print $3}' | cut -d "/" -f 1 | cut -d "." -f 4)
        LASTIP6=$(grep "/128" $WIREGUARD_CONFIG | tail -n1 | awk '{print $3}' | cut -d "/" -f 1 | cut -d "." -f 4)
        CLIENT_ADDRESS_V4="${PRIVATE_SUBNET_V4::-4}$((LASTIP4 + 1))"
        CLIENT_ADDRESS_V6="${PRIVATE_SUBNET_V6::-4}$((LASTIP6 + 1))"
```

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/commit/1b00b2a6d4849dc5d828acca3c59a5f32cbb13d8

Done.

**Comment by iqdoctor** [comment]
Better than nothing, but I prefer after 10.8.0.255 set net ip to 10.8.1.1, not stop script.
I understand your point about PR.

**Comment by Prajwal-Koirala** [comment]
This is a temp fix, (Hot fix) and a perm solution will come in time.

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/pull/101

**Comment by Prajwal-Koirala** [comment]
Hey @iqdoctor
I found a solution where lets say the local network is `10.0.0.0` and after 255 IP's it will be `10.1.0.0`
What do u think of a solution like this?

**Comment by Prajwal-Koirala** [comment]
> Better than nothing, but I prefer after 10.8.0.255 set net ip to 10.8.1.1, not stop script.
> I understand your point about PR.

Do you have the code for this?

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/pull/203

**Comment by Prajwal-Koirala** [comment]
# Merging it to main today so i will close this today.

**Comment by Prajwal-Koirala** [comment]
### This feature has been added.
