### ISSUE TITLE
Config expiry function

### ISSUE THREAD

**Issue by johnmalay** [complexorganizations/wireguard-manager#89]
Any plan to add subscription base function to wg config? Example here, a function to check and set wg config to expired within time range 1 month

**Comment by Prajwal-Koirala** [comment]
If someone makes a PR for this, i will accept it.

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/pull/197

**Comment by Prajwal-Koirala** [comment]
Also.
What options should be available?

1. One month
2. Six month
3. No months

**Comment by Prajwal-Koirala** [comment]
Also, because this isn't intended for commercial use, a security mechanism will be implemented in which the keys will cycle, rendering them useless even if they are compromised.
