### ISSUE TITLE
bugs with 10.128.0.0/9 subnet

### ISSUE THREAD

**Issue by iqdoctor** [complexorganizations/wireguard-manager#94]
Bug 1. Malformed ip 10.128.03 if I use 10.128.0.0/9 subnet
Unable to parse IP address: `10.128.03'

Bug 2.  qrencode: command not found (separate minor bug)

OS:  Ubuntu 20.10

```
root@vultr:~# wireguard-manager.sh
# wireguard-manager.sh
Do you want the interface or peer to be installed?
  1) Interface
  2) Peer
Interface Or Peer [1-2]: 1
What ipv4 subnet do you want to use?
  1) 10.8.0.0/24 (Recommended)
  2) 10.0.0.0/24
  3) Custom (Advanced)
Subnetwork Choice [1-3]: 3
Custom Subnet: 10.128.0.0/9
   ...
# default values
...

 Job for wg-quick@wg0.service failed because the control process exited with error code.
See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.
/usr/local/bin/wireguard-manager.sh: line 979: qrencode: command not found

...

tail -100 /var/log/syslog | grep pars
Feb 22 17:07:40 vultr wg-quick[8869]: Unable to parse IP address: `10.128.03'
Feb 22 17:07:40 vultr wg-quick[8869]: Configuration parsing error
```

**Comment by iqdoctor** [comment]
now I try use this

# This function just prints next ip
# https://stackoverflow.com/questions/33056385/increment-ip-address-in-a-shell-script
nextip(){
    IP=$1
    IP_HEX=$(printf '%.2X%.2X%.2X%.2X\n' `echo $IP | sed -e 's/\./ /g'`)
    NEXT_IP_HEX=$(printf %.8X `echo $(( 0x$IP_HEX + 1 ))`)
    NEXT_IP=$(printf '%d.%d.%d.%d\n' `echo $NEXT_IP_HEX | sed -r 's/(..)/0x\1 /g'`)
    echo "$NEXT_IP"
}

**Comment by Prajwal-Koirala** [comment]
Hey,
I will take a look at this once I get home, I found a way to get unlimited clients

**Comment by Prajwal-Koirala** [comment]
https://github.com/complexorganizations/wireguard-manager/pull/101

**Comment by Prajwal-Koirala** [comment]
Closed: Duplicate Issue.
https://github.com/complexorganizations/wireguard-manager/issues/94
